### ISSUE TITLE
Error "NewNodeInfo: Failed to get zones from Azure cloud provider." on Azure Stack Hub

### ISSUE THREAD

**Issue by songjiaxun** [kubernetes-sigs/azuredisk-csi-driver#1014]
**What happened**:
After a newer version of cloud-provider-azure is being used in 1.6.0, nodeserver gets errors: "NewNodeInfo: Failed to get zones from Azure cloud provider."

Because of the change of function [Zones](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go#L862-L870), inside the function [NewNodeInfo](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/pkg/optimization/skus.go#L133-L136) it will always get not `ok` and cause the issue.

**What you expected to happen**:
The node info should be populated properly on Azure Stack Hub.

**How to reproduce it**:
Whenever the CSI driver is installed, we have this issue.

**Anything else we need to know?**:
I will work to fix this by adding some flags for Azure Stack Hub to bypass this issue.

**Environment**:
- CSI Driver version: 1.6.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
if current node pool does not support zone, `topology.disk.csi.azure.com/zone: ""` is the correct setting, which could make sure PV could be scheduled to any node. We only set non-empty value for zone node, so this is expected and by design. It's not working **by accident**, it's working by our design.

**Comment by andyzhangx** [comment]
for azure stack, since it does not support zone, it will always print following error, I think we should remove following warning msg on Azure stack too, that could make logs more clear, anyway, that's not a blocking issue on Azure stack.
```
klog.Warningf("Failed to get zone from Azure cloud provider, nodeName: %v, error: %v", d.NodeID, err)
```

**Comment by songjiaxun** [comment]
@andyzhangx thanks for the explanation, I think you are right. I believe this issue is gone in version 1.7.0 because of this [commit](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/fed5fba85e6276aa09297701fd4312d6fc91f82b), in which you replaced `Fatalf` with `Errorf`. Closing this issue.
