### ISSUE TITLE
Storage volume not created on OpenShift Windows container w/ csi-proxy running

### ISSUE THREAD

**Issue by alinaryan** [kubernetes-sigs/azuredisk-csi-driver#1021]
**What happened**:
In pvc logs seeing: `waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator`

**What you expected to happen**:
Storage volume is created by external provisioner disk.csi.azure.com

**How to reproduce it**:
[deployment.txt](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7164983/deployment.txt)

**Anything else we need to know?**:
Azure-Disk logs: [csi-node-win-zfrxl-azuredisk.log](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7164999/csi-node-win-zfrxl-azuredisk.log)
Node Driver Registrar logs: [csi-node-win-zfrxl-node-driver-registrar.log](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7165010/csi-node-win-zfrxl-node-driver-registrar.log)
Liveness-probe logs: [csi-node-win-zfrxl-liveness-probe.log](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7165011/csi-node-win-zfrxl-liveness-probe.log)
statefulset-azuredisk-win-0 logs: [statefulset-azuredisk-win-0.txt](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7165045/statefulset-azuredisk-win-0.txt)
persistent-storage-statefulset-azuredisk-win-0 logs: [persistent-storage-statefulset-azuredisk-win-0.txt](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/7165055/persistent-storage-statefulset-azuredisk-win-0.txt)

**Environment**: OpenShift 4.9 on Azure 
- CSI Driver version: Version: mcr.microsoft.com/k8s/csi/azuredisk-csi:latest
- Kubernetes version (use `kubectl version`): Kubernetes Version: v1.22.0-rc.0+75ee307
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could your check disk driver controller logs, follow by: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case1-disk-createdeleteattachdetachsnapshotrestore-failed, and you may set up cluster identity for azure disk controller before deploy this driver, follow: https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-disk.md

**Comment by alinaryan** [comment]
I had attached the Azure-Disk driver logs. Are the Azure-Disk driver **controller** logs different from these?

> I0914 18:42:32.448941    7372 main.go:106] set up prometheus server on [::]:29605
I0914 18:42:33.510872    7372 azuredisk.go:133] 
DRIVER INFORMATION:
Build Date: "2021-09-14T02:34:36Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.8.0
Git Commit: b8be2e5112d5f84a455456e4ec22033409c71993
Go Version: go1.16
Platform: windows/amd64
Topology Key: topology.disk.csi.azure.com/zone
Streaming logs below:
I0914 18:42:33.510872    7372 azuredisk.go:136] driver userAgent: disk.csi.azure.com/v1.8.0 gc/go1.16 (amd64-windows) OSS-kubectl
I0914 18:42:34.063815    7372 azure_disk_utils.go:137] reading cloud config from secret kube-system/azure-cloud-provider
I0914 18:42:34.226836    7372 azure_auth.go:231] Using public cloud environment
I0914 18:42:34.226836    7372 azure_auth.go:119] azure: using client_id+client_secret to retrieve access token
I0914 18:42:34.226836    7372 azure_diskclient.go:67] Azure DisksClient using API version: 2020-12-01
I0914 18:42:34.226836    7372 azure.go:902] attach/detach disk operation rate limit QPS: 6.000000, Bucket: 10
I0914 18:42:34.631662    7372 safe_mounter_windows.go:362] using CSIProxyMounterV1, API Versions filesystem: v1, disk: v1, volume: v1
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: CLONE_VOLUME
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: LIST_VOLUMES
I0914 18:42:34.632705    7372 driver.go:81] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0914 18:42:34.632705    7372 driver.go:100] Enabling volume access mode: SINGLE_NODE_WRITER
I0914 18:42:34.632705    7372 driver.go:100] Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0914 18:42:34.632705    7372 driver.go:100] Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0914 18:42:34.632705    7372 driver.go:91] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0914 18:42:34.632705    7372 driver.go:91] Enabling node service capability: EXPAND_VOLUME
I0914 18:42:34.632705    7372 driver.go:91] Enabling node service capability: GET_VOLUME_STATS
I0914 18:42:34.634704    7372 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"C:\\\\csi\\\\csi.sock", Net:"unix"}
I0914 18:42:34.715363    7372 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0914 18:42:34.715363    7372 utils.go:96] GRPC request: {}
I0914 18:42:34.715363    7372 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.8.0"}
I0914 18:42:35.221285    7372 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0914 18:42:35.221285    7372 utils.go:96] GRPC request: {}
I0914 18:42:35.221285    7372 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.8.0"}
I0914 18:42:35.307438    7372 utils.go:95] GRPC call: /csi.v1.Node/NodeGetInfo
I0914 18:42:35.307438    7372 utils.go:96] GRPC request: {}
I0914 18:42:36.001252    7372 azure_vmclient.go:132] Received error in vm.get.request: resourceID: /subscriptions/5f675811-04fa-483f-9709-ffd8a9da03f0/resourceGroups//providers/Microsoft.Compute/virtualMachines/winworker-hjtrj, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
E0914 18:42:36.001252    7372 azure_standard.go:580] as.GetInstanceTypeByNodeName(winworker-hjtrj) failed: as.getVirtualMachine(winworker-hjtrj) err=Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
W0914 18:42:36.001252    7372 nodeserver.go:310] Failed to get instance type from Azure cloud provider, nodeName: winworker-hjtrj, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
I0914 18:42:36.014241    7372 azure_vmclient.go:132] Received error in vm.get.request: resourceID: /subscriptions/5f675811-04fa-483f-9709-ffd8a9da03f0/resourceGroups//providers/Microsoft.Compute/virtualMachines/csi-node-win-zfrxl, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
W0914 18:42:36.014540    7372 nodeserver.go:319] Failed to get zone from Azure cloud provider, nodeName: winworker-hjtrj, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
I0914 18:42:36.014567    7372 nodeserver.go:348] not found a matching size in getMaxDataDiskCount, VM Size: , use default volume limit: 16
I0914 18:42:36.014601    7372 utils.go:102] GRPC response: {"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}},"max_volumes_per_node":16,"node_id":"winworker-hjtrj"}

**Comment by andyzhangx** [comment]
@alinaryan which region are you trying on?
The api-version '2020-12-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

**Comment by andyzhangx** [comment]
api-version `2020-12-01` should be supported on public azure: https://docs.microsoft.com/en-us/rest/api/compute/disks, Not sure why `2020-12-01` is not supported on your platform. 
one workaround is set your `"cloud": "AzureStackCloud"` in your cloud config, it will then switch to use api-version `2019-03-01` which is supported on your platform.

**Comment by alinaryan** [comment]
I am on centralus region. I will try changing to AzureStackCloud in cloud config

**Comment by alinaryan** [comment]
I have been reading cloud conf from K8s secret following this: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/read-from-secret.md and then setting the secret name and namespace as an arg in the daemon set for my csi-driver. 

I realized I did not have the cloud field set in the azure.json file because I thought it defaults to AzurePublicCloud. I updated it and no longer seeing the `api version not supported` error.

**Comment by alinaryan** [comment]
Still seeing the following errors in the csi driver logs regarding instance type, zone and volume limit
>I0916 15:17:59.432320    5008 main.go:106] set up prometheus server on [::]:29605
I0916 15:17:59.910849    5008 azuredisk.go:133] 
DRIVER INFORMATION:
Build Date: "2021-09-14T02:34:36Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.8.0
Git Commit: b8be2e5112d5f84a455456e4ec22033409c71993
Go Version: go1.16
Platform: windows/amd64
Topology Key: topology.disk.csi.azure.com/zone
Streaming logs below:
I0916 15:17:59.910849    5008 azuredisk.go:136] driver userAgent: disk.csi.azure.com/v1.8.0 gc/go1.16 (amd64-windows) OSS-kubectl
I0916 15:17:59.954116    5008 azure_disk_utils.go:137] reading cloud config from secret kube-system/azure-cloud-provider
I0916 15:17:59.997574    5008 azure_auth.go:234] Using AzurePublicCloud environment
I0916 15:17:59.998194    5008 azure_auth.go:119] azure: using client_id+client_secret to retrieve access token
I0916 15:18:00.000428    5008 azure_diskclient.go:67] Azure DisksClient using API version: 2020-12-01
I0916 15:18:00.017251    5008 azure.go:902] attach/detach disk operation rate limit QPS: 6.000000, Bucket: 10
I0916 15:18:00.021204    5008 safe_mounter_windows.go:362] using CSIProxyMounterV1, API Versions filesystem: v1, disk: v1, volume: v1
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: CLONE_VOLUME
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: LIST_VOLUMES
I0916 15:18:00.021204    5008 driver.go:81] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0916 15:18:00.021204    5008 driver.go:100] Enabling volume access mode: SINGLE_NODE_WRITER
I0916 15:18:00.021204    5008 driver.go:100] Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0916 15:18:00.021204    5008 driver.go:100] Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0916 15:18:00.021204    5008 driver.go:91] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0916 15:18:00.021204    5008 driver.go:91] Enabling node service capability: EXPAND_VOLUME
I0916 15:18:00.021204    5008 driver.go:91] Enabling node service capability: GET_VOLUME_STATS
I0916 15:18:00.024672    5008 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"C:\\\\csi\\\\csi.sock", Net:"unix"}
I0916 15:18:00.039577    5008 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0916 15:18:00.039577    5008 utils.go:96] GRPC request: {}
I0916 15:18:00.041998    5008 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.8.0"}
I0916 15:18:00.486640    5008 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0916 15:18:00.486640    5008 utils.go:96] GRPC request: {}
I0916 15:18:00.486640    5008 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.8.0"}
I0916 15:18:01.686768    5008 utils.go:95] GRPC call: /csi.v1.Node/NodeGetInfo
I0916 15:18:01.686768    5008 utils.go:96] GRPC request: {}
W0916 15:18:23.041157    5008 nodeserver.go:310] Failed to get instance type from Azure cloud provider, nodeName: winworker-t766m, error: Get "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json": dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
W0916 15:18:44.055000    5008 nodeserver.go:319] Failed to get zone from Azure cloud provider, nodeName: winworker-t766m, error: Get "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json": dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I0916 15:18:44.055000    5008 nodeserver.go:348] not found a matching size in getMaxDataDiskCount, VM Size: , use default volume limit: 16
I0916 15:18:44.055000    5008 utils.go:102] GRPC response: {"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}},"max_volumes_per_node":16,"node_id":"winworker-t766m"}

**Comment by alinaryan** [comment]
My azure.json currently looks like the following. Anything else I should add?
>{
    "cloud":"AzurePublicCloud",
    "tenantId": "xxxxxxxxxxxxxxxxx",
    "aadClientId": "xxxxxxxxxxxxxxxxx",
    "aadClientSecret": "xxxxxxxxxxxxxxxxx",
    "subscriptionId": "xxxxxxxxxxxxxxxxx",
    "resourceGroup": "",
    "location": "centralus",
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": true
}

**Comment by andyzhangx** [comment]
you could disable instance metadata on your agent node by setting `"useInstanceMetadata": false`

**Comment by alinaryan** [comment]
Thanks, just tried that and still seeing same errors in logs

**Comment by alinaryan** [comment]
If I do that it I see the `api version not supported `error again

**Comment by andyzhangx** [comment]
hi @alinaryan I tried on `centralus` region, `2020-12-01` api-version works well, not sure why `2020-12-01` api-version is not available on your subscription in `centralus` region, would you try on a different region, e.g. `eastus2`, if `2020-12-01` api-version still not works, I think you may file an azure support ticket to enable `2020-12-01` api-version on your subscription.

**Comment by alinaryan** [comment]
thanks for all your help @andyzhangx. I tried on eastus2 and not seeing the api version error anymore. Currently seeing **"The Resource 'Microsoft.Compute/virtualMachines/csi-node-win-f6ldd' under resource group 'aliryan09-17-919-p897v-rg' was not found** in my azure disk logs. Having trouble figuring out how it can recognize my csi vm/where to enable that

>I0917 18:21:52.798709    6796 main.go:106] set up prometheus server on [::]:29605
I0917 18:21:54.016604    6796 azuredisk.go:133] 
DRIVER INFORMATION:
Build Date: "2021-09-17T03:40:42Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.8.0
Git Commit: cbba10b3c6b31fc6531d51f96a98d58d22ad35ad
Go Version: go1.16
Platform: windows/amd64
Topology Key: topology.disk.csi.azure.com/zone
Streaming logs below:
I0917 18:21:54.016604    6796 azuredisk.go:136] driver userAgent: disk.csi.azure.com/v1.8.0 gc/go1.16 (amd64-windows) OSS-kubectl
I0917 18:21:54.168798    6796 azure_disk_utils.go:137] reading cloud config from secret kube-system/azure-cloud-provider
I0917 18:21:54.186190    6796 azure_auth.go:234] Using AzurePublicCloud environment
I0917 18:21:54.186190    6796 azure_auth.go:119] azure: using client_id+client_secret to retrieve access token
I0917 18:21:54.186190    6796 azure_diskclient.go:67] Azure DisksClient using API version: 2020-12-01
I0917 18:21:54.186190    6796 azure.go:902] attach/detach disk operation rate limit QPS: 6.000000, Bucket: 10
I0917 18:21:54.186190    6796 safe_mounter_windows.go:377] using CSIProxyMounterV1, API Versions filesystem: v1, disk: v1, volume: v1
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: CLONE_VOLUME
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: EXPAND_VOLUME
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: LIST_VOLUMES
I0917 18:21:54.186190    6796 driver.go:81] Enabling controller service capability: LIST_VOLUMES_PUBLISHED_NODES
I0917 18:21:54.186190    6796 driver.go:100] Enabling volume access mode: SINGLE_NODE_WRITER
I0917 18:21:54.186190    6796 driver.go:100] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0917 18:21:54.186190    6796 driver.go:100] Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0917 18:21:54.186190    6796 driver.go:100] Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0917 18:21:54.186190    6796 driver.go:91] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0917 18:21:54.186190    6796 driver.go:91] Enabling node service capability: EXPAND_VOLUME
I0917 18:21:54.186190    6796 driver.go:91] Enabling node service capability: GET_VOLUME_STATS
I0917 18:21:54.201869    6796 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"C:\\\\csi\\\\csi.sock", Net:"unix"}
I0917 18:21:55.824496    6796 utils.go:95] GRPC call: /csi.v1.Identity/GetPluginInfo
I0917 18:21:55.824496    6796 utils.go:96] GRPC request: {}
I0917 18:21:55.824496    6796 utils.go:102] GRPC response: {"name":"disk.csi.azure.com","vendor_version":"v1.8.0"}
I0917 18:21:58.231858    6796 utils.go:95] GRPC call: /csi.v1.Node/NodeGetInfo
I0917 18:21:58.231858    6796 utils.go:96] GRPC request: {}
I0917 18:21:59.046160    6796 azure_vmclient.go:132] Received error in vm.get.request: resourceID: /subscriptions/5f675811-04fa-483f-9709-ffd8a9da03f0/resourceGroups/aliryan09-17-919-p897v-rg/providers/Microsoft.Compute/virtualMachines/csi-node-win-f6ldd, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/virtualMachines/csi-node-win-f6ldd' under resource group 'aliryan09-17-919-p897v-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
I0917 18:21:59.046462    6796 azure_wrap.go:195] Virtual machine "csi-node-win-f6ldd" not found
W0917 18:21:59.046588    6796 azure_wrap.go:75] Unable to find node csi-node-win-f6ldd: instance not found
W0917 18:21:59.046588    6796 nodeserver.go:319] Failed to get zone from Azure cloud provider, nodeName: winworker-7s6f2, error: instance not found
I0917 18:21:59.046588    6796 nodeserver.go:344] got a matching size in getMaxDataDiskCount, VM Size: STANDARD_D2S_V3, MaxDataDiskCount: 4
I0917 18:21:59.046588    6796 utils.go:102] GRPC response: {"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}},"max_volumes_per_node":4,"node_id":"winworker-7s6f2"}

**Comment by andyzhangx** [comment]
could you set the correct resourceGroup in cloud config file:
```
"resourceGroup": "resource-group-name", 
```

BTW, `NodeGetInfo` malfunction is actually not a blocking issue, it just could not get zone info and MaxDataDiskCount

**Comment by alinaryan** [comment]
My current azure.json has the correct resourceGroup. I cross referenced in the portal:
>{
"cloud":"AzurePublicCloud",
"tenantId": "xxxxxxxxxxxxxxxxx",
"aadClientId": "xxxxxxxxxxxxxxxxx",
"aadClientSecret": "xxxxxxxxxxxxxxxxx",
"subscriptionId": "xxxxxxxxxxxxxxxxx",
"resourceGroup": "aliryan09-17-919-p897v-rg",
"location": "eastus2",
"useManagedIdentityExtension": false,
"useInstanceMetadata": false
}

And I can see the resource group referenced in the csi driver logs. 
>Received error in vm.get.request: resourceID: /subscriptions/5f675811-04fa-483f-9709-ffd8a9da03f0/resourceGroups/aliryan09-17-919-p897v-rg/providers/Microsoft.Compute/virtualMachines/csi-node-win-f6ldd, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/virtualMachines/csi-node-win-f6ldd' under resource group 'aliryan09-17-919-p897v-rg' was not found.

**Comment by andyzhangx** [comment]
is there a vm name `csi-node-win-f6ldd` under `aliryan09-17-919-p897v-rg`? `csi-node-win-f6ldd` looks like a driver pod name.

**Comment by alinaryan** [comment]
Correct. No vm exists under `csi-node-win-f6ldd-rg`. `csi-node-win-f6ldd` is my Windows vm and `csi-node-win-f6ldd` is my azure-disk driver pod. Trying to figure out why it might think my driver pod is a vm

**Comment by andyzhangx** [comment]
it's from here:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/0bfa1a5efaff104ddd5554e41018eab717cda1ab/deploy/csi-azuredisk-node-windows.yaml#L104

**Comment by alinaryan** [comment]
I found my error. Azure-disk csi driver has to be enabled by a feature gate on OpenShift. Found this out here: https://docs.openshift.com/container-platform/4.1/nodes/clusters/nodes-cluster-enabling-features.html 
After I added featureSet: "TechPreviewNoUpgrade" my pvc was bound by the managed-csi storage class. Thank you for all your help
