### ISSUE TITLE
Requires root permissions when using ZRS disk

### ISSUE THREAD

**Issue by mohanchazz** [kubernetes-sigs/azuredisk-csi-driver#1025]
When using ZRS disk , pod requires root user permission to access the disk.
Getting permission denied, when pod run as user 1000.
Any options to resolve this issue.

**Comment by andyzhangx** [comment]
could you use the workaround here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/949

**Comment by mohanchazz** [comment]
The above works, Thanks @andyzhangx .
