### ISSUE TITLE
Make skuname parameter case consistent across disk and file

### ISSUE THREAD

**Issue by anshulahuja98** [kubernetes-sigs/azuredisk-csi-driver#1036]
**What happened**:
Just accessing programmatically, PV objects for az disk and az file (CSI)
Az Disk in the VolumeAttributes has it mentioned  as "skuname" whereas for Az File it is "skuName"

Not a major bug, just a slight inconsistency which can be improved for better programmatic access and consistency.

**What you expected to happen**:

**How to reproduce it**:
Az file
![image](https://user-images.githubusercontent.com/36476228/135592724-c641fc03-78f4-4ae9-83d7-43a4ebd907f9.png)

Az Disk
![image](https://user-images.githubusercontent.com/36476228/135592778-7950ca24-af0f-4913-a725-599f8df359cd.png)

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
csi driver parameters are actually case insensitive, so both work, while I think we may unify all parameters as `skuName` which is easy to read.
