### ISSUE TITLE
[question] Does this driver support Azure ultra disks?

### ISSUE THREAD

**Issue by ahrtr** [kubernetes-sigs/azuredisk-csi-driver#1038]
Please see [Using Azure ultra disks](https://docs.microsoft.com/en-us/azure/virtual-machines/disks-enable-ultra-ssd?tabs=azure-cli#attach-an-ultra-disk), the question is that does this CSI Driver support it? 

If yes, then I assume that we should set the flag "“--ultra-ssd-enabled true" when creating the worker VMs. Could anyone confirm this? Thanks.

**Comment by andyzhangx** [comment]
ultra disk is supported, just use `skuname: UltraSSD_LRS` in storage class setting:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/d641e5132f5b5b3af2f1af59d1873f95440b238d/deploy/example/storageclass-azuredisk-csi.yaml#L1-L11
