### ISSUE TITLE
failed to get azure instance id for node "aks-default-xxxxxxx-vmss000001" (instance not found)

### ISSUE THREAD

**Issue by prasadrajesh** [kubernetes-sigs/azuredisk-csi-driver#1047]
**What happened**:
Unable to attach volume to Node.

**What you expected to happen**:
It should attach block volume to the pod.

**How to reproduce it**:

`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS  # Currently shared disk only available with premium SSD
  maxShares: "2"
  cachingMode: None  # ReadOnly cache is not available for premium SSD with maxShares>1
reclaimPolicy: Delete

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi  # minimum size of shared disk is 256GB (P15)
  volumeMode: Block
  storageClassName: managed-csi`

**Anything else we need to know?**:
I want to mount single volume to 2 nodes and I am using VMSS.
`I1011 11:57:40.689523       1 controllerserver.go:436] GetDiskLun returned: <nil>. Initiating attaching volume "/subscriptions/xxxx-xxxx-xxx/resourceGroups/xxxx-xxxxx-xxx/providers/Microsoft.Compute/disks/pvc-69eb84b7-c2c6-4ea2-becf-06531b23c397" to node "aks-default-23380162-vmss000001".
I1011 11:57:40.689554       1 azure_vmss_cache.go:320] Assuming node "aks-default-23380162-vmss000001" is managed by VMSS since DisableAvailabilitySetNodes is set to true
I1011 11:57:40.689567       1 azure_vmss.go:709] Couldn't find VMSS for node aks-default-23380162-vmss000001, refreshing the cache
W1011 11:57:40.741028       1 azure_vmss.go:715] Unable to find node aks-default-23380162-vmss000001: instance not found
E1011 11:57:40.741051       1 azure_controller_common.go:445] error of getting data disks for node "aks-default-23380162-vmss000001": instance not found
E1011 11:57:40.741066       1 utils.go:100] GRPC error: rpc error: code = NotFound desc = failed to get azure instance id for node "aks-default-23380162-vmss000001" (instance not found)`

**Environment**:
- CSI Driver version: v1.8.0
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by prasadrajesh** [comment]
`{
    "cloud": "AzurePublicCloud",
    "tenantId": "xxxxxx-xxxxx-xxxxxxxx",
    "subscriptionId": "xxxxxx-xxxxx-xxxxxxxx",
    "aadClientId": "msi",
    "aadClientSecret": "msi",
    "resourceGroup": "azure-rajesh-use2-resources",
    "location": "eastus2",
    "vmType": "vmss",
    "subnetName": "azure-rajesh-use2-subnet",
    "securityGroupName": "aks-agentpool-23380162-nsg",
    "vnetName": "cerence-onecloud-sspi-dev-use2-vnet",
    "vnetResourceGroup": "cerence-onecloud-sspi-dev-use2-default-rg",
    "routeTableName": "aks-agentpool-23380162-routetable",
    "primaryAvailabilitySetName": "",
    "primaryScaleSetName": "aks-default-23380162-vmss",
    "cloudProviderBackoffMode": "v2",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderRateLimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "cloudProviderRateLimitQPSWrite": 10,
    "cloudProviderRateLimitBucketWrite": 100,
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "7c332944-eda6-4695-xxxxx-xxxxxxxxx",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Standard",
    "disableOutboundSNAT": false,
    "excludeMasterFromStandardLB": true,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}`

**Comment by prasadrajesh** [comment]
Still same issue. Even today, I tried with redeploy AKS.

**Comment by prasadrajesh** [comment]
Sure. I will let you know.

**Comment by prasadrajesh** [comment]
It is working well on 1.21.

**Comment by andyzhangx** [comment]
could you only schedule to one vmss node pool and only schedule pod with disk mount to that node pool to narrow down issue?
and if it's a testing cluster, try install master branch version: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md

**Comment by prasadrajesh** [comment]
I will try. Thank you @andyzhangx :)

**Comment by anshulahuja98** [comment]
@prasadrajesh, I faced a similar issue
The reason in my case was that the cluster MSI did not have permission on the RG containing the nodes/nodepool
And hence could not fetch the instance

Hope this helps

**Comment by andyzhangx** [comment]
As @anshulahuja98 pointed out, there is possibility that identity which is used by azure disk controller does not have permission to list agent node, and grant permission would solve the issue.

**Comment by andyzhangx** [comment]
in such case, you may find following list vm error logs in azure disk controller logs:
```
{"log":"E0105 08:51:00.712545       1 azure_vmss_cache.go:68] VirtualMachineScaleSetsClient.List failed: &{false 403 0001-01-01 00:00:00 +0000 UTC {\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Compute/virtualMachineScaleSets/read' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute' or the scope is invalid. If access was recently granted, please refresh your credentials.\"}}}\n","stream":"stderr","pod":"csi-azuredisk-controller-7ff9b555b7-tsq77","containerID":"405b5d6cb4010179cbcb283364cf36b6c6750153b24dfaa3190ae55693363ec1"}
```
