### ISSUE TITLE
node-driver-registrar CrashLoopBackOff on AKS 1.20 or below

### ISSUE THREAD

**Issue by lynshi** [kubernetes-sigs/azuredisk-csi-driver#1067]
**What happened**:
Our `csi-azuredisk-node` Pods are in `CrashLoopBackOff` state after restarting. The DaemonSet itself is 181 days old, but it looks like all the Pods in it are less than 3 days old, so something on AKS must've forced a restart. On other clusters, the Pods in the `cs-azuredisk-node` DaemonSet that were not recently restarted are still running happily.

Happy to provide cluster details etc internally for targeted debugging as needed.

The failing container is `node-driver-registrar`. The liveness probe is failing with the following error:
```
  Warning  Unhealthy  9m28s (x2751 over 2d5h)  kubelet  Liveness probe failed: flag provided but not defined: -mode
Usage of /csi-node-driver-registrar:
  -add_dir_header
      If true, adds the file directory to the header
  -alsologtostderr
      log to standard error as well as files
  -connection-timeout duration
      The --connection-timeout flag is deprecated
  -csi-address string
      Path of the CSI driver socket that the node-driver-registrar will connect to. (default "/run/csi/socket")
  -health-port int
      TCP port for healthz requests. Set to 0 to disable the healthz server.
  -kubelet-registration-path string
      Path of the CSI driver socket on the Kubernetes host machine.
  -log_backtrace_at value
      when logging hits line file:N, emit a stack trace
  -log_dir string
      If non-empty, write log files in this directory
  -log_file string
      If non-empty, use this log file
  -log_file_max_size uint
      Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
      log to standard error instead of files (default true)
  -plugin-registration-path string
      Path to Kubernetes plugin registration directory. (default "/registration")
  -skip_headers
      If true, avoid header prefixes in the log messages
  -skip_log_headers
      If true, avoid headers when opening log files
  -stderrthreshold value
      logs at or above this threshold go to stderr (default 2)
  -v value
      number for the log level verbosity
  -version
      Show version.
  -vmodule value
          comma-separated list of pattern=N settings for file-filtered logging
```

**Anything else we need to know?**:
The nodes aren't under MemoryPressure, DiskPressure, or PIDPressure.

I can't seem to find the related addon with `az aks addon list`, but I'm pretty sure we created the cluster with `--aks-custom-headers EnableAzureDiskFileCSIDriver=true`.

**Environment**:
- CSI Driver version: Here are the images used by containers in the Pod: `mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.2.0`, `mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.0.1`, and `mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.2.0.5`
- Kubernetes version (use `kubectl version`): 1.18.14

**Comment by andyzhangx** [comment]
the fix would be rolled out this week, and use following way to workaround:

run following operations, and modify `failureThreshold` of `livenessProbe` in `node-driver-registrar` container to `900000000`
```console
kubectl edit ds csi-azuredisk-node -n kube-system
kubectl edit ds csi-azurefile-node -n kube-system
```
 
```yaml
            livenessProbe:
              exec:
                command:
                  - /csi-node-driver-registrar.exe
                  - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                  - --mode=kubelet-registration-probe
              failureThreshold: 900000000
```

**Comment by fmbahrt** [comment]
I was told by the Azure support that the CSI drivers are only formally supported from k8s version 1.21 and up. Can anyone support this claim? I am experiencing the same issue..

**Comment by andyzhangx** [comment]
> I was told by the Azure support that the CSI drivers are only formally supported from k8s version 1.21 and up. Can anyone support this claim? I am experiencing the same issue..

@fmbahrt before 1.21, CSI drivers managed by AKS are in preview, pls use the above workaround to make it work first. The AKS fix would be rolled out next week.

**Comment by lynshi** [comment]
> AKS fix would be rolled out this week, and use following way to workaround from user side:
> 
> run following operations, and modify `failureThreshold` of `livenessProbe` in `node-driver-registrar` container to `900000000`
> 
> ```
> kubectl edit ds csi-azuredisk-node -n kube-system
> kubectl edit ds csi-azurefile-node -n kube-system
> ```
> 
> ```yaml
>             livenessProbe:
>               exec:
>                 command:
>                   - /csi-node-driver-registrar.exe
>                   - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
>                   - --mode=kubelet-registration-probe
>               failureThreshold: 900000000
> ```
> 
> Since `failureThreshold` is not set in AKS managed CSI driver, this setting won't be reverted even CSI driver is managed by AKS.

Just so I understand what's going on here - we setting the threshold to something high so we aren't blocked by `CrashLoopBackOff` for now.  When AKS rolls out the fix, since the AKS managed driver doesn't set this value will we have to reset the threshold back to 3 so that the liveness probe actually has an effect?

**Comment by andyzhangx** [comment]
@lynshi `livenessProbe` should not be enabled for AKS version < 1.21, there is a fix to remove the whole `livenessProbe` setting in the next 2 weeks, no action from AKS user side from fix rolled out.

**Comment by lynshi** [comment]
Thanks for clarifying! Appreciate your help. We used the workaround and we're now able to attach volumes again.

**Comment by andyzhangx** [comment]
close this issue since the fix would be rolled out complete in all regions within 20 hours.
