### ISSUE TITLE
[failing test] aks-engine-windows-dockershim-azure-disk-master job is failing consistently

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/azuredisk-csi-driver#1088]
https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-dockershim-azure-disk-master has been failing since at least 11/01 (can't see history past that). 

10 of the tests are failing 100% of the time.

cc @andyzhangx

**Comment by andyzhangx** [comment]
another PR change: https://github.com/kubernetes-sigs/windows-testing/pull/295
