### ISSUE TITLE
[V2] data disk count is invalid in shared disk mode

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#1097]
**What happened**:
1) create a node pool with 2 nodes (DS2_v2 size), each node could attach 8 data disks at most
2) create 8 pods with one disk mount each (with `maxShares: 2`)
3) create the 9th pod with one disk mount, disk would be scheduled to one node, stuck in `ContainerCreating` state forever, and error would be like following:

```
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Warning  FailedScheduling    47s               default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    47s               default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           40s               default-scheduler        Successfully assigned default/statefulset-azuredisk-share-8 to aks-agentpool-70325192-vmss000001
  Warning  FailedAttachVolume  7s (x7 over 39s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-54c55671-22d4-4d8c-ba69-834634e65573" : rpc error: code = FailedPrecondition desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "The maximum number of data disks allowed to be attached to a VM of this size is 8.",
    "target": "dataDisks"
  }
}
```

Root cause: in shared disk mode, current maximum data disk count calculation is invalid any more, need to adjust

**What you expected to happen**:
It's ok that with with `maxShares: 2`, we could only attach 8 data disks, while the 9th pod should be in `Pending` state instead of  scheduled to one node which obviously could not attach any disk any more.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: V2
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aslafy-z** [comment]
@andyzhangx I'm encountering the same issue with non shared disks (maxShares: 0). Did you published the PR code in a docker image I can test in my environment? Thank you

**Comment by andyzhangx** [comment]
> @andyzhangx I'm encountering the same issue with non shared disks (maxShares: 0). Did you published the PR code in a docker image I can test in my environment? Thank you

@aslafy-z on which version did you hit this issue? usually it's caused by detach failure on specific node, and thus that disk is not counted.

**Comment by aslafy-z** [comment]
@andyzhangx I've seen this behavior with the latest v1.10.0 version, after upgrading from v1.9.0 (we were hitting the issue before). I've seen some detach failures, will have a look if old PVs are still attached to nodes.

**Comment by edreed** [comment]
@aslafy-z This issue was specific to the v2 driver which is under development. If you are experiencing an issue with the v1 driver, please create a new issue for it.
