### ISSUE TITLE
Broken documentation link 

### ISSUE THREAD

**Issue by naioja** [kubernetes-sigs/azuredisk-csi-driver#1099]
**What happened**:
Looking at the https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/README.md we can see the link for Tune disk performance on Linux is broken : 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/enhancements/feat-add-ability-to-tune-azuredisk-performance-parameters.md

**What you expected to happen**:
Please review the link URL and fix it.

This link was mentioned in the AKS release notes from September https://github.com/Azure/AKS/releases/tag/2021-09-30

**Comment by andyzhangx** [comment]
should point to https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/perf-profiles.md, already fixed, thanks.
