### ISSUE TITLE
Add CSI Ephemeral Volume Support

### ISSUE THREAD

**Issue by nearora-msft** [kubernetes-sigs/azuredisk-csi-driver#1189]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
we don't want to support this feature because this feature requires attaching disk in `NodePublishVolume` on agent node, while usually agent node identity does not have any access to the disk by default, this would break easily. And it's a nice to have feature, customer could use PV/PVC way to mount static disk.

**Comment by nearora-msft** [comment]
With v2 driver, attaching a disk is handled by the attach_detach controller - which performs the attach/detach operations asynchronously while reconciling AzVolumeAttachment objects. In case of CSI ephemeral volumes, we could create an AzVolumeAtachment CRI in NodePublishVolume and wait for it's status to change to Attached and then mount the volume. In NodeUnpublishVolume, we could delete the AzVolumeAtachment , which would cause the disk to be detached. Do you think it'd make sense to do it this way?

**Comment by andyzhangx** [comment]
then I think you could implement this feature in V2

**Comment by edreed** [comment]
> In case of CSI ephemeral volumes, we could create an AzVolumeAtachment CRI in NodePublishVolume

We need to be careful here. Allowing a node to create an AzVolumeAttachment CRI may allow a node to attach a disk to which it does not have access, but the control plane does. This would be an EoP threat.

It seems the intent of the CSI ephemeral volume was to provide access to node local storage, so using this to orchestrate the attachment of a managed disk seems is questionable.

**Comment by andyzhangx** [comment]
> > In case of CSI ephemeral volumes, we could create an AzVolumeAtachment CRI in NodePublishVolume
> 
> We need to be careful here. Allowing a node to create an AzVolumeAttachment CRI may allow a node to attach a disk to which it does not have access, but the control plane does. This would be an EoP threat.
> 
> It seems the intent of the CSI ephemeral volume was to provide access to node local storage, so using this to orchestrate the attachment of a managed disk seems is questionable.

agree, this is not a common scenario, also azure disk csi driver already supports general ephemeral volume which provides similar functionality.

**Comment by edreed** [comment]
Given the potential EoP threat implementing this feature would introduce, I am closing this issue.
