### ISSUE TITLE
Support customized VM hostname

### ISSUE THREAD

**Issue by guoxun19** [kubernetes-sigs/azuredisk-csi-driver#1207]
**Is your feature request related to a problem?/Why is this needed**

When using customized hostname which is not the same as Azure VM name, the driver cannot work.

**Describe the solution you'd like in detail**

The driver should support customized hostname which is not the same as Azure VM name.

**Describe alternatives you've considered**

**Additional context**

1. Use self-built K8S on Azure VM, no VMSS used
2. CSI driver version: latest
3. Kubernetes version: 1.21
4. OS version: CentOS 7.3 with kernel 5.4

**Comment by andyzhangx** [comment]
close this issue since actually it's a cloud provider azure feature request, I have put all details in this link: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1273

**Comment by andyzhangx** [comment]
btw, since that's a new requirement in cloud provider azure, would you try `--hostname-override` with kubelet option to override hostname setting in kubelet first, after set, restart node, and then I think azure disk csi driver would work with correct vm name.
