### ISSUE TITLE
CSI driver reads consumption

### ISSUE THREAD

**Issue by mbolanos23** [kubernetes-sigs/azuredisk-csi-driver#1224]
**Is your feature request related to a problem?/Why is this needed**

The CSI driver seems to have got hungrier on GetDisk requests. I'm experiencing throttling issue because of this.

**Describe the solution you'd like in detail**

Need a way to tune / improve the way the CSI driver is behaving so GetDisk requests are controlled and withing limits.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
> @andyzhangx On AKS Cluster 1.22.6 with OS image AKSUbuntu-1804-2022.03.07 where the latest driver is azuredisk-csi:v1.12.0 is still present the error
> 
> AttachVolume.Attach failed for volume "pvc-555sd4564df-xxxx" : rpc error: code = NotFound desc = Volume not found, failed with error: Retriable: true, RetryAfter: 109s, HTTPStatusCode: 0, RawError: azure cloud provider throttled for operation GetDisk with reason "client throttled"
> 
> Does this version already includes the fix #1181 ?

@alftio did you create lots of disk volumes in the same time? there is also a fix in v1.13.0, it would not GetDisk when creating volumes: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1213

**Comment by alftio** [comment]
@andyzhangx Thanks.
Yes there were a considerable number creates of disk concurrently. We will wait for the 1.13 version

**Comment by andyzhangx** [comment]
pls try with latest v1.16 version, GetDisk throttling should be fixed.
