### ISSUE TITLE
[V2] verify-examples.sh leaks deployment and stateful set when running e2e tests

### ISSUE THREAD

**Issue by jmclong** [kubernetes-sigs/azuredisk-csi-driver#1288]
**What happened**:
When running e2e tests, `/hack/verify_examples.sh` runs as a part of the `ginkgo.AfterSuite` test hook in `test/e2e/suite_test.go`. This script leaks a deployment and stateful set that can interfere to subsequent test runs that expect a clean system.

**What you expected to happen**:
I expect there to be no deployment or stateful set left over after running an e2e test. 

**How to reproduce it**:
1. Run an e2e test
2. Execute `kubectl get all`
3. Observer that there is a deployment and stateful set in the default namespace after the test run.

**Anything else we need to know?**:
This is part of the testing infrastructure and not related to features or functionality.

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jmclong** [comment]
Currently, this script runs after the test suite for e2e tests if `testconsts.IsTestingMigration || !testconsts.IsUsingInTreeVolumePlugin` and again if `!testconsts.IsTestingMigration && !testconsts.IsUsingCSIDriverV2`. The framework checks to make sure it has a 0 exit code otherwise the test fails. 

I am wondering if it would be better for the script to be called from a testcase instead because it takes about ~2 minutes to resolve, which can really add up when you're debugging a test and running it multiple times.

This script is also called from the `test/external-e2e/run.sh` script when `make e2e-test` is invoked and $EXTERNAL_E2E_TEST is defined.

**Comment by andyzhangx** [comment]
` verify-examples.sh` is for verifying examples, otherwise we need to set up a standalone test pipeline for example verifications, that would be wasting resource.

**Comment by jmclong** [comment]
> ` verify-examples.sh` is for verifying examples, otherwise we need to set up a standalone test pipeline for example verifications, that would be wasting resource.

Hi Andy,

Thanks for the comment. That makes sense. 

Given the current use-cases, would it be appropriate to trap script exit and execute ```kubectl delete -f "$EXAMPLE --ignore-not-found``` for each example? 

I have some code that does this, but I was trying to understand if that would disturb the use in `make e2e-test` or when applying  the files again when `!testconsts.IsTestingMigration && !testconsts.IsUsingCSIDriverV2`.

Thanks,
Joshua

**Comment by andyzhangx** [comment]
the second `verify-examples.sh` test is for testing `deploy/install-driver.sh`, while in main_v2 branch, it's just skipped since `IsUsingCSIDriverV2` is always `true`:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/7644adb8d3649d77e73ef3a3cd70d464fa412212/test/e2e/suite_test.go#L185
