### ISSUE TITLE
1.17.0 helm chart - controller errors with: flag provided but not defined: -vmss-cache-ttl-seconds

### ISSUE THREAD

**Issue by jgreat** [kubernetes-sigs/azuredisk-csi-driver#1297]
**What happened**:

Three problems.  

1.) `csi-azuredisk-controller` `azuredisk` sidecar container is using `mcr.microsoft.com/k8s/csi/azuredisk-csi:latest`.

Using "latest" is not a great practice and kind of defeats the purpose of having a versioned helm chart.

2.) `mcr.microsoft.com/k8s/csi/azuredisk-csi:latest` doesn't support the flag `--vmss-cache-ttl-seconds` added in to the 1.17.0 version of the helm chart. 

Probably because "latest" might be v1.16.0? 

3.) there is no `mcr.microsoft.com/k8s/csi/azuredisk-csi:v1.17.0` image published.

Not sure what's going on here, if 1.17.0 isn't the latest release, why is it in your helm chart index as the latest release?

**What you expected to happen**:

Find the latest versioned helm chart release (1.17.0) and install it.  Chart should install the latest (1.17.0) version of azuredisk utilities.

**How to reproduce it**:

Install the latest release of the azuredisk-csi-driver helm chart.

```
helm repo add azuredisk-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
helm repo update
helm search repo -l azuredisk-csi-driver
NAME                                     	CHART VERSION	APP VERSION	DESCRIPTION                                       
azuredisk-csi-driver/azuredisk-csi-driver	v1.17.0      	latest     	Azure disk Container Storage Interface (CSI) St...
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.17.0 (well that's what should have been installed)
- Kubernetes version (use `kubectl version`): v1.23.5+k3s1
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: Helm v3.7.0

**Comment by andyzhangx** [comment]
hi @jgreat pls install v1.16.0 version:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/charts#install-a-specific-version
```
helm install azuredisk-csi-driver azuredisk-csi-driver/azuredisk-csi-driver --namespace kube-system --version v1.16.0
```

latest versioned helm chart is mainly for testing purpose. Thanks.
