### ISSUE TITLE
[V2] v2 driver scheduler extender should skip filter and prioritize if pods has no volumes from 1.22+

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#1347]
**What happened**:
v2 driver scheduler extender tries to skip filter and prioritize if pod has no volumes, while start from k8s 1.22, all pods would have `kube-api-access-xxx` volume which is used to access api-server by default, which means the skip check actually does not work, **ALL** pods will go through scheduler-extender and call `getAzDriverNodes` and `getAzVolumeAttachments` which are expensive calls. We should test and check what's the impact of scheduler-extender when there are large num of dummy pods, 
 - e.g. 20K dummy pods on a 100 nodes with already 1000 disk attachments.
in such testing scenario, there would be 20K calls of node and disk attachments list in the scheduler extender, that's really big overload.

 - related code
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/6c49a06e0b8eb664a8ae165da058bf4292456189/pkg/azdiskschedulerextender/azdiskschedulerextender.go#L142-L150

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/6c49a06e0b8eb664a8ae165da058bf4292456189/pkg/azdiskschedulerextender/azdiskschedulerextender.go#L232-L235

**What you expected to happen**:
v2 driver scheduler extender should skip filter and prioritize if pods has no volumes from 1.22+

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v2
- Kubernetes version (use `kubectl version`): 1.22
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by landreasyan** [comment]
Agree that we have to find another way to skip filter and prioritize calls for pods with no volumes but also wanted to mention that we get azvolumeattachments and azdrivernodes from cache, so `getAzDriverNodes` and `getAzVolumeAttachments` calls are not as expensive.

**Comment by andyzhangx** [comment]
pls also get time cost of filter and prioritize call for every pod scheduling, I filed an issue here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1387

**Comment by edreed** [comment]
This issue is addressed by #1389 & #1448 .
