### ISSUE TITLE
[v2] cluster-autoscaler does not support custom scheduling config

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#1354]
**What happened**:
cluster-autoscaler does not support custom scheduling config, details: https://github.com/kubernetes/autoscaler/issues/4518
should test v2 driver shared disk with cluster-autoscaler, check whether there is potential issue:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
We've added E2E tests in AKS to validate the V1 & V2 drivers with the Cluster Autoscaler.
