### ISSUE TITLE
[V2] Downgrading from V2 driver to V1 could break some workflows due to missing LUN in volume attachment

### ISSUE THREAD

**Issue by landreasyan** [kubernetes-sigs/azuredisk-csi-driver#1357]
**What happened**:
After downgrading from V2 version of the driver to V1, some stateful workflows failed to restart as volume attachment resources in V2 driver don't have LUN in the status field due to doing attachments asynchronously. 

**What you expected to happen**:
Stateful workloads should be able to restart on the same node and failover to new nodes without any issues.

**How to reproduce it**:

1. InstallV2 driver.
2. Start stateful workload
3. Uninstall V2 driver and install V1
4. Delete the pods of the stateful workload and let the stateful set recreate the pods
5. Pods that start on the same node as before, fail with " lun not provided"

**Anything else we need to know?**:
Expected status for volume attachment obj: 
```
Status:
Attached: true
Attachment Metadata:
LUN: 0
Events: <none>
```

Status for volume attachment obj with failure: 
```
Status:
Attached: true
Events: <none>
```

Complete error: 

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    9m29s                 default-scheduler  Successfully assigned perf-test/statefulset-azuredisk-2 to aks-nodepool1-22248711-vmss000002
  Warning  FailedMount  7m26s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[kube-api-access-n49np persistent-storage]: timed out waiting for the condition
  Warning  FailedMount  71s (x12 over 9m25s)  kubelet            MountVolume.MountDevice failed for volume "pvc-05eeed02-4742-449e-bf83-621d56f54bce" : rpc error: code = InvalidArgument desc = lun not provided
  Warning  FailedMount  42s (x3 over 5m12s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage kube-api-access-n49np]: timed out waiting for the condition
```

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by edreed** [comment]
This was fixed by #1361 .
