### ISSUE TITLE
[V2]get time cost metrics of filter and prioritize call for every pod scheduling

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#1387]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

get time cost metrics of filter and prioritize call for every pod scheduling

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
@edreed have you got the time cost data of filter and prioritize call during pod scheduling? And also per below code, the `metrics.ExponentialBuckets` setting is not reasonable, should at least input following `0.0001, 0.001, 0.01, 0.1, 1` between `(0.00001, 2)`

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/7e836ff9c2344e02440a41df512a2069accd8e3e/pkg/azdiskschedulerextender/azdiskschedulerextender_metrics.go#L36-L50

**Comment by edreed** [comment]
@andyzhangx Thanks for pointing this out and suggesting more appropriate bucketing values. We'll get this fixed soon.

**Comment by landreasyan** [comment]
We are setting fairly smaller buckets because our latencies are low. Our buckets are set to cover (0.0001, 0.4096) in factors of 2. I am not sure having bigger buckets as suggested makes more sense in this case. I would even argue that we can make the buckets smaller.
