### ISSUE TITLE
Cannot install CSI driver 

### ISSUE THREAD

**Issue by oriolaf** [kubernetes-sigs/azuredisk-csi-driver#1425]
has anyone had a problem with installation of  csi  using kubectl?
the error is as below , when i try to local deploy the latest version 

curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/v1.20.0/deploy/install-driver.sh | bash -s v1.18.0 snapshot --
Installing Azure Disk CSI driver, version: v1.18.0 ...
The connection to the server 127.0.0.1:51695 was refused - did you specify the right host or port?

**Comment by andyzhangx** [comment]
that means kubectl cannot connect to api-server, run `kubectl get no` to check.
And if you are using AKS 1.21+ cluster, CSI driver is already installed by default.

**Comment by oriolaf** [comment]
I am using minikube.

**Comment by andyzhangx** [comment]
I don't think you can attach a disk to node in minikube, so this driver is not supported on minikube.
