### ISSUE TITLE
What is the behaviour of the Driver when Secret is updated

### ISSUE THREAD

**Issue by gauravAggrahari** [kubernetes-sigs/azuredisk-csi-driver#1427]
Hi,
What would be the expected behaviour of the driver when I update the secret. 
Do I need to restart the `Dayployment` and `Daemonset` or the changes would be taken dynamically ?

Regards,
Gaurav

**Comment by andyzhangx** [comment]
> Hi, What would be the expected behaviour of the driver when I update the secret. Do I need to restart the `Dayployment` and `Daemonset` or the changes would be taken dynamically ?
> 
> Regards, Gaurav

@gauravAggrahari azure disk csi driver does not use secret, do you mean azure file csi driver? For azure file driver, restart driver won't make azure file remount on the node.

**Comment by gauravAggrahari** [comment]
Hi @andyzhangx ,
So what would be the correct course of action when the secret needs to be updated. 
I guess AzureDisk driver reads from Secrets as well when the cloud-config file is not found right ?

The question is applicable for both `azuredisk-csi-driver` and `azurefile-csi-driver` ?

**Comment by gauravAggrahari** [comment]
I was referring to this link for azuredisk driver
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/read-from-secret.md

**Comment by andyzhangx** [comment]
> I was referring to this link for azuredisk driver https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/read-from-secret.md

@gauravAggrahari o, that secret change requires restart driver(deployment and daemonset pods).
