### ISSUE TITLE
Create a persistent volume in the Azure Edge Zone location

### ISSUE THREAD

**Issue by kunaltelang** [kubernetes-sigs/azuredisk-csi-driver#1437]
**Is your feature request related to a problem?/Why is this needed**
A customer using a self-managed Kubernetes cluster in an Azure Edge Zone is unable to create a PV and attach it to the POD running in that Edge Zone.

**Describe the solution you'd like in detail**
The current CSI driver does not support "extended location". When we tried the Edge Zone ID in the "location" column "attatlanta1" we got the following error.

Warning ProvisioningFailed 82s (x10 over 5m39s) disk.csi.azure.com_af-svr0_7c020c5e-f73f-45b5-81ee-a7a6441d441f failed to provision volume with StorageClass "azure-wavelength": rpc error: code = Unknown desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"LocationNotAvailableForResourceType","message":"The provided location 'attatlanta1 (East US2)' is not available for resource type 'Microsoft.Compute/disks'. List of available regions for the resource type is 'southeastasia,eastus2,centralus,westeurope,eastus,northcentralus,southcentralus,westus,northeurope,eastasia,brazilsouth,westus2,westcentralus,ukwest,uksouth,japaneast,japanwest,canadacentral,canadaeast,centralindia,southindia,australiaeast,australiasoutheast,koreacentral,koreasouth,westindia,francecentral,southafricanorth,uaenorth,australiacentral,switzerlandnorth,germanywestcentral,norwayeast,jioindiawest,westus3,swedencentral'."}}

Please add support for "extended location" in the CSI Driver, which should allow for the customers to deploy/create PVCs in the Edge Zones.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
@kunaltelang what's your azure cloud config file(`azure.json`), for edge zone support, you need to set following two more fields:
```
	// The name of site where the cluster will be deployed to that is more granular than the region specified by the "location" field.
	// Currently only public ip, load balancer and managed disks support this.
	ExtendedLocationName string `json:"extendedLocationName,omitempty" yaml:"extendedLocationName,omitempty"`
	// The type of site that is being targeted.
	// Currently only public ip, load balancer and managed disks support this.
	ExtendedLocationType string `json:"extendedLocationType,omitempty" yaml:"extendedLocationType,omitempty"`
```

**Comment by kunaltelang** [comment]
Thank you @andyzhangx . Let me try this and get back if this works.

**Comment by kunaltelang** [comment]
hello @andyzhangx , your suggestions about adding those two fields seems to have helped! As you mentioned, the customer was instructed to do the following things. 
1. update /etc/kubernetes/azure.json file on the agent node with the following additional fields:
    "extendedLocationType": "edgezone",
    "extendedLocationName": "attatlanta1",
2. Then restart csi driver controller pod

The customer reported that after trying this, they were able to attach the PVC successfully to the POD.

thank you so very much for your timely input and the guidance!

**Comment by andyzhangx** [comment]
thanks for the check. close this issue.

**Comment by andyzhangx** [comment]
would be addressed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1533
