### ISSUE TITLE
Set priority class to system critical

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#148]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add priorityClassName: system-cluster-critical and priorityClassName: system-node-critical to controller and node YAMLs respectively

Make the driver high priority and less likely to be evicted

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Here we can get the detail about pod priority and preemption.
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
