### ISSUE TITLE
[V2] azuredisk_csi_driver_controller_publish_volume latency metrics is incorrect in v2 driver

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#1492]
**What happened**:
In `ControllerPublishVolume` func, disk attach is async call, so `azuredisk_csi_driver_controller_publish_volume` latency metrics is incorrect in v2 driver now, need to get actuall disk attach latency, same issue for `azuredisk_csi_driver_controller_unpublish_volume` latency metrics

```
azure_metrics.go:114] "Observed Request Latency" latency_seconds=0.000512805 request="azuredisk_csi_driver_controller_publish_volume" resource_group="kubetest-rfl35lck" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="disk.csi.azure.com" volumeid="/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-rfl35lck/providers/Microsoft.Compute/disks/pvc-065ce6f7-649d-4bd2-af11-c15b48e8e556" node="k8s-agentpool-18545342-vmss000001" result_code="succeeded"
```

cc @edreed 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by landreasyan** [comment]
The issue is fixed by #1531. New `attach_volume_latency` is added to track the latency of the actual attach operation.
