### ISSUE TITLE
support HTTPS_PROXY, HTTP_PROXY in chart config

### ISSUE THREAD

**Issue by garelp** [kubernetes-sigs/azuredisk-csi-driver#1509]
**What happened**:
My network is behind corporate proxy and it seems the the provisioner is trying ot contact Azure pubkic managemeent URL. I tried to setup the usual ENV variable HTTPS_PROXY and HTTP_PROXY without success. It seems the process is ingoring completly the proxy variables.

How Can I specifiy the http proxy in order for the provisioner procces to contact Azure Management url ? 

Don't tell me use Azure Firewall or nat gateway, it's not possible.

**Environment**:

- CSI Driver version: 1.21
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g. from /etc/os-release): RHEL7.9
- Kernel (e.g. `uname -a`): 3.10.0-1160.76.1.el7.x86_64
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I think you could define `AZURE_ENVIRONMENT_FILEPATH` and in that file, define your `managementPortalURL`, `resourceManagerEndpoint`, etc.

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/06f968afbc05b793b850895516bfee56b8f11696/charts/v1.22.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml#L142-L145

https://github.com/Azure/go-autorest/blob/7dd32b67be4e6c9386b9ba7b1c44a51263f05270/autorest/azure/environments.go#L28

**Comment by garelp** [comment]
Thanks for you insight but it's not how it should work. We need have a way to configure http/https proxy in order for the controller to reach the Azure management endpoint which are public. 
I don't know why it's not already implemented since it's supposed to be a profesionnal solution. Most of the corporate enviroment are using proxies to reach outside and don't allow direct internet connections.

**Comment by andyzhangx** [comment]
@garelp I think `HTTPS_PROXY` env may work, just run `kubectl edit deployment -n kube-system csi-azuredisk-controller`, and then add `HTTPS_PROXY` env

```
          env:
            - name: AZURE_CREDENTIAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: azure-cred-file
                  key: path
                  optional: true
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: HTTPS_PROXY
              value: https://xxx
```

in my case, I set a wrong proxy since I don't have a real one, it would fail with following error, once I removed `HTTPS_PROXY` env, it works, so I think it's taking effect by leveraging go lib:
```
I0914 03:21:19.049182       1 azure_managedDiskController.go:94] azureDisk - creating new managed Name:pvc-ebce78f6-1d19-4dfb-a8c5-0480ab6d1f3b StorageAccountType:StandardSSD_LRS Size:10
I0914 03:21:28.094501       1 azure_retry.go:203] Backoff retrying PUT "https://management.azure.com/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/mc_andy-aks1219_group_andy-aks1219_uksouth/providers/Microsoft.Compute/disks/pvc-ebce78f6-1d19-4dfb-a8c5-0480ab6d1f3b?api-version=2021-04-01" with error Put "https://management.azure.com/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/mc_andy-aks1219_group_andy-aks1219_uksouth/providers/Microsoft.Compute/disks/pvc-ebce78f6-1d19-4dfb-a8c5-0480ab6d1f3b?api-version=2021-04-01": Bad Request
```

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/5597d85cba7d188d80df6060f252c474a4b8ef14/vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/armclient/azure_armclient.go#L73-L74

```
// FromEnvironment returns a Config instance populated from the
// environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the
// lowercase versions thereof). HTTPS_PROXY takes precedence over
// HTTP_PROXY for https requests.
//
// The environment values may be either a complete URL or a
// "host[:port]", in which case the "http" scheme is assumed. An error
// is returned if the value is a different form.
func FromEnvironment() *Config {
	return &Config{
		HTTPProxy:  getEnvAny("HTTP_PROXY", "http_proxy"),
		HTTPSProxy: getEnvAny("HTTPS_PROXY", "https_proxy"),
		NoProxy:    getEnvAny("NO_PROXY", "no_proxy"),
		CGI:        os.Getenv("REQUEST_METHOD") != "",
	}
}
```

**Comment by garelp** [comment]
thanks .. It worked. Actually it's better to put the proxy ENV config on the right pods.

**Comment by garelp** [comment]
Now it would be great to include this proxy configuration onto the Helm chart.

**Comment by andyzhangx** [comment]
> Now it would be great to include this proxy configuration onto the Helm chart.

@garelp thanks for the confirm, we will add this config later.

**Comment by andyzhangx** [comment]
add two new chart config fields as `driver.httpsProxy`, `driver.httpProxy` for csi driver controller and node daemonset:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/16ce4b79a9017241a00bb6994d99f5afe9832dbb/charts/latest/azuredisk-csi-driver/values.yaml#L144-L152

**Comment by garelp** [comment]
Hello.. I've tried the new version with the httpsProxy and httpProxy value, it works for the value settings but I missed the noproxy variable.. I need to set it by hand... the noProxy doesn't exists..

**Comment by garelp** [comment]
It's unusable without the noproxy variable set accordingly.

**Comment by andyzhangx** [comment]
> ProxyFromEnvironment

@garelp what's the `NO_PROXY` value you would setting? I thought we only need to set `HTTPS_PROXY` and `HTTP_PROXY`.
and you could set that env var in the driver deployment.

**Comment by garelp** [comment]
The noproxy is a list of domain/ip/network you want to access directly wtihout passing the proxy which is usualy to go outside towards internet. Basically noproxy contains your internal networks and domains.
