### ISSUE TITLE
Add docs for Volume Cloning feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#153]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

Volume Cloning feature is alpha in v1.15: https://kubernetes-csi.github.io/docs/volume-cloning.html
In driver v0.3.0, we already added volume cloning feature: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/0deb537f201a376179831171de80f9a10ec2c6cb/pkg/azuredisk/azuredisk.go#L266-L268
need to check whether it works and if it works, need docs

**Additional context**

**Comment by andyzhangx** [comment]
could you take a look? @ZeroMagic

**Comment by ZeroMagic** [comment]
ok, I will check it.

**Comment by ZeroMagic** [comment]
Currently, the driver just uses snapshotID as SourceResourceID. So actually it does not support `volume cloning` feature.
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/8d06e40/pkg/azuredisk/controllerserver.go#L185-L202
I will fix it and add docs as soon as possible.
