### ISSUE TITLE
Increasing size of volumes in AKS can lead to instance in VMSS going into a Failed state

### ISSUE THREAD

**Issue by SStorm** [kubernetes-sigs/azuredisk-csi-driver#1575]
**What happened**:
We have a bunch of statefulsets where we occasionally want to resize (increase) the PVCs attached to the pods in them. We do this by first scaling the STS to 0, and then resizing the PVCs all at once. Sometimes the PVC resize fails with an error like this:
```
0s          Warning   FailedMount                  pod/pod-name-0                           MountVolume.WaitForAttach failed for volume "pvc-fdae35d9-4c4e-4997-b832-aa1fadd3a6ed" : volume attachment is being deleted
```

When looking at the VMSS in Azure, it shows that the instance where this volume was attached is in a Failed state. The VMSS instance has a disk that is marked for deletion, but won't delete. 

This situation does not fix itself eventually. The only way to fix it is to force-delete the instance in the VMSS.

**What you expected to happen**:
Resize completes successfully.

**How to reproduce it**:
See above.

**Anything else we need to know?**:

Instance in VMSS has status:

```
Disk property change for disk 'pvc-fdae35d9-4c4e-4997-b832-aa1fadd3a6ed' is not allowed when disk is marked for deletion. Target: '/subscriptions/[snip]/resourceGroups/[snip]/providers/Microsoft.Compute/disks/pvc-fdae35d9-4c4e-4997-b832-aa1fadd3a6ed'.
```

**Environment**:

- CSI Driver version: 1.23.0
- Kubernetes version (use `kubectl version`): v1.22.11
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS   
- Kernel (e.g. `uname -a`): 5.4.0-1090-azure
- Install tools: Managed Kubernetes (AKS)

**Comment by andyzhangx** [comment]
@SStorm This is a vmss issue, pls file an Azure ticket, thanks.
