### ISSUE TITLE
Driver fails to unpublish a volume associated with a drained and deleted Node (release v1.19.0)

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/azuredisk-csi-driver#1687]
**What happened**:
When a Node is deleted, the CSI driver fails to delete any VolumeAttachment resource that is attached to the Node. (Technically, it fails to remove its finalizer from the resource)

**What you expected to happen**:
The CSI driver should remove its finalizer from the VolumeAttachment resource.

**How to reproduce it**:

1. Create a cluster  (I used Cluster API Azure Infrastructure Provider)
2. Deploy Azure CSI driver.
3. Create a default Storage Class backed by the Azure CSI driver.
4. Create a PersistentVolumeClaim and Pod that mounts a volume backed by this claim.
5. Verify this results in a new VolumeAttachment resource.
6. Drain the node.
7. Delete the node.
8. Observe the CSI driver log for "Could not detach volume" errors. These repeat until all finalizers are removed from the VolumeAttachment resource, and it is garbage collected. 

**Anything else we need to know?**:
I believe the bug was introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/commit/fd315b0a0f056c6e18fd26ccb107e00391cd966c#diff-e6715e02b5aa5f8b693bf3e14dd99dd9a160f0f0f1481df96891af24fc3a5fffR331-R342.

```log
I0110 02:55:13.316057       1 utils.go:77] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
I0110 02:55:13.316090       1 utils.go:78] GRPC request: {"node_id":"dlipovetsky-md-0-k58bd","volume_id":"/subscriptions/REDACTED/resourceGroups/dlipovetsky/providers/Microsoft.Compute/disks/pvc-107c420c-ade8-447e-a4b7-c6cf3193e4ef"}
I0110 02:55:13.316269       1 controllerserver.go:444] Trying to detach volume /subscriptions/REDACTED/resourceGroups/dlipovetsky/providers/Microsoft.Compute/disks/pvc-107c420c-ade8-447e-a4b7-c6cf3193e4ef from node dlipovetsky-md-0-k58bd
I0110 02:55:13.316299       1 azure_vmss_cache.go:332] Node dlipovetsky-md-0-k58bd has joined the cluster since the last VM cache refresh, refreshing the cache
I0110 02:55:13.355886       1 azure_backoff.go:101] VirtualMachinesClient.List(dlipovetsky) success
E0110 02:55:13.355922       1 azure_vmss.go:367] Unable to find node dlipovetsky-md-0-k58bd: not a vmss instance
W0110 02:55:13.355932       1 azure_controller_common.go:319] failed to get azure instance id (not a vmss instance)
I0110 02:55:13.356043       1 azure_metrics.go:112] "Observed Request Latency" latency_seconds=0.039690339 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="dlipovetsky" subscription_id="REDACTED" source="disk.csi.azure.com" volumeid="/subscriptions/REDACTED/resourceGroups/dlipovetsky/providers/Microsoft.Compute/disks/pvc-107c420c-ade8-447e-a4b7-c6cf3193e4ef" node="dlipovetsky-md-0-k58bd" result_code="failed"
E0110 02:55:13.356083       1 utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/REDACTED/resourceGroups/dlipovetsky/providers/Microsoft.Compute/disks/pvc-107c420c-ade8-447e-a4b7-c6cf3193e4ef from node dlipovetsky-md-0-k58bd: failed to get azure instance id for node "dlipovetsky-md-0-k58bd": not a vmss instance
```

By this logic, if a Node is not found in the cache, the cache is refreshed and an error is returned. However, if the Node is deleted, it will never be found in the cache.

This code is present in releases v0.7.3 through 1.25.0. However, I cannot reproduce the issue in v1.25.0.

The code is substantially changed in release v1.26.0, as the result of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2288.  I cannot reproduce this issue using CSI driver v1.26.0.

Because the issue is not in current releases, this bug report is likely just for reference, and can be closed.
 
I discussed this issue first in the context of the Cluster API Azure Infrastructure Provider here: https://kubernetes.slack.com/archives/CEX9HENG7/p1673384255536689

**Environment**:

- CSI Driver version:  v1.19.0
- Kubernetes version (use `kubectl version`): v1.24.
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Others:

**Comment by andyzhangx** [comment]
@dlipovetsky thanks for the info. this issue is fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2288 which is in azure disk csi driver v1.24.0 and later version.
mainly it's fixed by following code snippet:https://github.com/kubernetes-sigs/cloud-provider-azure/blob/ed5b9f4364c4165269c2bc93201de6ea122563b8/pkg/provider/azure_vmss.go#L403-L408
