### ISSUE TITLE
Add dataAccessAuthMode parameter to snapshot 

### ISSUE THREAD

**Issue by anshulahuja98** [kubernetes-sigs/azuredisk-csi-driver#1702]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Need an option to enable AAD on snapshots taken through CSI driver.
![image](https://user-images.githubusercontent.com/36476228/214215990-7c39282d-d134-4f12-92aa-884fa7a18807.png)

Parameter inside Snapshot JSON 
      "dataAccessAuthMode": "AzureActiveDirectory",

https://learn.microsoft.com/en-us/rest/api/compute/disks/create-or-update?tabs=HTTP#dataaccessauthmode

**Describe alternatives you've considered**

**Additional context**

**Comment by anshulahuja98** [comment]
@andyzhangx  is there any ETA by when this can be prioritized?

**Comment by andyzhangx** [comment]
we are planning to add this parameter in next week's v1.27 release, roll out on AKS would be after next week.
