### ISSUE TITLE
Restore snapshot on re-created cluster

### ISSUE THREAD

**Issue by slawekww** [kubernetes-sigs/azuredisk-csi-driver#1711]
**What happened**:
Created  AKS cluster with Azure CSI disk driver.
Created application with PVC using Azure CSI storageClass.
Created Azure snapshot with pv using Velero 1.10.0 (feature=EnableCSI on)
Deleted AKS cluster
Re-created AKS cluster with the same name in the same Azure resource group.
Restore backup using Velero.

Error AttachVolume as "ResourceNotFound"
```
  Warning  FailedAttachVolume  81m (x9 over 98m)     attachdetach-controller  AttachVolume.Attach failed for volume "pvc-256e7259-d2cf-42a6-96b0-8febb636b173" : rpc error: code = NotFound desc = Volume not found, failed with error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/disks/pvc-256e7259-d2cf-42a6-96b0-8febb636b173' under resource group 'aks_resource_group' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
  Warning  FailedMount         107s (x35 over 97m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[vmstorage-volume], unattached volumes=[vmstorage-volume kube-api-access-rhz9m]: timed out waiting for the condition
```

pv manifest:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  creationTimestamp: "2023-01-31T09:06:31Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/disk-csi-azure-com
  labels:
    velero.io/backup-name: velero-backup
    velero.io/restore-name: initial-restore
  name: pvc-256e7259-d2cf-42a6-96b0-8febb636b173
  resourceVersion: "16398"
  uid: 586de88b-a3dc-4bde-a0c6-9855b7262971
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 127Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: name
    namespace: namespace
    resourceVersion: "15631"
    uid: 92ca3927-8e0c-4563-b027-5c4c81f47aba
  csi:
    driver: disk.csi.azure.com
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pvc-256e7259-d2cf-42a6-96b0-8febb636b173
      csi.storage.k8s.io/pvc/name: name
      csi.storage.k8s.io/pvc/namespace: namespace
      requestedsizegib: "127"
      skuname: Standard_LRS
      storage.kubernetes.io/csiProvisionerIdentity: 1675151843882-8081-disk.csi.azure.com
    volumeHandle: /subscriptions/111-11111-1111/resourceGroups/aks_managed_resource_group/providers/Microsoft.Compute/disks/pvc-256e7259-d2cf-42a6-96b0-8febb636b173
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - westeurope-2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi-hdd
  volumeMode: Filesystem
status:
  phase: Bound
```

pvc manifest:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    backup.velero.io/must-include-additional-items: "true"
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    velero.io/backup-name: backup
    velero.io/volume-snapshot-name: velero-snapshot-id
  creationTimestamp: "2023-01-31T09:06:32Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: vmstorage
    app.kubernetes.io/instance: helm-release
    app.kubernetes.io/name: helm-release
    backup.velero.io/must-include-additional-items: "true"
    velero.io/backup-name: velero-default-20230131083157
    velero.io/restore-name: initial-restore
    velero.io/volume-snapshot-name: velero-snapshot-id
  name: name
  namespace: namespace
  resourceVersion: "15637"
  uid: 92ca3927-8e0c-4563-b027-5c4c81f47aba
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-snapshot-id
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-snapshot-id
  resources:
    requests:
      storage: 127Gi
  storageClassName: managed-csi-hdd
  volumeMode: Filesystem
  volumeName: pvc-256e7259-d2cf-42a6-96b0-8febb636b173
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 127Gi
  phase: Bound
```

**What you expected to happen**:
Expect that Snapshot is used to restore disk even if disk reference does not exist.

**How to reproduce it**:
Defined in **What happened** section.

**Anything else we need to know?**:
It is recovery of AKS cluster with the same name using Velero backup and Azure CSI drivers.

**Environment**:
- CSI Driver version: azuredisk-csi:v1.24.0.2
- Kubernetes version (use `kubectl version`): AKS 1.24.6
- OS (e.g. from /etc/os-release): AKS 1.24.6 image Ubuntu 18
- Kernel (e.g. `uname -a`): AKS 1.24.6 image Ubuntu 18
- Install tools: velero 1.10.0
- Others: n/a

**Comment by andyzhangx** [comment]
the error said `The Resource 'Microsoft.Compute/disks/pvc-256e7259-d2cf-42a6-96b0-8febb636b173' under resource group 'aks_resource_group' was not found`, could you make sure whether that disk is under resource group 'aks_resource_group'

**Comment by slawekww** [comment]
It is not possible. In my scenario, I run backup, deleted cluster (AKS), then re-created cluster and run restore.
PV (as managed by StorageClass Azure CSI disk) does not exist on re-created cluster.

**Comment by andyzhangx** [comment]
@slawekww that's because snapshot is taken in the same resource group as AKS cluster node resource group, and when AKS cluster is deleted with node resource group, snapshots are also deleted. Pls use `resourceGroup: EXISTING_RESOURCE_GROUP_NAME` to create snapshot on an external resource group.

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:
  resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when snapshot is not taken in the same resource group as agent node
  incremental: "true"  # available values: "true"(by default), "false"
```

**Comment by slawekww** [comment]
@andyzhangx In my config CR VolumeSnapshotClass is pointed to external Azure Resource group:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: disk.csi.azure.com
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com
deletionPolicy: Retain
parameters:
  resourcegroup: "extenal_resource_group"
```
After backup, I've checked that Azure snapshots are stored correctly in external Azure resource group.

After restore, I've checked that pvc is in state bound. Problem I think is reference at `volumeHandle` to Azure disk which does not exist on re-created cluster as it is new cluster with the same name and within the same resource group.

**Comment by andyzhangx** [comment]
cc @umagnus could you help taking a look?

**Comment by slawekww** [comment]
Control plane (AKS) is re-created using the same settings (name, resource group name, subscription etc) using Terraform.
Resource group name is the same as for initial cluster and created by module and AKS managed-resource-group is the same.
[kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster)

I've not seen authorization error during my testing as you indicated at event logs.

Please advise if scenario as mentioned in this ticket is supported. Maybe it is not supported.

**Comment by andyzhangx** [comment]
@slawekww I think you have already granted write permission for that external rg `kubeitshared033-dev-rg_k8s-we` in the deleted cluster, this time you need to grant write permission again for the new cluster control plane identity (that is, you aks cluster name).

as long as you could make sure following disk uri(in `volume_id`) exists and your control plane identity has write permission to resource group `kubeitshared033-dev-rg_k8s-we`, it should work:
```
I0131 13:35:54.575151       1 utils.go:78] GRPC request: {"node_id":"aks-default-36632826-vmss000000","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-256e7259-d2cf-42a6-96b0-8febb636b173","csi.storage.k8s.io/pvc/name":"vmstorage-volume-vmstorage-0","csi.storage.k8s.io/pvc/namespace":"victoria-metrics","requestedsizegib":"127","skuname":"Standard_LRS","storage.kubernetes.io/csiProvisionerIdentity":"xxx-xxx-disk.csi.azure.com"},"volume_id":"/subscriptions/xxx/resourceGroups/kubeitshared033-dev-rg_k8s-we/providers/Microsoft.Compute/disks/pvc-256e7259-d2cf-42a6-96b0-8febb636b173"}
```

**Comment by slawekww** [comment]
Scenario is:
1. AKS cluster created
2. Backup created by Velero as Azure Snapshot on external resource group
3. AKS deleted (it means Azure Resource group `kubeitshared033-dev-rg_k8s-we` has been deleted and disks for AKS), like `az aks delete` and AKS managed resource group is removed automatically.
4. Cluster is re-created using the same Azure resource group and AKS managed resource group is recreated but no disks there.
5. Restore backup and error as **disk is not present** which is expected, I want disk to be created from backup.

However it means that Azure Snapshot for volume has no sense to store it as backup as it cannot be used to restore and recreate disk on re-created AKS cluster.

**Comment by andyzhangx** [comment]
@slawekww what's the `kubectl get VolumeSnapshot snapshot-name`? is it recovered? if snapshot exists and you could create disk pvc based on that VolumeSnapshot, following by: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/snapshot#3-create-a-new-pvc-based-on-snapshot

**Comment by andyzhangx** [comment]
I have tried taking snapshot on external rg, as long as `volumesnapshotcontent` object is restored in the new cluster, it has `snapshotHandle` field which could find that snapshot. Pls make sure your new cluster control plane identity has access to the external rg, I got following error in the beginning:
```
 however, it does not have permission to perform action 'Microsoft.Compute/disks/beginGetAccess/action' on the linked scope(s) '/subscriptions/xxx/resourceGroups/andy-aks123/providers/Microsoft.Compute/snapshots/snapshot-569574e7-7ed9-4fb4-ad4d-23c956bba78b' or the linked scope(s) are invalid."}}
```

And I found contributor role does not work until I set owner role for my control plane identity, then creating a pvc based on snapshot works

```
# k get VolumeSnapshotContent snapcontent-569574e7-7ed9-4fb4-ad4d-23c956bba78b -o yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  creationTimestamp: "2023-02-03T09:18:23Z"
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  generation: 1
  name: snapcontent-569574e7-7ed9-4fb4-ad4d-23c956bba78b
  resourceVersion: "1390881"
  uid: 699ed83a-b1e8-4d5f-b3b3-08a67d2fa530
spec:
  deletionPolicy: Delete
  driver: disk.csi.azure.com
  source:
    volumeHandle: /subscriptions/xxx/resourceGroups/mc_andy-aks125_andy-aks125_uksouth/providers/Microsoft.Compute/disks/pvc-bcbf60ec-7955-4755-9bf5-e8099f889e36
  volumeSnapshotClassName: csi-azuredisk-vsc
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: azuredisk-volume-snapshot2
    namespace: default
    resourceVersion: "1390824"
    uid: 569574e7-7ed9-4fb4-ad4d-23c956bba78b
status:
  creationTime: 1675415907475179500
  readyToUse: true
  restoreSize: 10737418240
  snapshotHandle: /subscriptions/xxx/resourceGroups/andy-aks123/providers/Microsoft.Compute/snapshots/snapshot-569574e7-7ed9-4fb4-ad4d-23c956bba78b
```

**Comment by slawekww** [comment]
Thank you for testing and guidance! 
I believe my control plane identity has Contributor role, not Owner during testing.
Let me repeat tests and ensure that it would work.

**Comment by andyzhangx** [comment]
@slawekww how did you solve this issue?

**Comment by slawekww** [comment]
I have no tested it yet. I do not want to keep bug open if no time to test.

**Comment by slawekww** [comment]
I had some time and re-tested scenario - please find attached manifests created on re-created cluster by Velero and error log.
I've checked that Control Plane SP has Contributor role on external_resource_group with Azure snapshots.
It is the same SP as used for initial cluster.

[restore.zip](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/10708236/restore.zip)

Tested with granting Control Plane role Owner to external_resource_group (backup) and the same error.
If you have any suggestions why it does not work, please advice.

**Comment by slawekww** [comment]
And VolumeSnapshotClass manifest:

```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Retain
driver: disk.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: disk.csi.azure.com
parameters:
  resourceGroup: external_resource_group # backup
```

**Comment by andyzhangx** [comment]
@slawekww have you figured out this issue?

**Comment by slawekww** [comment]
@andyzhangx Yes, I've started to use Velero Kopia and copy files from persistent volumes to Azure Storage Account and no more use snapshots for Azure.

Issue could be closed however Microsoft should consider strategy for restoring persistent volumes on re-created AKS cluster for AKS default storage classes, e.g. for incident removal of cluster or disaster recovery.
