### ISSUE TITLE
Documentation - accessModes support

### ISSUE THREAD

**Issue by DanielYWoo** [kubernetes-sigs/azuredisk-csi-driver#1763]
**Is your feature request related to a problem?/Why is this needed**
I cannot find the document about accessModes support for each offering, can we put it into the document? e.g.,
Standard_LRS: RWO, ROM
Premium_LRS: RWO, ROM, RWM

Thanks

**Comment by andyzhangx** [comment]
Azure Disk  CSI driver only supports RWO for all disk sku, we have RWO in all examples, e.g.
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/d6f39a1f15fc115070fe72c4e98326fc41f332e7/deploy/example/pvc-azuredisk-csi.yaml#L7-L8

**Comment by DanielYWoo** [comment]
> Azure Disk CSI driver only supports RWO for all disk sku, we have RWO in all examples, e.g.
> 
> https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/d6f39a1f15fc115070fe72c4e98326fc41f332e7/deploy/example/pvc-azuredisk-csi.yaml#L7-L8

Thanks for the info. Can we put it into the README.md? since this is very important and I cannot find it documented anywhere.
