### ISSUE TITLE
azureblob-fuse-premium cannot provision requested storage size

### ISSUE THREAD

**Issue by sscchh2001** [kubernetes-sigs/azuredisk-csi-driver#1769]
**What happened**: I tried to mount 30GB and 200GB blobfuse pvc using the azureblob-fuse-premium SC. After mounting the PV to pod, in the pod I can only see 8GB mounted.

**What you expected to happen**: the mounted storage size should be exactly what I requested in yaml file.

**How to reproduce it**:
Environment is in Azure China.
AKS cluster version is 1.23.12, has blob driver feature enabled.
Az CLI version is 2.46.0.

PVC and pod yaml:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-fuse
  annotations:
        volume.beta.kubernetes.io/storage-class: azureblob-fuse-premium
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 30Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: mcr.azk8s.cn/oss/nginx/nginx:1.17.3-alpine
    volumeMounts:
    - mountPath: "/mnt/blobfuse"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-blob-fuse

PVC status:
kubectl get pvc
NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
azure-blob-fuse                         Bound    pvc-610e42cf-b038-4d88-a2ba-b271acc78e70   30Gi       RWX            azureblob-fuse-premium   54m

Pod status:
kubectl get pod
NAME           READY   STATUS    RESTARTS      AGE
mypod          1/1     Running   0             29m

kubectl exec -it mypod -- /bin/sh
/ # df -k
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay              129886128  27366240 102503504  21% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                  2012904         0   2012904   0% /sys/fs/cgroup
**blobfuse               8152540        36   7716792   0% /mnt/blobfuse**
/dev/sda1            129886128  27366240 102503504  21% /etc/hosts
/dev/sda1            129886128  27366240 102503504  21% /dev/termination-log
/dev/sda1            129886128  27366240 102503504  21% /etc/hostname
/dev/sda1            129886128  27366240 102503504  21% /etc/resolv.conf
shm                      65536         0     65536   0% /dev/shm
tmpfs                  2209236        12   2209224   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                  2012904         0   2012904   0% /proc/acpi
tmpfs                    65536         0     65536   0% /proc/kcore
tmpfs                    65536         0     65536   0% /proc/keys
tmpfs                    65536         0     65536   0% /proc/timer_list
tmpfs                    65536         0     65536   0% /proc/sched_debug
tmpfs                  2012904         0   2012904   0% /proc/scsi
tmpfs                  2012904         0   2012904   0% /sys/firmware

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 
image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.26.2
image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.26.2
imageID: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi@sha256:4be036dd35933a8889a5b14f98a8377e8057e652a64f0bc3908225d58db34daa
image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.26.2
image: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi:v1.26.2
imageID: mcr.azk8s.cn/oss/kubernetes-csi/azuredisk-csi@sha256:4be036dd35933a8889a5b14f98a8377e8057e652a64f0bc3908225d58db34daa

- Kubernetes version (use `kubectl version`): 
client: 1.26.2, server: 1.23.12

- OS (e.g. from /etc/os-release):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.2
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

- Kernel (e.g. `uname -a`): 
Linux mypod1 5.4.0-1091-azure #96~18.04.1-Ubuntu SMP Tue Aug 30 19:15:32 UTC 2022 x86_64 Linux

- Install tools:
- Others:

**Comment by andyzhangx** [comment]
hi @sscchh2001 the size in blobfuse file system does not reflect the actual size, for blob storage, the capacity is actually more than 100 TiB, so even you create a 200GB blob storage container, it can store 100TiB data.

**Comment by andyzhangx** [comment]
also this is azure disk driver repo, you should go to https://github.com/kubernetes-sigs/blob-csi-driver/issues
