### ISSUE TITLE
Enable leader election for controller service

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#177]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

To improve availability of controller service when it is being restarted or rescheduled. We should support leader election for controller service.

After this we could switch to use deployment for controller service instead of stateful set.

**Describe alternatives you've considered**

**Additional context**

/kind feature
/assign @Masquerade0097

**Comment by bcho** [comment]
@andyzhangx Hi, I can help with this issue, can you assign it to me? I will give the plan of changes in the next few days. Thanks!

**Comment by bcho** [comment]
@andyzhangx The `csi-provisioner` / `csi-attacher` / `csi-snapshotter` have [builtin leader election support](https://github.com/kubernetes-csi/external-provisioner#command-line-options), can we just enable leader election in these containers?

**Comment by bcho** [comment]
I made a draft pr in #224, please have a look @andyzhangx

**Comment by andyzhangx** [comment]
this feature is already in v0.5.0 release
