### ISSUE TITLE
[V2] Crash using V2 on RKE2 on Azure VMs

### ISSUE THREAD

**Issue by joelcomp1** [kubernetes-sigs/azuredisk-csi-driver#1784]
**What happened**:
Deploying RKE2 on Azure via Rancher using the Azure Disk CSI causes crashing of the mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v2.0.0-beta.10 container

**What you expected to happen**:
Provision PVCs in my cluster and create PVs from those requests.

**How to reproduce it**:

Install the Azure CSI V2 Helm chart, tested both v2.0.0-beta.6 and v2.0.0-beta.10

**Anything else we need to know?**:

I had this working at one point and not it doesn't, I even had it working in one of my two containers, it provisioned storage then the pod restarted and it stopped working again.  When it fails, this is the crash I get in my container

I0322 11:20:27.891037       1 skus.go:123] NewNodeInfo: Starting to populate node and disk sku information.
I0322 11:20:28.142735       1 util.go:124] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 21893
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185ac67]

goroutine 1 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*availabilitySet).GetInstanceTypeByNodeName(0x0?, {0x0, 0x0})
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_standard.go:591 +0xc7
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).InstanceType(0xc000014000, {0x0?, 0x203ffb9?}, {0x0, 0x0})
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_instances.go:476 +0x10b
sigs.k8s.io/azuredisk-csi-driver/pkg/optimization.NewNodeInfo({0x22ebc28, 0xc000192000}, {0x22f4eb8, 0xc000014000}, {0x0, 0x0})
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/optimization/skus.go:130 +0xc5
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*DriverV2).Run(0xc000140640, {0xc0007a29c0, 0x14}, {0x22c7ae0, 0x0}, 0x0, 0xf7?)
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk_v2.go:270 +0x1a59
main.handle()
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:124 +0xd0
main.main()
	/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:107 +0x1d5

**Environment**:

- CSI Driver version: azuredisk-csi:v2.0.0-beta.10
- Kubernetes version (use `kubectl version`): v1.24.8+rke2r1
- OS (e.g. from /etc/os-release): Ubutnu VMs
- Kernel (e.g. `uname -a`): 
- Install tools: Flux CD / Helm
- Others:

**Comment by edreed** [comment]
@joelcomp1 This is #1697 which is fixed in #1698 . This simple workaround is to disable the performance optimization feature using the option `--set linux.enablePerfOptimization=false`. This setting was inadvertently passed to the CSI controller which causes it to go down an unexpected path. The setting should really only be applied to the CSI node driver and #1698 fixes this.

**Comment by joelcomp1** [comment]
Wow @edreed thank you, you are a life saver! I was lost as to what was going on, that did the trick!
