### ISSUE TITLE
Permission denied - Pods/deployment/statefulset with PVC is not working if pod is running as non-root user in Azure Stack Hub

### ISSUE THREAD

**Issue by zohebk8s** [kubernetes-sigs/azuredisk-csi-driver#1801]
**What happened**:
pod/deployment/statefulset with PVC is not working, if the pod is running as non-root users in Azure StackHub. Kindly go through the attachment for more details about the issue/error.
[pod as non-root user - usecase.pdf](https://github.com/kubernetes-sigs/azuredisk-csi-driver/files/11128764/pod.as.non-root.user.-.usecase.pdf)

**What you expected to happen**:

As non-root user/pod is working fine in Azure AKS Public cloud. I am expecting it should work in Azure Stack Hub as well.

**How to reproduce it**:

Kindly refer to the attachment to reproduce. Already in that attachment, I've reproduced the issue.

**Anything else we need to know?**:

**Environment**: Azure Stack Hub(2206/2102) - AKS Version - v1.23.13

- CSI Driver version: image: mcr.microsoft.com/k8s/csi/azuredisk-csi:v1.10.0
 azuredisk:
    Container ID:  docker://7413d010eefabcbb36a62d851d1c580a536b2a330d8966618f28c7a46143ad2f
    Image:         mcr.microsoft.com/k8s/csi/azuredisk-csi:v1.10.0

  node-driver-registrar:
    Container ID:  docker://dedb7e7650990280ed390b737b0725f7ff03f47b695959b3f13963b9d6677433
    Image:         mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.4.0

Containers:
  liveness-probe:
    Container ID:  docker://058a4453e67d193fc032c2e35217cbb1d1e4f3ab046336a6984522c1a8f223a1
    Image:         mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.5.0

- Kubernetes version (use `kubectl version`): Azure AKS 1.23.13
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
since you are using v1.10.0 azure disk version, could you run following command to update `CSIDriver ` first:
```
kubectl delete CSIDriver disk.csi.azure.com
kubectl apply -f https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/v1.20.0/deploy/csi-azuredisk-driver.yaml
```
 - and then config `securityContext` in your pod
```
securityContext:
  fsGroupChangePolicy: "Always"
```

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

**Comment by zohebk8s** [comment]
@andyzhangx Thanks for your response. For CSI Driver installation, Javier Darsie asked me to follow this URL: https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#azure-disk-csi-driver

As I've used the below commands to install the CSI driver in Azure Stack Hub. 

Instead of deleting and reinstalling, can I just upgrade the version? Will it create any downtime? As it's our production setup.

helm repo add azuredisk-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts

helm install azuredisk-csi-driver azuredisk-csi-driver/azuredisk-csi-driver --namespace kube-system --set cloud=AzureStackCloud --set controller.runOnMaster=true --version v1.10.0

**Comment by zohebk8s** [comment]
@andyzhangx As the installation is slightly different for Azure Stack Hub. That’s why I am double checking before doing any changes, as it’s our production and few PVCs are in use as well.

Will you be able to loop Javier Darsie in this thread? As it’s quite specific to Azure Stack Hub.

**Comment by andyzhangx** [comment]
> @andyzhangx As the installation is slightly different for Azure Stack Hub. That’s why I am double checking before doing any changes, as it’s our production and few PVCs are in use as well.
> 
> Will you be able to loop Javier Darsie in this thread? As it’s quite specific to Azure Stack Hub.

@zohebk8s this is duplicated to issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/901#issuecomment-867451903

there are two options:
 - 1. set `fstype: ext4` in azure disk storage class, that's for new pvc creation.
 - 2. follow this guide to enableFSGroupPolicy on existing cluster
 as long as you don't create/delete/attach/detach disk on that cluster between delete CSIDriver object and creation CSIDriver object, there is no impact (that process only costs less than < 0.1s, so it has nearly no impact)
https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/fsgroup#option2-enable-fsgrouppolicy-support-on-a-cluster-with-csi-driver-already-installed

**Comment by zohebk8s** [comment]
@andyzhangx Amazing, thank you. New PVC creation I've tested and it's working fine.

After deleting and creating a new CSIDriver, do we need to restart any specific pods of kube-system? I mean after executing this commands - https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/fsgroup#option2-enable-fsgrouppolicy-support-on-a-cluster-with-csi-driver-already-installed

**Comment by andyzhangx** [comment]
> @andyzhangx Amazing, thank you. New PVC creation I've tested and it's working fine.
> 
> After deleting and creating a new CSIDriver, do we need to restart any specific pods of kube-system? I mean after executing this commands - https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/fsgroup#option2-enable-fsgrouppolicy-support-on-a-cluster-with-csi-driver-already-installed

@zohebk8s that's not necessary, for existing non-root pod issue, just restart the application pod to make it restart, it should take effect immedately.

**Comment by zohebk8s** [comment]
@andyzhangx I've tested one more scenario:

I've created a new storage class with ext4. Without this parameter in a pod(fsGroupChangePolicy: "Always"), I've deployed and I am able to create a file inside that PVC-mounted directory. So it means, only the ext4 storage class change worked for me.

One last question, usually ext4 is the default filesystem, right? In Azure Stack Hub, why do we need to define it explicitly? Just for my knowledge, I am asking.

Currently, below are the parameters of CSIDriver Azure Stack Hub:

spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent

**Comment by andyzhangx** [comment]
@zohebk8s this is explained as following, empty does not mean `ext4`:
ReadWriteOnceWithFSType: Indicates that volumes will be examined to determine if volume ownership and permissions should be modified to match the pod's security policy. Changes will only occur if the fsType is defined and the persistent volume's accessModes contains ReadWriteOnce. .

https://kubernetes-csi.github.io/docs/support-fsgroup.html

**Comment by zohebk8s** [comment]
@andyzhangx The game is all about Drivers. Thanks a lot for your patience and support. This issue is not straightforward as it needs a deep understanding of Drivers etc.

Thank you once again.
