### ISSUE TITLE
Switch or add photoh os or ubuntu based dockerfile

### ISSUE THREAD

**Issue by m1zzx2** [kubernetes-sigs/azuredisk-csi-driver#1807]
**Is your feature request related to a problem?/Why is this needed**

Can we switch or add photoh os or ubuntu based dockerfile?
**Describe the solution you'd like in detail**

The alpine not opensource.
We don't know how it was compiled, whether there are any backdoors or loopholes in it, this may be a risk.
The photoh or ubnutu is opensource  and we can know all the details of it.  This can avoid some risks caused by information opacity if we use the photoh or ubnutu .

**Comment by m1zzx2** [comment]
If this suggestion is accepted, I can deal with it.

**Comment by m1zzx2** [comment]
Yes it is open source and I made a mistake, but I understand there is no way to clearly figure out a way to compile it from source.

The debian also has some CVEs, Can we add an option for ubnutu?  :cry:

**Comment by andyzhangx** [comment]
> Yes it is open source and I made a mistake, but I understand there is no way to clearly figure out a way to compile it from source.
> 
> The debian also has some CVEs, Can we add an option for ubnutu? 😢

@m1zzx2 we don't want to maintain two driver linux driver images, I think you could use RP https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1704 to builld your own linux driver image.

**Comment by m1zzx2** [comment]
yeah, thank you
