### ISSUE TITLE
Helm install still pulling 1.27.0 version number

### ISSUE THREAD

**Issue by manishsat** [kubernetes-sigs/azuredisk-csi-driver#1810]
**What happened**:
Whem running command 
"helm install azuredisk-csi-driver azuredisk-csi-driver/azuredisk-csi-driver --namespace kube-system"
getting error

INSTALLATION FAILED: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.27.0/azuredisk-csi-driver-v1.27.0.tgz : 404 Not Found'

**What you expected to happen**:
It should be pulling 1.27.1 since 1.27.0 is deprecated

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by manishsat** [comment]
Here is the error from the command prompt

❯ helm install azuredisk-csi-driver azuredisk-csi-driver/azuredisk-csi-driver --namespace kube-system --version v1.27.1
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/masatwan/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/masatwan/.kube/config
Error: INSTALLATION FAILED: chart "azuredisk-csi-driver" matching v1.27.1 not found in azuredisk-csi-driver index. (try 'helm repo update'): no chart version found for azuredisk-csi-driver-v1.27.1
❯ helm install azuredisk-csi-driver azuredisk-csi-driver/azuredisk-csi-driver --namespace kube-system
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/masatwan/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/masatwan/.kube/config
Error: INSTALLATION FAILED: failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v1.27.0/azuredisk-csi-driver-v1.27.0.tgz : 404 Not Found

**Comment by andyzhangx** [comment]
have you tried `helm repo update` and then helm install again?

**Comment by andyzhangx** [comment]
let me know `helm repo update` works
