### ISSUE TITLE
A disk remains in unattached state forever and the pod never comes up

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes-sigs/azuredisk-csi-driver#1815]
**What happened:**

In our service running on AKS, the service and its pods use AKS’s native CSI drivers for both block  ([disk.csi.azure.com](http://disk.csi.azure.com/)) and file ([file.csi.azure.com](http://file.csi.azure.com/)) PVCs.
One of the main pods uses block based 5 PVCs and is using 5 managed disks (ZRS or LRS). However, at times, one of the disks (as seen in Azure portal) remains in “unattached” state forever. This causes the pods to not come up successfully. There are other pods in the service too which are using file based PVCs. 

Based on CSI (disk) driver logs, here is the sequence of events, we have observed.
Just taking an example of 2 disks (say D1, D2) out of the 5 disks:

1. The pod is created
2. D1 gets mounted on LUN-x (x is just an integer starting from 0)
3. D2 gets mounted on LUN-y (y is just an integer starting from 0)
4. The pod is terminated
5. D1 gets unmounted from LUN-x
6. D2 gets unmounted from LUN-y
7. The pod comes up again
8. D2 gets mounted on LUN-x (please note D2 is being mounted on the same LUN number where previously D1 was mounted)
9. CSI driver tries to mount D1 on LUN-z (z could be anything) but it shows that the error that it can not find D1.
10. On Azure UI portal, D1 is shown as "unattached".
11. The disk never gets attached.
12. The pod never comes up.

The above sequence of events could happen in various scenarios like node drain or node reboot or even when the pod
Is being created first time.

One way to recover from this is that when the unattached disk (D1 for example) is
reattached to the same node (for example via Azure portal). After this
manual reattachment, things work fine and the pod comes back up online
successfully.

**What you expected to happen:**

The disk should get re-attached after the pod is recreated.

**How to reproduce it:**

If a pod with 5 disk based PVCs is created, terminated and recreated a few times, it should be possible to reproduce the issue.

**Anything else we need to know?:**

The storage classes use following params:

cachingmode=None,enableAsyncAttach=true,kind=Managed

**Environment:**
AKS K8S version: 1.24.10/1.25.6
Latest CSI driver version
Ubuntu OS.

**Comment by andyzhangx** [comment]
hi, can you remove `enableAsyncAttach=true` (set as false) setting? we found this parameter may have race condition issue.

**Comment by andyzhangx** [comment]
@aveshagarwal `enableAsyncAttach` is deprecated now, so I think you should remove this parameter in your sc or pv setting, the CSI driver would already attach/detach disks in batch mode, so it's ok that enableAsyncAttach is false.

**Comment by aveshagarwal** [comment]
we will remove `enableAsyncAttach` and retry, and get back to you if we still see the issue. 
Could you also help with another question? In some places we noticed that even if we provision "disk.csi.azure.com" CSI provisioner (which is for block PVCs) for file PVCs (rather than using file.csi.azure.com), it does not fail, and PVCs get bound successfully. Any idea why because we were expecting it to fail due to incorrect CSI provisioner?

**Comment by andyzhangx** [comment]
> 

@aveshagarwal that depends on the pvc, and storage class setting. Do you have more details?

**Comment by aveshagarwal** [comment]
PVC (FileSystem) is coming up successfully with storage class that is using disk.csi.azure.com provisioner:

```
Name:          test-etcd-cluster-87pt6pctth
Namespace:     test-system
StorageClass:  md-premium
Status:        Bound
Volume:        pvc-aaabbbcc-aaaa-4ab3-aaaa-xxxxxxxxxxxxxx
Labels:        app=etcd
               etcd_cluster=test-etcd-cluster
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/selected-node: aks-standardds3-xxxxxxxx-vmss000002
               volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       test-etcd-cluster-87pt6pctth
Events:
  Type    Reason                 Age   From                                                                                               Message
  ----    ------                 ----  ----                                                                                               -------
  Normal  WaitForFirstConsumer   53m   persistentvolume-controller                                                                        waiting for first consumer to be created before binding
  Normal  ExternalProvisioning   53m   persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
  Normal  Provisioning           53m   disk.csi.azure.com_csi-azuredisk-controller-xxxxxxxx  External provisioner is provisioning volume for claim "test-system/test-etcd-cluster-87pt6pctth"
  Normal  ProvisioningSucceeded  53m   disk.csi.azure.com_csi-azuredisk-controller-xxxxxxxx  Successfully provisioned volume pvc-aaabbbcc-aaaa-4ab3-aaaa-xxxxxxxxxxxxxx
```


Storage Class:

```
Name:                  md-premium
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           disk.csi.azure.com
Parameters:            cachingmode=None,enableAsyncAttach=true,kind=Managed,storageaccounttype=Premium_LRS
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```

**Comment by andyzhangx** [comment]
@aveshagarwal what do you mean file PVC, from the above manifest, it's creating a disk pvc, and since VolumeBindingMode is `WaitForFirstConsumer`, it won't create disk immediately until the pod is scheduled to one node first.

**Comment by aveshagarwal** [comment]
PVC has  `VolumeMode:    Filesystem` whereas the storage class this PVC points to has `disk.csi.azure.com` as provisioner. 
Shouldn't the provisioner for `VolumeMode:    Filesystem` be `file.csi.azure.com`?

**Comment by andyzhangx** [comment]
> PVC has `VolumeMode: Filesystem` whereas the storage class this PVC points to has `disk.csi.azure.com` as provisioner. Shouldn't the provisioner for `VolumeMode: Filesystem` be `file.csi.azure.com`?

@aveshagarwal 
`disk.csi.azure.com` supports both `Filesystem` and `Block` mode, if it's `Filesystem`, the csi driver would format the disk for the end user.

**Comment by aveshagarwal** [comment]
thanks @andyzhangx, so based on your response, any csi provisioner `file.csi.azure.com` or `disk.csi.azure.com` for PVC with VolumeMode as `Filesystem`, right?

We are still working on updating storage classes without `enableAsyncAttach` for our service and will report soon if it helped with the issue or not.

**Comment by andyzhangx** [comment]
> thanks @andyzhangx, so based on your response, any csi provisioner `file.csi.azure.com` or `disk.csi.azure.com` can be used for PVC with VolumeMode as `Filesystem`, right?
> 
> We are still working on updating storage classes without `enableAsyncAttach` for our service and will report soon if it helped with the issue or not.

@aveshagarwal correct

**Comment by aveshagarwal** [comment]
Just to update that we are still testing with changes (by removing enableAsyncAttach). As soon as we have confidence with changes and the issue does not show up, i will update here.
