### ISSUE TITLE
MCR-provided images of sig-storage apps should be multiarch

### ISSUE THREAD

**Issue by scoof** [kubernetes-sigs/azuredisk-csi-driver#1822]
**What happened**: csi-azuredisk-controller images do not support arm64

**What you expected to happen**: I expected to be able to run on arm64 nodes

**How to reproduce it**: Deploy the helm chart on a arm64-enabled cluster

**Anything else we need to know?**: These containers are not multiarch:

- mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v4.0.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v3.3.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-resizer:v1.6.0

The same images, supplied by sig-storage on registry.k8s.io are all multiarch.

**Environment**:
- CSI Driver version: 1.27.1
- Kubernetes version (use `kubectl version`): 1.24.9
- OS (e.g. from /etc/os-release): AKSUbuntu-2204gen2arm64containerd-202304.10.0
- Kernel (e.g. `uname -a`): 5.4.0-1105-azure
- Install tools: Helm
- Others:

**Comment by andyzhangx** [comment]
@scoof we are already working on this, as a workaround, you could use `registry.k8s.io/sig-storage/xxx` images instead.

**Comment by andyzhangx** [comment]
We have already built arm64 image for the following CSI sidecar images, pls try again, thanks.

```
attacher v4.3.0 v4.2.0 v4.1.0 v4.0.0
resizer v1.8.0 v1.7.0 v1.6.0
provisioner v3.5.0  v.3.4.1 v3.4.0 v3.3.1 v3.3.0
```

**Comment by scoof** [comment]
This works. Thanks
