### ISSUE TITLE
Large number of csi-azuredisk-controller with NodePorts status appeared in the cluster, affecting our k8s API availability 

### ISSUE THREAD

**Issue by igorpalant** [kubernetes-sigs/azuredisk-csi-driver#1823]
**What happened**: We have discovered yesterday that thousands of  csi-azuredisk-controller pods appeared in our cluster. The pods stayed in status: NodePorts as it shows in attachment. We are running 3 master nodes and all these pods seemed to be appearing on one of the master nodes. csi-azuredisk-controller Deployment and Replicaset have not been changed. 

![image](https://user-images.githubusercontent.com/29439548/235309911-4f0ebb0b-a52c-44d4-a9c9-8433cd4640ed.png)

**What you expected to happen**: We expected not to see "extra" pods related to csi-azuredisk-controller 

**How to reproduce it**: Not sure what caused it; therefor not sure how to reproduce it

**Anything else we need to know?**:

**Environment**: k8s 1.23

- CSI Driver version:v1.9.0
- Kubernetes version (use `kubectl version`): 1.23
- OS (e.g. from /etc/os-release): "20.04.5 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): 5.15.0-1035-azure
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
is there any other pods showing the status as `NodePorts` on that master node? also v1.9.0 is a very old version, are you able to install newer version?

**Comment by igorpalant** [comment]
Thanks, no other pods are showing such status on that master node. Our next step is to investigate upgrade to the latest version. We are just trying to understand the condition that created all these thousand pods.
