### ISSUE TITLE
The volume created without zone

### ISSUE THREAD

**Issue by celiawa** [kubernetes-sigs/azuredisk-csi-driver#183]
Hi Experts,

I'm using azuredisk csi v0.4.0, csi-provisioner:v1.0.1 and csi-attacher:v1.0.1  . After deployed the azuredisk csi in my k8s cluster. 

[root@celia-control-01 ~]# kubectl get po -n kube-system|grep csi
csi-azuredisk-controller-69df6d5d8-mg6h4   6/6     Running   0          23m
csi-azuredisk-node-hrr94                   3/3     Running   0          87m
csi-azuredisk-node-pwl6w                   3/3     Running   0          87m
csi-azuredisk-node-xzr7p                   3/3     Running   0          87m

I use below storageclass configuration file.
[root@celia-control-01 ~]# cat azuredisk_sc.yml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS  
  kind: managed 
  cachingMode: ReadOnly
reclaimPolicy: Delete
volumeBindingMode: Immediate

[root@celia-control-01 ~]# kubectl get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
pvcsc004   Bound    pvc-0a49158e-cea3-471e-918a-5daef15c1a3c   2Gi        RWO            azure-disk-standard   6m44s

The PV can be created and bound to PVC successfully. 

When start a pod and use the pvc, the volume failed to attach to a node, because the PV is created without zone. The zone is "None" for the PV.

  Warning  FailedAttachVolume  1s (x3 over 3s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-0a49158e-cea3-471e-918a-5daef15c1a3c" : rpc error: code = Unknown desc = Attach volume "/subscriptions/66e8f030-dbe5-4677-bd29-06b963faa0ac/resourceGroups/compaas-01-dev/providers/Microsoft.Compute/disks/pvc-0a49158e-cea3-471e-918a-5daef15c1a3c" to instance "celia-worker-01" failed with compute.VirtualMachinesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Disk /subscriptions/66e8f030-dbe5-4677-bd29-06b963faa0ac/resourceGroups/compaas-01-dev/providers/Microsoft.Compute/disks/pvc-0a49158e-cea3-471e-918a-5daef15c1a3c cannot be attached to the VM because it is not in zone '1'."

Do we support zone set in azuredisk CSI v0.4.0. Even I add below in the sc. The volume created still without zone.  Do we support creating a volume using the zone discovered from the node like in-tree drive 
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - eastus-1

**Environment**:
- CSI Driver version:  v0.4.0

- Kubernetes version (use `kubectl version`):
[root@celia-control-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andyzhangx** [comment]
hi @celiawa we are still working on zone support: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/176, target supported version: `v0.5.0`

**Comment by celiawa** [comment]
@andyzhangx , thanks a lot your quick response. Could you share the schedule of v0.5.0, when it will be delivered.

**Comment by andyzhangx** [comment]
@celiawa  we will publish v0.5.0 when zone support is done. Is zone support a must for you? You may try non-zone  cluster now.

**Comment by celiawa** [comment]
@andyzhangx I'm trying to deploy a non-zone cluster. We used in-tree driver and supported node in multi-zone in our last release. So we want to support multi zone also after we change to out tree driver. If currently out-tree not support zone, we have to use non-zone instead.

**Comment by andyzhangx** [comment]
zone feature is supported by https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v0.5.0
