### ISSUE TITLE
AKS, disk.csi.azure.com, volumesnapshot: Restoring a volume snapshot from another region

### ISSUE THREAD

**Issue by blagar2** [kubernetes-sigs/azuredisk-csi-driver#1891]
**Is your feature request related to a problem?/Why is this needed**
Hello,
It's possible to create a volume snapshot cross-region, using managed copy.
<https://learn.microsoft.com/en-us/azure/virtual-machines/disks-copy-incremental-snapshot-across-regions?tabs=azure-cli#managed-copy>
In my case, I've created a VolumeSnapshotClass, and specify a parameters.location to create a snapshot in another zone.
The snapshot works, and you can retrieve the volumesnapshot in the cluster.
But the snapshot is harder to restore, the driver seems not able to retrieve the remote the volumesnapshot.
Error:
```
 external provisioner "disk.csi.azure.com" or manually created by system administrator
  Normal   Provisioning          45s (x11 over 9m20s)    disk.csi.azure.com_csi-azuredisk-controller-9f649bf59-zcd8q_37485638-86e3-4300-abf3-or claim "logging/storage-loki-0"
  Warning  ProvisioningFailed    45s (x11 over 9m19s)    disk.csi.azure.com_csi-azuredisk-controller-9f649bf59-zcd8q_37485638-86e3-4300-abf3-
"managed-csi": rpc error: code = NotFound desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\r
  "error": {\r
    "code": "NotFound",\r
    "message": "Resource snapshot-3f923497-582a-4697-9f82-a3dc2a52ca4a is not found."\r
  }\r
}
```
**Describe the solution you'd like in detail**
Have the reverse mechanism by declaring a simple PVC, with a spec.dataSource.location to restore the volumesnapshot?

**Comment by andyzhangx** [comment]
you can only create a disk pv in the same region as the snapshot, that's by design.

**Comment by andyzhangx** [comment]
> Hello @andyzhangx , Thank you for your time! That's a bit sade, because with that kind of manifest:
> 
> ```
> apiVersion: snapshot.storage.k8s.io/v1
> kind: VolumeSnapshotClass
> metadata:
>   name: csi-azuredisk-bkp
>   annotations:
>     snapshot.storage.kubernetes.io/is-default-class: "false"
> driver: disk.csi.azure.com
> deletionPolicy: Delete
> parameters:
>   incremental: "true"
>   resourceGroup: rg_backup
>   location: your-remote-location
>   tags: app=my_app, resourceGroup=rg_aks, namespace=my_namespace
> ```
> 
> You can create a volume snapshot in another region. That can be really powerfull ...

@blagar2 you can only restore to a disk pv in the same region as the snapshot, that's the limitation of azure storage now.

**Comment by blagar2** [comment]
Yes, I am aware that currently it is not possible to restore a PVC from a snapshot that is backed up in an external region. However, I strongly believe that in the future, such functionality will be available. Otherwise, there would be failure messages generated when taking a snapshot of a disk in an external region?
I have full confidence that you and your team can push the boundaries and achieve this capability.
