### ISSUE TITLE
Is storage account tls configuration affect the function of csi driver?  

### ISSUE THREAD

**Issue by xiaoping8385** [kubernetes-sigs/azuredisk-csi-driver#1897]
Hi, we use Azure StorageAccount for the StorageClass for dynamic provisioning.we would like to understand If we change the TLS version of the Azure StorageAccount that csi is using from 1.1 to 1.2, will it affect the existing workload [Like pvc, pv, etc. that were created when the tls version of storageAccount was 1.1] that csi is using? We currently installed azuredisk /azurefile 1.19. Thanks

**Comment by andyzhangx** [comment]
@xiaoping8385 it's not applicable and impacted for azure disk since azure disk won't use a storage account, and for azure file, you could check by: https://learn.microsoft.com/en-us/azure/storage/common/transport-layer-security-configure-minimum-version?tabs=portal#detect-the-tls-version-used-by-client-applications

**Comment by xiaoping8385** [comment]
Actually we are using azurediskcsi driver and azurefilecsi driver, we didn't create our own application to call storageaccount directly.

**Comment by xiaoping8385** [comment]
So how about this case? Did azurefilecsi driver use the TLS to talk to storageaccount?

**Comment by andyzhangx** [comment]
> So how about this case? Did azurefilecsi driver use the TLS to talk to storageaccount?

@xiaoping8385 during the azure file mount, azure file csi driver would leverage "mount -t cifs " to mount azure file, so yes, azure file csi driver would eventually use TLS connecting to storage account.

**Comment by xiaoping8385** [comment]
So I can't find any configurable TLS related parameters out there for azurefile csi driver, is there one?

**Comment by andyzhangx** [comment]
close this issue since it's not related to this driver, and also answer provided

**Comment by xiaoping8385** [comment]
Thanks @andyzhangx That helps.
