### ISSUE TITLE
Add otel trace instrumentation on gRPC calls

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-sigs/azuredisk-csi-driver#1910]
**Is your feature request related to a problem?/Why is this needed**
Add some more observability to the csi driver. In particular, add gRPC tracing using opentelemetry.

**Describe the solution you'd like in detail**
We implemented it on our side in https://github.com/DataDog/azuredisk-csi-driver/pull/1. So I can submit a similar PR here.
The feature is working as expected and we are able to get the gRPC traces.

**Describe alternatives you've considered**
None

**Additional context**

Is your feature request related to a problem? Please describe.
Lack of observability on the driver

**Comment by andyzhangx** [comment]
thanks, just go ahead adding the PR, btw, you only want to enable this feature on open source install, right?

**Comment by Fricounet** [comment]
Hello, the target is mainly for open source install and the feature is hidden behind a flag that default to `false` so it is opt-in. I guess if folks on AKS side also want to enable it for managed install, they can set the flag to `true` in the `az aks` commands but that's not my goal here :)

**Comment by andyzhangx** [comment]
> Created a [PR](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1912) with the feature against `master`. Not sure what is the process with `main_v2`, shall I raise the same PR against the branch?

let's focus on master branch first. thanks.
