### ISSUE TITLE
Failed to create PV when CSI Migration feature for azureDisk enabled.

### ISSUE THREAD

**Issue by celiawa** [kubernetes-sigs/azuredisk-csi-driver#192]
**What happened**:
I'm using azuredisk csi 0.4.0 and kubernetes version 1.16.1.
After enable CSIMigration and CSIMigrationAzureDisk according document in https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk

When create a pvc reference the in-tree storageclass, from kube-controller-manager log, the volume is to create with the out-tree provisioner.
I1120 05:41:26.682985       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pvcsc003", UID:"8af5fd4a-40d1-4ac3-9e3d-9af411330f4c", APIVersion:"v1", ResourceVersion:"254018", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator

But from the csi-provisioner log, the volume can't be created for umkonwn provisioner "kubernetes.io/azure-disk"
I1120 05:35:10.824738       1 controller.go:926] provision "default/pvcsc003" class "azure-disk-standard": started
E1120 05:35:10.827574       1 controller.go:956] provision "default/pvcsc003" class "azure-disk-standard": unknown provisioner "kubernetes.io/azure-disk" requested in claim's StorageClass

**What you expected to happen**:
The PV shall be created for the CSI migration feature enabled.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.4.0
- Kubernetes version (use `kubectl version`):  1.16.1
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
hi @celiawa, the migration work for azure disk csi driver is still on going, we are targeting to make it as work in 1.18

**Comment by celiawa** [comment]
okay, thanks for your response, then we'll not enable the migration feature gate.

**Comment by andyzhangx** [comment]
already supported on k8s v1.17.4 with `v0.7.0` version
