### ISSUE TITLE
csi-azuredisk-controller is restarting continuously in Azure AKS (Azure Stack Hub)

### ISSUE THREAD

**Issue by zohebk8s** [kubernetes-sigs/azuredisk-csi-driver#1933]
Hi Team,

All applications are up/running. However, csi-azuredisk-controller pods are continuously restarting.

It's Azure AKS cluster - Azure Stack Hub

Image Details:

<img width="239" alt="image" src="https://github.com/kubernetes-sigs/azuredisk-csi-driver/assets/128701612/6a749d43-e186-4f70-a3f9-d348435ce089">

Mainly the containers csi-attacher, csi-resizer & csi-snapshotter are getting restarted.

csi-resizer logs:

kubectl logs csi-azuredisk-controller-69df6bccb7-tvm92 -c csi-resizer -n kube-system
I0810 14:15:30.615804       1 main.go:93] Version : v1.3.0-0-g4a6c116
I0810 14:15:30.615882       1 feature_gate.go:245] feature gates: &{map[]}
I0810 14:15:30.619123       1 common.go:111] Probing CSI driver for readiness
I0810 14:15:30.620971       1 main.go:141] CSI driver name: "disk.csi.azure.com"
I0810 14:15:30.622851       1 common.go:111] Probing CSI driver for readiness
I0810 14:15:30.627125       1 leaderelection.go:248] attempting to acquire leader lease kube-system/external-resizer-disk-csi-azure-com...
E0810 15:17:55.664083       1 leaderelection.go:330] error retrieving resource lock kube-system/external-resizer-disk-csi-azure-com: etcdserver: request timed out
E0811 01:45:28.971001       1 leaderelection.go:330] error retrieving resource lock kube-system/external-resizer-disk-csi-azure-com: etcdserver: leader changed
E0811 03:40:53.562835       1 leaderelection.go:330] error retrieving resource lock kube-system/external-resizer-disk-csi-azure-com: etcdserver: request timed out

csi-snapshotter logs:

kubectl logs csi-azuredisk-controller-69df6bccb7-tvm92 -c csi-snapshotter -n kube-system
I0808 00:11:16.877032       1 main.go:87] Version: v3.0.3-0-g9df5a3ce
I0808 00:11:16.883481       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0808 00:11:16.888765       1 main.go:136] CSI driver name: "disk.csi.azure.com"
W0808 00:11:16.888800       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I0808 00:11:16.888812       1 common.go:111] Probing CSI driver for readiness
I0808 00:11:16.890590       1 main.go:162] Start NewCSISnapshotSideCarController with snapshotter [disk.csi.azure.com] kubeconfig [] csiTimeout [1m0s] csiAddress [/csi/csi.sock] resyncPeriod [1m0s] snapshotNamePrefix [snapshot] snapshotNameUUIDLength [824634007720]
I0808 00:11:16.894343       1 leaderelection.go:243] attempting to acquire leader lease  kube-system/external-snapshotter-leader-disk-csi-azure-com...
E0808 06:51:30.969178       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0808 07:19:18.424648       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0808 17:41:07.670130       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: leader changed
E0808 21:18:46.206233       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0809 11:19:31.477865       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0809 12:56:09.365830       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: leader changed
E0809 16:05:22.366097       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0809 19:41:48.249938       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0810 00:26:00.778759       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0810 14:09:31.304157       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0810 14:15:11.966935       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: leader changed
E0810 15:17:55.668179       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0810 19:18:55.608674       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0811 01:45:28.978579       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: leader changed
E0811 07:58:33.775323       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0811 11:00:54.351386       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: leader changed
E0811 11:28:36.258384       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out
E0811 15:06:03.052470       1 leaderelection.go:321] error retrieving resource lock kube-system/external-snapshotter-leader-disk-csi-azure-com: etcdserver: request timed out

**Comment by andyzhangx** [comment]
from the error msg, those pods cannot connect to api-server, is the api-server healthy?

**Comment by zohebk8s** [comment]
@andyzhangx Thanks for your response Andy. Master nodes/api server is up/running and even scheduling is working fine.

I’ve a doubt. There was a pod with pvc failing to attach to a node. It was pending and failing from few days. Yesterday I’ve deleted that statefulset/pod, is it something caused the issue?

**Comment by andyzhangx** [comment]
there is `etcdserver: request timed out` error, is etcd pod running well? can you check the etcd pod logs to get why it's time out?

**Comment by zohebk8s** [comment]
No restarts till now, after deleting that pending statefulset. Even in csi-azuredisk-controller logs, no error from Aug 11th.
