### ISSUE TITLE
misleading message for performancePlus disk size

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes-sigs/azuredisk-csi-driver#1949]
**What happened**:

Creating disk with 512Gi size result in error saying that the disk needs to be at least 512GB for performancePlus.

**What you expected to happen**:

1) receive correct error message saying it's at least 513Gi, which is actually documented correctly here: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-enable-performance?tabs=azure-cli#enable-performance-plus

2) driver should resize the volume accordingly if the performancePlus feature is enabled, similar to what Azure File driver does with premium fileshares: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/794f5fa89560cfb4b3a183bccdd73b8f3c4bd8f0/pkg/azurefile/controllerserver.go#L358-L363

**How to reproduce it**:

1. Create SC with `enablePerformancePlus` parameter set to `true`:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-perfplus
parameters:
  skuname: Premium_LRS
  enablePerformancePlus: "true"
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

2. Create PVC with exactly 512Gi

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: "csi-perfplus"
```

3. Observe `ProvisioningFailed` message:  

` Warning  ProvisioningFailed    <invalid> (x5 over <invalid>)  disk.csi.azure.com_wduan0810manual-b5dng-master-1_d7a29bbf-3f49-4207-af33-056e0814f6e2  failed to provision volume with StorageClass "managed-csi-test-28-sssdlrs-enableperformanceplus": rpc error: code = Internal desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "BadRequest",
    "message": "The performancePlus flag can only be set on disks at least 512 GB in size."
  }
}
`

4. Retry with 513Gi PVC

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 513Gi
  storageClassName: "csi-perfplus"
```

6. Check that disk created successfully and performancePlus is set

```
$ az disk show --resource-group rbednar-mycluster-01-4c6xn-rg --name `oc get pv/pvc-5ca12393-504f-40d2-b9ca-1bcd7198ee18 -o custom-columns=:.metadata.name --no-headers` | jq '.creationData.performancePlus'
true
```

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 1.28
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
so it's `513 GiB or larger`, let me fix it, thanks.

**Comment by RomanBednar** [comment]
@andyzhangx I was thinking if it might do the resize automatically, like with premium file shares: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1950
