### ISSUE TITLE
Add mount options e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

add `mountOptions` to existing case:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/23e97d4fc3756eb51274c3024ad076d463f4338a/test/e2e/dynamic_provisioning.go#L50-L57

azure disk mountOptions reference:
https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azuredisk-mountoptions.yaml#L6

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
I can work on this.
/assign
