### ISSUE TITLE
Azure deprecated API removal on 2023-09-30

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-sigs/azuredisk-csi-driver#1985]
**What happened**:
Just noticed that tomorrow, 30 September 2023, a some deprecated azure api will be removed ([source](https://azure.microsoft.com/en-us/updates/api-versions-being-retired-for-azure-api-management/).
I'm not sure what is the scope of the deprecation and [one of the tests](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/test/utils/azure/azure_helpers.go#L32) looks like it is using one of the API that might be removed, it might start failing.

Also, [some of the vendored modules](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go#L28) also use APIs that might be removed. It's less clear what could be the impact here because the code might not be used anywhere in the driver.

**Comment by Fricounet** [comment]
@andyzhangx do you know if this api removal was taken into account?

**Comment by Fricounet** [comment]
Actually, rereading the original post, it appears I misunderstood the scope. `Azure API Management` is the only service impacted which is not used in the driver anywhere. Closing the issue 😅

**Comment by andyzhangx** [comment]
correct, otherwise that's a disaster for Azure services, people are using all kinds of api-versions, if it's not supported, I believe the whole azure service would be down
