### ISSUE TITLE
update base image to stay on a current version

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes-sigs/azuredisk-csi-driver#2026]
Looks like @andyzhangx changed the base image about nine months ago to one which will be EOL soon: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1704

A community member [asked on K8s Slack](https://kubernetes.slack.com/archives/C5HJXTT9Q/p1698263619233129) "hello all - is there a plan to update the base image from utilizing [alpine:3.15.1](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/ee9fba5a761346c5dce6af2d0217e1f28b5abb31/pkg/azurediskplugin/Dockerfile#L15) which goes [end of life](https://www.alpinelinux.org/releases/) November 1st?"

@feiskyer @andyzhangx please take a look - perhaps we could use Azure Linux? - thanks!

**Comment by JamshedAnsari** [comment]
Hi @andyzhangx can you please provide the ETA for the fix ?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx can you please provide the ETA for the fix ?

@JamshedAnsari the upstream change could happen in Dec, while due to code freeze on AKS, the rollout may happen in Feb.
