### ISSUE TITLE
keep helm chart in sync with deploy manifest

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#203]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Now we have deployment manifests: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy and also chart config: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/charts/latest/azuredisk-csi-driver/templates
need to figure out how to maintain one copy of manifest

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
I can work on this.
/assign
