### ISSUE TITLE
Set the maximum number of volumes that can be attached to a node

### ISSUE THREAD

**Issue by celiawa** [kubernetes-sigs/azuredisk-csi-driver#205]
Hi Experts:

For in-tree azure plugin,  can change the limit of the number of volumes attached to a node by setting the value of the KUBE_MAX_PD_VOLS environment variable, and then starting the scheduler. Refer to https://kubernetes.io/docs/concepts/storage/storage-limits/#custom-limits

For out-tree azure csi plugin, do we have such config for this limitation and how. If not which release it will be supported.

**Comment by andyzhangx** [comment]
that's a good question, we don't support this config in CSI driver now.
Currently we get max data disk count by:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/ad935c61c522a90d967ca8d3ba17db94c403ca5b/pkg/azuredisk/nodeserver.go#L315-L317
By default, max data disk count is 16:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/ad935c61c522a90d967ca8d3ba17db94c403ca5b/pkg/azuredisk/nodeserver.go#L43

**Comment by andyzhangx** [comment]
so if csi driver could get max data disk count correctly, do you still need to set this `KUBE_MAX_PD_VOLS` env? @celiawa

**Comment by celiawa** [comment]
From this link (https://kubernetes.io/docs/concepts/storage/storage-limits/#custom-limits) KUBE_MAX_PD_VOLS  is just for AWS EBS or GCP Persistent disks in-tree plugins. If we use out-tree csi the config will useless.

**Comment by andyzhangx** [comment]
csi driver could get correct max data disk count now, is it ok to close this issue? @celiawa
