### ISSUE TITLE
Add more e2e test cases

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#206]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add following e2e cases:  
 - should create multiple PV objects, bind to PVCs and attach all to a single pod
refer to  https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/13424bda9b3137c06e10a9fb0eb75b152b638103/tests/e2e/dynamic_provisioning.go#L138
 - should create a raw block volume and a filesystem volume on demand and bind to the same pod
refer to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/13424bda9b3137c06e10a9fb0eb75b152b638103/tests/e2e/dynamic_provisioning.go#L234

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
I can work on this.
/assign
