### ISSUE TITLE
Nodes fail to mount azure file using SMB

### ISSUE THREAD

**Issue by daanroeterink** [kubernetes-sigs/azuredisk-csi-driver#2082]
**What happened**:
Sometimes windows nodes cannot mount Azure-files volumes anymore, after a reboot of the node everything works again. It tends happen more on higher cpu count nodes. The error we see in the logging of the CSI Azurefile 
`1672 utils.go:81] GRPC error: rpc error: code = Internal desc = volume(mc_AKS_RESOURCE_GROUP_AKS_NAME_westeurope#STORAGEACCOUNTNAME#pvc-PVC_GUID###APPLICATION) mount \\STORAGEACCOUNTNAME.file.core.windows.net\pvc-PVC_GUID on \var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\FILE_GUID\globalmount failed with NewSmbGlobalMapping failed. output: "", err: exit status 0xc0000142
Please refer to http://aka.ms/filemounterror for possible causes and solutions for mount errors.
I1124 08:32:23.506792    1672 utils.go:76] GRPC call: /csi.v1.Node/NodeStageVolume
I1124 08:32:23.506792    1672 utils.go:77] GRPC request: {"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\file.csi.azure.com\\FILE_GUID\\globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["mfsymlinks","actimeo=30"]}},"access_mode":{"mode":5}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-PVC_GUID","csi.storage.k8s.io/pvc/name":"z99270-customer-APPLICATION-pvc","csi.storage.k8s.io/pvc/namespace":"APPLICATION","secretnamespace":"APPLICATION","skuName":"Standard_LRS","storage.kubernetes.io/csiProvisionerIdentity":"PROVISIONER_ID-file.csi.azure.com"},"volume_id":"mc_AKS_RESOURCE_GROUP_AKS_NAME_westeurope#STORAGEACCOUNTNAME#pvc-PVC_GUID###APPLICATION"}
I1124 08:32:23.506951    1672 nodeserver.go:309] cifsMountPath(\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\FILE_GUID\globalmount) fstype() volumeID(mc_AKS_RESOURCE_GROUP_AKS_NAME_westeurope#STORAGEACCOUNTNAME#pvc-PVC_GUID###APPLICATION) context(map[csi.storage.k8s.io/pv/name:pvc-PVC_GUID csi.storage.k8s.io/pvc/name:z99270-customer-APPLICATION-pvc csi.storage.k8s.io/pvc/namespace:APPLICATION secretnamespace:APPLICATION skuName:Standard_LRS storage.kubernetes.io/csiProvisionerIdentity:PROVISIONER_ID-file.csi.azure.com]) mountflags([mfsymlinks actimeo=30]) mountOptions([AZURE\STORAGEACCOUNTNAME]) volumeMountGroup()
I1124 08:32:23.506981    1672 safe_mounter_host_process_windows.go:45] SMBMount: remote path: \\STORAGEACCOUNTNAME.file.core.windows.net\pvc-PVC_GUID local path: \var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\FILE_GUID\globalmount
I1124 08:32:23.506981    1672 safe_mounter_host_process_windows.go:67] begin to mount \\STORAGEACCOUNTNAME.file.core.windows.net\pvc-PVC_GUID on c:\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\FILE_GUID\globalmount
I1124 08:32:23.521746    1672 smb.go:72] begin to run NewSmbGlobalMapping with \\STORAGEACCOUNTNAME.file.core.windows.net\pvc-PVC_GUID, AZURE\STORAGEACCOUNTNAME
E1124 08:32:23.532647    1672 safe_mounter_host_process_windows.go:105] failed NewSmbGlobalMapping NewSmbGlobalMapping failed. output: "", err: exit status 0xc0000142
E1124 08:32:23.532647    1672 utils.go:81] GRPC error: rpc error: code = Internal desc = volume(mc_AKS_RESOURCE_GROUP_AKS_NAME_westeurope#STORAGEACCOUNTNAME#pvc-PVC_GUID###APPLICATION) mount \\STORAGEACCOUNTNAME.file.core.windows.net\pvc-PVC_GUID on \var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\FILE_GUID\globalmount failed with NewSmbGlobalMapping failed. output: "", err: exit status 0xc0000142
Please refer to http://aka.ms/filemounterror for possible causes and solutions for mount errors.`

I replaced some parts of the logging with placeholders
**What you expected to happen**:
The volume mount are correctly mounted to the node

**How to reproduce it**:
We are not sure yet, we see that it happens on somewhat older nodes > 40 hour old with deallocate 

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 
mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.28.4
image: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.28.4.1-windows-hp

- Kubernetes version (use `kubectl version`): v1.27.3
- OS (e.g. from /etc/os-release): Windows-2022
- Kernel (e.g. `uname -a`):  Not applicable
- Install tools: Helm
- Others:

**Comment by andyzhangx** [comment]
are you able to mount azure file on the broken windows node using `NewSmbGlobalMapping ` command?

**Comment by andyzhangx** [comment]
- On Windows node
```
$User = "AZURE\accountname"
$PWord = ConvertTo-SecureString -String "xxx" -AsPlainText -Force
$Credential = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $User, $Pword
New-SmbGlobalMapping -LocalPath x: -RemotePath \\accountname.file.core.windows.net\sharename -Credential $Credential
Get-SmbGlobalMapping
cd x:
dir
```

**Comment by andyzhangx** [comment]
close this issue since this is azure disk csi driver repo, pls file an issue under https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues
