### ISSUE TITLE
 Proposal: Introducing reservedDataDiskSlots for improved disk count management

### ISSUE THREAD

**Issue by aslafy-z** [kubernetes-sigs/azuredisk-csi-driver#2169]
**Is your feature request related to a problem?/Why is this needed**

I'm facing a challenge with the Azure Disk CSI Driver, detailed in [issue #767](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/767). My Kubernetes clusters have VMs with two untracked data disks. This causes a miscount in `maxDataDiskCount`, as these disks aren't considered. The driver currently allows setting `volumeAttachLimit` manually. However, this method doesn't align with the automatic VM SKU-based limit discovery, leading to inaccurate disk capacity calculations.

**Describe the solution you'd like in detail**

I suggest adding a new parameter to the Azure Disk CSI Driver, tentatively named `reservedDataDiskSlots`. It would enable users to set an offset that is subtracted from the auto-discovered maxDataDiskCount. For instance, if a VM SKU supports 8 disks and `reservedDataDiskSlots` is 2, the effective `maxDataDiskCount` becomes 6. This solution keeps the automatic limit discovery advantage and considers pre-attached disks.

**Describe alternatives you've considered**

An alternative is to keep manually setting `volumeAttachLimit`. But this method is less ideal as it demands detailed tracking of VM SKUs in the cluster, ensuring limits fit each node's capabilities. This is complex and error-prone, especially in environments with varying VM SKUs.

**Additional context**

**Comment by andyzhangx** [comment]
@aslafy-z thanks for the suggestion, are you using AKS or open source csi driver?

**Comment by andyzhangx** [comment]
there is `--volume-attach-limit` parameter in the driver, you could set in the daemonset, that would applies to all csi driver pods running on the node, and set  the unified volume attach limit for all nodes, can you use this workaround now? @aslafy-z 

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c0b0e6c580631dae98a8105448ae68015289f1e7/pkg/azuredisk/azuredisk_option.go#L69C37-L69C56

**Comment by andyzhangx** [comment]
we would provide `--reserved-attached-volume-count` parameter in the driver, I think that would make more sense and more useful.

**Comment by aslafy-z** [comment]
> @aslafy-z thanks for the suggestion, are you using AKS or open source csi driver?

I'm currently using the opensource CSI driver.

> there is `--volume-attach-limit` parameter in the driver, you could set in the daemonset, that would applies to all csi driver pods running on the node, and set  the unified volume attach limit for all nodes, can you use this workaround now? @aslafy-z 
> 
> https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c0b0e6c580631dae98a8105448ae68015289f1e7/pkg/azuredisk/azuredisk_option.go#L69C37-L69C56

Certainly, I will employ this temporary measure and adjust the limit to the highest value allowed by the smallest SKU in our cluster.

**Comment by andyzhangx** [comment]
@aslafy-z would be fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2173
