### ISSUE TITLE
add windows build test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

Add windows build test

```
make azuredisk-windows
```

could refer to https://github.com/kubernetes/test-infra/blob/5742c4353ae50eaecf4c1b4418d3b323c76b18b1/config/jobs/kubernetes-sigs/azuredisk-csi-driver/azuredisk-csi-driver-config.yaml#L3-L21

**Describe alternatives you've considered**

**Additional context**

**Comment by levimm** [comment]
pr here: https://github.com/kubernetes/test-infra/pull/15686

**Comment by andyzhangx** [comment]
@levimm could you add same build test on azure file driver? thanks.
