### ISSUE TITLE
add e2e test for volume expansion feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/215 added volume expansion feature, need to add e2e test for this feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by bcho** [comment]
@andyzhangx  I want to help with this issue, can you assign to me, thanks!

**Comment by stcheng** [comment]
@bcho hi, i've already started working on this. /assign stcheng

**Comment by andyzhangx** [comment]
thanks, btw, the volume expansion can only be done when disk is in "unattached" state, that's a limitaion from azure disk, azure disk team are planning to support disk on the fly in the future.

**Comment by ZeroMagic** [comment]
There is an example for reference. https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/175

**Comment by ZeroMagic** [comment]
Closed due to duplicated issue #453.
