### ISSUE TITLE
add static provision e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#219]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-azuredisk-static-provisioninguse-an-existing-azure-disk

**Describe alternatives you've considered**

**Additional context**

**Comment by prksu** [comment]
@andyzhangx can i take this one?

**Comment by ZeroMagic** [comment]
Actually, all of our pre-provisioned scenario e2e tests cover the static provision. Because the mount process of azuredisk is different from blobfuse and azurefile, here we don't need to write a new test to cover.
