### ISSUE TITLE
Outdated info in doc

### ISSUE THREAD

**Issue by alice-zheyan-yu** [kubernetes-sigs/azuredisk-csi-driver#2199]
**What happened**:
The information below about what sku names are supported in this doc file: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md seems outdated.

`
Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS, PremiumV2_LRS
(Note: [PremiumV2_LRS](https://learn.microsoft.com/en-us/azure/virtual-machines/disks-deploy-premium-v2) only supports None caching mode)
`

I tested and verified that UltraSSD_LRS only supports None caching mode, which is also matching the description in this doc: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-enable-ultra-ssd?tabs=azure-portal#ga-scope-and-limitations

I tested and verified that PremiumV2_LRS needn't adding cachingMode: None in the storageclass.

**What you expected to happen**:
Could we update the doc(https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md) to be:
`
Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS, PremiumV2_LRS
(Note: [UltraSSD_LRS](https://learn.microsoft.com/en-us/azure/virtual-machines/disks-enable-ultra-ssd?tabs=azure-portal) only supports None caching mode)
`

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
there is doc saying: 
`Premium SSDv2 doesn't support host caching.`
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-deploy-premium-v2?tabs=azure-cli#limitations

so is host caching really supported on Premium SSDv2 though it's not reporting error?

and it's correct that Ultra disk does not support host caching.

**Comment by andyzhangx** [comment]
nvm, per disk PR PM in 1/25:
```
There is no ETA for enabling caching for Pv2 disks
```

I will modify the Ultra disk related doc first, and will only modify the PremiumV2 doc if the above doc has changed, thanks.
