### ISSUE TITLE
Workload identity is not working

### ISSUE THREAD

**Issue by AdallomRoy** [kubernetes-sigs/azuredisk-csi-driver#2229]
**What happened**: Workload identity is not working

**What you expected to happen**: Workload identity should work

**How to reproduce it**: Try to use workload identity

**Anything else we need to know?**:

Since this commit: https://github.com/wiz-sec/azuredisk-csi-driver/commit/01b0efc4be6b8963eeff0fcd0c5a35f3edeb5545 workload identity is broken, since ParseConfig is not called anymore and therefore this code part:
```
if tenantID := os.Getenv("AZURE_TENANT_ID"); tenantID != "" {
	config.TenantID = tenantID
}
if clientID := os.Getenv("AZURE_CLIENT_ID"); clientID != "" {
	config.AADClientID = clientID
}
if federatedTokenFile := os.Getenv("AZURE_FEDERATED_TOKEN_FILE"); federatedTokenFile != "" {
	config.AADFederatedTokenFile = federatedTokenFile
	config.UseFederatedWorkloadIdentityExtension = true
}
```
does not get called anymore.

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cvvz** [comment]
Hi, @AdallomRoy Thanks for your report. I've filed a PR to fix this issue.
