### ISSUE TITLE
v1.30.0 Does not see Cloud Credential secret. 

### ISSUE THREAD

**Issue by tfontana1** [kubernetes-sigs/azuredisk-csi-driver#2268]
**What happened**:
When installing v1.30 it does not see the azure cloud credential secret. But when downgrading to v1.29.2 it will work and use the secret. 
**What you expected to happen**:
Installing v1.30 would work and see my secret. 
**How to reproduce it**:
Helm install v1.30
**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aslafy-z** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2218 will fix it but still pending. Any news @andyzhangx?

**Comment by andyzhangx** [comment]
> #2218 will fix it but still pending. Any news @andyzhangx?

@aslafy-z I am still working on a few fixes into v1.30.1, this release should be published end of this week, is that ok?

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.30.1
