### ISSUE TITLE
PVC in Azure can't attach disc to pod after reboot

### ISSUE THREAD

**Issue by aliakseiBabuk** [kubernetes-sigs/azuredisk-csi-driver#2349]
During pod initialization, disc attachment is blocked by security policy with the next error
"Error:
Warning  FailedAttachVolume  4s (x4 over 9s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ff855328-0d87-43e6-9f2d-2f43ab8699c5" : rpc error:

code = Internal desc = Attach volume /subscriptions/***/resourceGroups/***/providers/Microsoft.Comp

ute/disks/pvc-ff855328-0d87-43e6-9f2d-2f43ab8699c5 to instance aks-testnodes-41912833-vmss000000 failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, Raw
Error: {"error":{"code":"RequestDisallowedByPolicy","target":"0","message":"Resource '0' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\
":\"Public IPs disallowed from Virtual Machine Scale Sets\",\"id\":\"/subscriptions/***/resourceGroups/**/providers/Microsoft.Authorization/policyAssignments/%%%\"},\"policyDefinition\":{\"name\":\"Public IPs disallowed from Virtual Machine Scale Sets\",\"id\":\"/subscriptions/***/providers/Microsoft.Authorization/policyDefinitions/***\"}}]'."

We have had a security policy for 3 years it hasn't changed

Does something change in CSI driver work? Why does it request public IP?

**Environment**:

- CSI Driver version: azuredisk-csi:v1.28.7
- Kubernetes version 1.27.9:
- OS (e.g. from /etc/os-release): node-image-version=AKSUbuntu-2204gen2containerd-202402.07.0

**Comment by andyzhangx** [comment]
that's a security policy related to VMSS setting, not related to this driver
