### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MostefaKamalLala** [kubernetes-sigs/azuredisk-csi-driver#2361]
**What happened**:
I upgraded my AKS cluster to 1.28.9. I have 3 windows node and the csi driver version is v1.29.6-windows-hp.
I have a total of 3 windows node with respectively 11, 12 and 8 disks attached to a statefulset. 
I upgrade the cluster because the other version had different issues with the csi driver for windows. The scheduling and mounting of the 2 first nodes went well. However the last node with only 8 disks didnt go welll on two repetitions because I recreted the node juste in case something didnt go well with the provisiong of the node. I am wondering if it is not related to one disk in particular. All the disks are mounted the same way, no pvc/pv but disk URI instead. They all have the same specs, only the data is different.  

The symptoms are the constant restart of the pod after starting the mount. The second time I had the chance to have all my disks mounted and services up so I am leaving it as is now but if I have to redeploy, I will face a problem.
![image](https://github.com/kubernetes-sigs/azuredisk-csi-driver/assets/56651912/1f40ad9c-f9a7-4852-a891-a5c6c27f287d)

**What you expected to happen**:
No errors??

**How to reproduce it**:
B8MS Nodes.  P1 Disks. Mouting using disk URI. The containers have .net 4.7.2 base images.

**Anything else we need to know?**:
The log:
[issue-csiazuredisk-win-1.log](https://github.com/user-attachments/files/15908443/issue-csiazuredisk-win-1.log)

**Environment**:

- CSI Driver version:  v1.29.6-windows-hp
- Kubernetes version (use `kubectl version`): 1.28.9
- OS (e.g. from /etc/os-release): 10.0.17763 / AKSWindows-2019-containerd-17763.5696.240423
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@MostefaKamalLala could you drain that broken node, and then reimage the node?

**Comment by andyzhangx** [comment]
and what's the csi driver logs of good node?

**Comment by MostefaKamalLala** [comment]
> @MostefaKamalLala could you drain that broken node, and then reimage the node?

this is what I did and the problem reappeared. could it be related to one of the disks that got drained into the new node?

**Comment by MostefaKamalLala** [comment]
> and what's the csi driver logs of good node?

I will provide you that information in a couple of Hours.

**Comment by MostefaKamalLala** [comment]
@andyzhangx here is the log from one of the two nodes that are running well. The logs are similar.
[csiazuredisk-winb8b0.log](https://github.com/user-attachments/files/15915519/csiazuredisk-winb8b0.log)

**Comment by andyzhangx** [comment]
> @andyzhangx here is the log from one of the two nodes that are running well. The logs are similar. [csiazuredisk-winb8b0.log](https://github.com/user-attachments/files/15915519/csiazuredisk-winb8b0.log)

thanks, I found the bug, the get freespace of a specific path failed, and it should not panic

**Comment by MostefaKamalLala** [comment]
> > @andyzhangx here is the log from one of the two nodes that are running well. The logs are similar. [csiazuredisk-winb8b0.log](https://github.com/user-attachments/files/15915519/csiazuredisk-winb8b0.log)
> 
> thanks, I found the bug, the get freespace of a specific path failed, and it should not panic

Amazing! What's next now? I am stuck with the release cycle of AKS before I get the patch right? If I recreate another node will I have a chance to make it work? (2 nodes on 2 didnt 👎)   

And one more concern, could it happen at any time in the other two nodes?

**Comment by andyzhangx** [comment]
> > > @andyzhangx here is the log from one of the two nodes that are running well. The logs are similar. [csiazuredisk-winb8b0.log](https://github.com/user-attachments/files/15915519/csiazuredisk-winb8b0.log)
> > 
> > 
> > thanks, I found the bug, the get freespace of a specific path failed, and it should not panic
> 
> Amazing! What's next now? I am stuck with the release cycle of AKS before I get the patch right? If I recreate another node will I have a chance to make it work? (2 nodes on 2 didnt 👎)
> 
> And one more concern, could it happen at any time in the other two nodes?

@MostefaKamalLala I will cut a new release early next week, pls email me your aks cluster fqdn, I will upgrade the version as long as the new release is cut, thx
