### ISSUE TITLE
add statefulset e2e test cases

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#238]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

Add following e2e cases which is more similar to real e2e scenarios:
 - run a statefulset which has one pod with disk mount
 - delete the only pod and new pod will be scheduled on the same node
 - wait for pod status as `Running` 
 - if it's not in `Running` state for about 10min, then test fail, otherwise succeed

Config examples:
 - deployment example:
https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/attach-stress-test/deployment/deployment-azuredisk1.yaml

 - statefulset example:
https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/attach-stress-test/statefulset/statefulset-azuredisk1.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
could refer to https://github.com/kubernetes-sigs/cloud-provider-azure/blob/fb507c32b206a110f4c8bbf4316c7417101ce3ef/tests/e2e/autoscaling/autoscaler.go#L156

**Comment by chewong** [comment]
We already have a similar test case - https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/test/e2e/dynamic_provisioning_test.go#L214-L237. It creates a deployment, deletes the pod, waits for the pod to be scheduled again, and validate the disk attached to the pod. Should we add a similar test case to statefulset?

**Comment by andyzhangx** [comment]
> We already have a similar test case - https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/test/e2e/dynamic_provisioning_test.go#L214-L237. It creates a deployment, deletes the pod, waits for the pod to be scheduled again, and validate the disk attached to the pod. Should we add a similar test case to statefulset?

yes, we should, title modified. Thanks.

**Comment by anshulahuja98** [comment]
@andyzhangx  is this still open/required?

**Comment by andyzhangx** [comment]
> @andyzhangx is this still open/required?

yes, there is only a deployment test here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1cf5d698b4ff19f8d7783979dd5b6ba5743dd8fe/test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go#L42

**Comment by andyzhangx** [comment]
> > @andyzhangx is this still open/required?
> 
> yes, there is only a deployment test here:
> 
> https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1cf5d698b4ff19f8d7783979dd5b6ba5743dd8fe/test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go#L42

let me know if you want to participate in this project,  thanks.

**Comment by chewong** [comment]
We actually have a test case in cloud-provider-azure that uses statefulset + autoscaler + azuredisk-csi-driver - 
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/autoscaling/autoscaler.go#L137

**Comment by andyzhangx** [comment]
@anshulahuja98 would you help add this statefulset test as a warm up? thanks.

**Comment by anshulahuja98** [comment]
> @anshulahuja98 would you help add this statefulset test as a warm up? thanks.

@andyzhangx I started some work towards it, would keep you posted about it.

**Comment by andyzhangx** [comment]
cc @Sakuralbj
