### ISSUE TITLE
fix golint error

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#239]
**What happened**:
Current `erify-golint.sh` does not work while it always worked before 12/30/2019, not sure what happened.

```
# hack/verify-golint.sh
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:59:14: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:74:16: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:113:16: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning.go:273:15: undeclared name: azurediskDriver]
ERRO Running error: buildssa: analysis skipped: errors in package: [/root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:59:14: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:74:16: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:113:16: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning.go:273:15: undeclared name: azurediskDriver]
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by bcho** [comment]
Looks like the tool cannot read the `azurediskDriver` symbol from [suite_test.go](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c4c585cc12eff40c3a70ba4070638e45319f0f27/test/e2e/suite_test.go#L48)

**Comment by bcho** [comment]
I will have a look on this @andyzhangx 

/assign @bcho

**Comment by andyzhangx** [comment]
> I will have a look on this @andyzhangx
> 
> /assign @bcho

thanks, point is it always worked in the before, while just today it does not work.

**Comment by bcho** [comment]
Yep, looks like it's because the changes in golang-ci-lint, one quick fix is to rename `dynamic_provisioning.go` to `dynamic_provisioning_test.go` and this will make the lint tool works again. I will figure out what changes in the tool cause it.

**Comment by bcho** [comment]
I think this lint issue is always here ([previous build log](https://source.cloud.google.com/results/invocations/17403309-8534-438b-aa87-8716207cc4a5/targets/test/log)):

```
W1220 01:52:51.643] level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:59:14: undeclared name: azurediskDriver /go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:74:16: undeclared name: azurediskDriver /go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:113:16: undeclared name: azurediskDriver /go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning.go:273:15: undeclared name: azurediskDriver]"
I1220 01:52:51.776] Congratulations! All Go source files have been linted.
```

But there is [an issue](https://github.com/golangci/golangci-lint/issues/451) in `golangci-lint`, which cause this lint error did not raise properly. And today's release of `golangci-lint` fixed this issue (per https://github.com/golangci/golangci-lint/pull/890). As a result, this lint error raised in our tests.

So I would suggest we rename the `dynamic_provisioning.go` to `dynamic_provisioning_test.go` to pass the linting. @andyzhangx LGTY?
