### ISSUE TITLE
[bug] disk should be attached to /dev/sdc instead of /devhost/sdc

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#24]
Currently disk is attached as `/devhost/sdc` instead of `/dev/sdc`, need to investigate how to make it as `/dev/sdc`, at that time, I did not succeed doing that, looks like there is conflict

 - deployment config
https://github.com/andyzhangx/azuredisk-csi-driver/blob/e51aea26d3417ed3c376a49796e54a34bbd71ee5/deploy/azuredisk-csi-driver.yaml#L66-L67

 - related code need to change
https://github.com/andyzhangx/azuredisk-csi-driver/commit/8ac931d0a39d6f2ebb6a70ff45ac9584a21836cb

```
root@nginx-azuredisk:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          30G  7.1G   22G  25% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.5G     0  3.5G   0% /sys/fs/cgroup
/devhost/sdc    9.8G   37M  9.8G   1% /mnt/azuredisk
/dev/sda1        30G  7.1G   22G  25% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           3.5G   12K  3.5G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           3.5G     0  3.5G   0% /proc/acpi
tmpfs           3.5G     0  3.5G   0% /proc/scsi
tmpfs           3.5G     0  3.5G   0% /sys/firmware
```

**Comment by andyzhangx** [comment]
/assign @ZeroMagic 
Could you take an investigation? Thanks.

**Comment by ZeroMagic** [comment]
Ok. I will.
