### ISSUE TITLE
Migrate test-infra jobs to community infra

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/azuredisk-csi-driver#2410]
**Is your feature request related to a problem?/Why is this needed**
All of the test-infra jobs need to be migrated to community infrastructure by August 1st else they will be deleted.

The [list of tests required to migrate can be found here](https://github.com/dtzar/test-infra/blob/nawaz-azure/hack/cluster-migration/azuredisk-csi-driver-job-migration-todo.md).

Epic-level tracking issue here with additional information: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4976

**Comment by andyzhangx** [comment]
it's done
