### ISSUE TITLE
Attach volume failed. instance not found (doc issue)

### ISSUE THREAD

**Issue by ibalajiarun** [kubernetes-sigs/azuredisk-csi-driver#249]
**What happened**:
I spun up my own kubernetes cluster (with k3s.io) on Azure VMs and installed the azuredisk-csi-driver.

**What you expected to happen**:
I hoped this will be straightforward, but apparently not. After running through the steps in [e2e_usage.md](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md), I get the following error on the nginx pod:

```
AttachVolume.Attach failed for volume "pv-azur
edisk" : rpc error: code = NotFound desc = failed to get azure instance id for node "k3s-vm0" (instance not found)
```

**How to reproduce it**:
1. Get 3 VMs on Azure (I used Standard_D2_v3).
2. Install k3s ([k3.io](https://rancher.com/docs/k3s/latest/en/quick-start/) is better than my instructions)
3. Copy azure.json (see below) to the VMs manually to /etc/kubernetes/azure.json
4. Apply azuredisk-csi-driver manifest files (I used master)
5. Run the e2e_usage.md instructions.

azure.json:
```
{
    "cloud":"AzurePublicCloud",
    "tenantId": "<>,
    "subscriptionId": "<>,
    "aadClientId": "<>",
    "aadClientSecret": "<>",
    "useInstanceMetadata": true
}
```

**Anything else we need to know?**:

I did some debugging and I think it may be because I am not using VM scale sets. If so, is that strict dependency? I cannot use VM scale sets in my setup.

**Environment**:
- CSI Driver version: 
- Kubernetes version (use `kubectl version`): 1.16
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.0.0-1027-azure
- Install tools:
- Others:

Thanks a lot for the help.

**Comment by ibalajiarun** [comment]
Okay, I tried a little bit more with success. Turns out providing the resource group does the trick. Below is the updated azure.json file I used:
```
{
    "cloud":"AzurePublicCloud",
    "tenantId": "<>",
    "subscriptionId": "<>",
    "aadClientId": "<>",
    "aadClientSecret": "<>",
    "resourceGroup": "k3s-rg",
    "location": "eastus",
    "vmType": "standard",
    "useInstanceMetadata": true
}
```

Now, the volume mounts successfully and I am able to tail the date appended to the file. But, the pod reports another warning:

```
Normal   SuccessfulAttachVolume  10m        attachdetach-controller  AttachVolume.Attach succeeded for volume "pv-azuredi
sk"
  Warning  FailedMount             9m8s       kubelet, k3s-vm0         Unable to attach or mount volumes: unmounted volumes
=[azuredisk01], unattached volumes=[default-token-tc29n azuredisk01]: timed out waiting for the condition
```

I have no disk named azuredisk01, so I am wondering what the problem is. I am not sure about the implications.

**Comment by ibalajiarun** [comment]
I was wrong that there is no disk named azuredisk01. azuredisk01 is the volume name of the pvc-azuredisk. But if the kubelet complains it failed to mount, how is it mounted on the pod? Is it just a transient error?

**Comment by andyzhangx** [comment]
@ibalajiarun kubelet also requires `/etc/kubernetes/azure.json` file, see config here: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/19054ed12171b843bb9a13a9f7e9a4c9615d616c/deploy/csi-azuredisk-node.yaml#L84

**Comment by andyzhangx** [comment]
let me know if you have any question.

**Comment by ibalajiarun** [comment]
@andyzhangx It's not clear yet. Every node has the `/etc/kubernetes/azure.json` file and I am applying the `csi-azuredisk-node.yaml` manifest file to the cluster. What else do I need to do?

**Comment by andyzhangx** [comment]
@ibalajiarun that's all, is there any issue now?
follow steps here:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-v0.5.0.md
