### ISSUE TITLE
[feature] add create/delete/list snapshot feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#25]
https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html#snapshot--restore-feature
related AKS feature request: https://github.com/Azure/AKS/issues/658

**Comment by andyzhangx** [comment]
I am adding disk snapshots client on azure cloud provider now which is going to be releases in k8s v1.14.0, then we could add snapshot & restore feature.

**Comment by ekgandhi** [comment]
Thanks @andyzhangx for the suggested workaround:

Use azure disk snapshot feature for backup & restore manually:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/snapshot-copy-managed-disk

**Comment by jeremych1000** [comment]
Now that v1.14.0 is out, is the timeline for this still June as per [Azure/AKS#658](https://github.com/Azure/AKS/issues/658)?

**Comment by tall49er** [comment]
Can I working on it?

**Comment by andyzhangx** [comment]
/assign @tall49er 
pls work on snapshot on azure disk driver first, thanks.

**Comment by andyzhangx** [comment]
BTW, snapshot feature is still alpha in k8s v1.15.0, which means AKS 1.15.x could not use snapshot feature:
https://github.com/kubernetes/kubernetes/blob/5fe910191a6a1a64872e249c4c431b0169d763ed/pkg/features/kube_features.go#L553

**Comment by andyzhangx** [comment]
/assign
I am working on this now: https://github.com/andyzhangx/azuredisk-csi-driver/tree/snapshot
