### ISSUE TITLE
add windows integration & e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#257]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

Currently we only have windows build test, and we need to add windows integration test and e2e test. Windows e2e test requires csi driver on Windows ready, and we could now add windows integration test first, below is linux integration test, need to add a window cmd based integration test:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/8965cdfa05f460397ced8a566bc5678e86a7b255/test/integration/run-test.sh#L45

@chewong as I know, current test in test-infra are all containerized, how can we run windows binary execution test? do you have any idea?

@kkmsft 

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
I think currently test-infra only supports Linux containers, so it wouldn't be possible to run windows binary execution test. We could use other CI system like Travis to test windows-related stuff.

**Comment by andyzhangx** [comment]
@chewong I have added you as admin of this project, could you explore on that, it's ok to use other CI. Thanks.

**Comment by chewong** [comment]
Had some progress with e2e tests on Windows clusters - https://github.com/chewong/azuredisk-csi-driver/tree/windows-e2e

/assign
