### ISSUE TITLE
Missing Disk Encryption Set Read Permission When Using `diskEncryptionSetID` driver param

### ISSUE THREAD

**Issue by bennerv** [kubernetes-sigs/azuredisk-csi-driver#2609]
**What happened**:
When creating a custom storage class with the driver parameter for `diskEncryptionSetID` and attempting to create a volume based on the storage class, it fails to do so with the error message when assigning the azuredisk-csi-driver identity minimal permissions outlined in [driver-parameters](https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/docs/driver-parameters.md)

```
failed to provision volume with StorageClass "des-disk-csi": rpc error: code = Internal desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: \{"error":{"code":"LinkedAuthorizationFailed","message":"The client '<client>' with object id '<object-id>' has permission to perform action 'Microsoft.Compute/disks/write' on scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/disks/pvc-5db9e4bb-812a-4ae5-b9b1-c9b280ba5e76'; however, it does not have permission to perform action(s) 'Microsoft.Compute/diskEncryptionSets/read' on the linked scope(s) '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/diskEncryptionSets/test-des' (respectively) or the linked scope(s) are invalid."}}
```

**What you expected to happen**:
A disk is able to be created and attached to the pod.  

**How to reproduce it**:
1. Create a custom role definition with permissions listed in docs/driver-parameters.md and create a role assignment to the identity used for azuredisk-csi-driver .
2. a disk encryption set backed by a key vault
3. create a custom storage class for azure disk with the `diskEncryptionSetID` driver parameter specifying the disk encryption set resource ID in step 2
4. Create a stateful set or something that consumes a volume, see the error logs from the `azure-disk-csi-driver-controller` pod with failures to create a disk.  

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 
- Kubernetes version (use `kubectl version`): Kubernetes Version: v1.27.16+03a907c
- OS (e.g. from /etc/os-release): `Red Hat Enterprise Linux CoreOS 414.92.202409250559-0 (Plow)"`
- Kernel (e.g. `uname -a`): `Linux testcluster-dcss9-worker-eastus3-ppf8v 5.14.0-284.86.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 23 12:42:39 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2610
