### ISSUE TITLE
Unit Test for ensureMountPoint func

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#268]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

write Unit Test for `ensureMountPoint` func

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/711476a88fdfc0c6c857d9aef1067f01b4da3b26/pkg/azuredisk/nodeserver.go#L394

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
I will add it after pr https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/270 merged.
