### ISSUE TITLE
Waiting for ControllerAttachDetach takes too much time and can fail on 2m kubelet timeout

### ISSUE THREAD

**Issue by kosta709** [kubernetes-sigs/azuredisk-csi-driver#269]
**What happened**:
Pod with PVC stays on ContainerCreating too long time and can fail 
**What you expected to happen**:
Attach/detach should take less than 30s and should be stable 
**How to reproduce it**:
submit pods with volumes azuredisk-csi pvc like this https://github.com/kosta709/azure-csi-azure/tree/master/csi-examples.

**Anything else we need to know?**:
 Provisioner creates disk and PVC is bounded quickly enough, but kubelet spins on VerifyControllerAttachedVolume with exponensial backoff.
Real time from call Azure "attach disk" and time when it is actually attached to the node (available in /dev/disk/azure/scsi1)  in most cases takes 10-15s , but waiting for Azure longRunningOperation can take more than 1min 

I recorded the timing issue here - https://www.youtube.com/watch?v=aklhaC2926Q&feature=youtu.be - - tried `az vmss disk attach` call together with `watch ls /dev/disk/azure/scsi1` and `az vmss list-instances --- `. You can see that actual attach goes quickly enough but we waiting for azure api return takes too long time

Controler waits in [azure_controller_vmss.go](https://github.com/kubernetes/kubernetes/blob/v1.16.4/staging/src/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go)  - line 91 and return in line 102 calls through azure_client.go there it uses WaitForCompletion. 

So due to exponensial backoff NodeStageVolume (mount) is called at least 1min after actual attachment and in case if this wait takes more than 1min kubelet fails on its 2min timeout

**Environment**: Kubernetes on Azure created by latest aks-engine 
- CSI Driver version: 0.5.0
- Kubernetes version (use `kubectl version`): 1.17.1
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-1066-azure
- Install tools: aks-engine
- Others:

**Comment by andyzhangx** [comment]
@kosta709 thanks, we are investigating this issue, will update this thread when there is new finding.

**Comment by kosta709** [comment]
Hello
Any progress?

**Comment by andyzhangx** [comment]
hi @kosta709 azure disk team is working on this work item to reduce the disk attach time, the target is 5s, and target date is around middle of this year, will keep you posted when there is progress on this issue, thanks.

**Comment by kosta709** [comment]
Thanks @andyzhangx 
lets wait 
but now the attach time in azure is 10-15s but because of waiting for long-running + exp. backoff + locks on node level actual kubernetes attach+mount can take few minutes 

I suggest these changes - https://github.com/codefresh-io/azuredisk-csi-driver/blob/attach-delay-fix/CHANGELOG-v0.5.0-attach-delay-fix.md 

see also draft pr on my fork https://github.com/codefresh-io/azuredisk-csi-driver/pull/1
and image codefresh/azuredisk-csi-driver:t2 

It works (currently only vmss) , i get almost stable 15-30s on concurrent attach/detach on same node.  
Mostly these are changes on k8s.io/legacy-cloud-providers/azure 

What do you think?

**Comment by andyzhangx** [comment]
> Thanks @andyzhangx
> lets wait
> but now the attach time in azure is 10-15s but because of waiting for long-running + exp. backoff + locks on node level actual kubernetes attach+mount can take few minutes
> 
> I suggest these changes - https://github.com/codefresh-io/azuredisk-csi-driver/blob/attach-delay-fix/CHANGELOG-v0.5.0-attach-delay-fix.md
> 
> see also draft pr on my fork [codefresh-io#1](https://github.com/codefresh-io/azuredisk-csi-driver/pull/1)
> and image codefresh/azuredisk-csi-driver:t2
> 
> It works (currently only vmss) , i get almost stable 15-30s on concurrent attach/detach on same node.
> Mostly these are changes on k8s.io/legacy-cloud-providers/azure
> 
> What do you think?

@kosta709 thanks for the check. We do the node level lock is because when attach a disk, we update the data disk list, so if we lock lun+node, when there are two disk attachment in the same time, there would be race condition:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/ed7d4842332c6518cac287c036a09237c956f005/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go#L62-L68

**Comment by andyzhangx** [comment]
@kosta709 BTW, we already use `wait.Poll` to poll the `findDiskByLun` result every second, current problem is mainly on slow disk attachment. And also there is some cost on k8s volume controller, when sometimes disk attach costs more than 1min, it may exceed 2min timeout value. Anyway, main problem is on slow disk attachment sometimes.

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/ed7d4842332c6518cac287c036a09237c956f005/pkg/azuredisk/nodeserver.go#L441-L445

**Comment by kosta709** [comment]
regarding nodeserver.go - yes it polls every second, but if /dev/... is not there (findDiskByLun returns "") it returns  fmt.Errorf("azureDisk - findDiskByLun(%v) failed within timeout", lun).  and exits from `wait.Poll` 
It causes to kubelet retry NodePublishVolume with exponensial backoff, and because /dev/disk/azure/... can appear 15-60s after first first call it can reach 2m timeout. 
So I suggest to just `return false, nil` and let wait.Poll to retry instead of kubelet.  
see https://github.com/codefresh-io/azuredisk-csi-driver/blob/03a3b6d4809b0b263fd6774c2d6ef94a99ceaa18/pkg/azuredisk/nodeserver.go#L478

--------------------------
yes, i understand, i'm not removing node-level lock at all
i suggest to hold node-level lock only on time when vmss.Update is executing without WaitForCompletion (it is 1-5s) in most cases 

node+lun lock we need in addition to nodeLock, because we cannot permit any other other attach to take same lun before WaitForCompletion returns
see 	https://github.com/codefresh-io/azuredisk-csi-driver/blob/03a3b6d4809b0b263fd6774c2d6ef94a99ceaa18/pkg/azure/azure_controller_common.go#L166

and also waiting for azure long-ops completion in attach and detach:
https://github.com/codefresh-io/azuredisk-csi-driver/blob/03a3b6d4809b0b263fd6774c2d6ef94a99ceaa18/pkg/azure/azure_controller_vmss.go#L104

https://github.com/codefresh-io/azuredisk-csi-driver/blob/03a3b6d4809b0b263fd6774c2d6ef94a99ceaa18/pkg/azure/azure_controller_vmss.go#L205

so nodeLock is released on Update returns ( without WaitForCompletion )
and nodeLunLock is released on WaitForCompletion returns .
 Also we refresh node cache on both  Update and WaitForCompletion returns

**Comment by andyzhangx** [comment]
> regarding nodeserver.go - yes it polls every second, but if /dev/... is not there (findDiskByLun returns "") it returns fmt.Errorf("azureDisk - findDiskByLun(%v) failed within timeout", lun). and exits from `wait.Poll`
> It causes to kubelet retry NodePublishVolume with exponensial backoff, and because /dev/disk/azure/... can appear 15-60s after first first call it can reach 2m timeout.
> So I suggest to just `return false, nil` and let wait.Poll to retry instead of kubelet.
> see https://github.com/codefresh-io/azuredisk-csi-driver/blob/03a3b6d4809b0b263fd6774c2d6ef94a99ceaa18/pkg/azuredisk/nodeserver.go#L478

@kosta709 thanks, I agree, are you willing to contribute this fix to azure disk csi driver? Let's fix the nodeserver first. About the second Controller fix, I need some time to check it carefully.

**Comment by andyzhangx** [comment]
@kosta709 FYI. to address the long disk attach/detach latency, we have worked out a new feature on azure file csi driver: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/disk, it's vhd disk based on azure file, disk attach/detach only costs < 1s

**Comment by andyzhangx** [comment]
the original issue was fixed by https://github.com/kubernetes/kubernetes/pull/88158, fixed in release 1.15.9, 1.16.8, 1.17.4, 1.18.0 and azure disk CSI driver `v0.7.0`
