### ISSUE TITLE
Support resizing attached azure disk

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#273]
**Is your feature request related to a problem? Please describe.**

Azure disk could not be resized when it's in "attached" state, we could only resize azure disk when it's in "unattached" state.

**Describe the solution you'd like in detail**

available from `v1.11.0`, details: [Add azuredisk PV size grow feature](https://github.com/kubernetes/kubernetes/pull/64386)

example: 
 - [azuredisk storage class with size grow configuration](https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azuredisk-sizegrow.yaml)
 - [How to use azure disk size grow feature](https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-sizegrow.md)

related issues: [Resizing the persistent volume in Azure AKS doesn't reflect the change at pod level.](https://github.com/kubernetes/kubernetes/issues/68427)

**Describe alternatives you've considered**

**Additional context**

/assign

**Comment by Robert-Stam** [comment]
@andyzhangx : Any news on this? Please provide a ballpark estimate if a solid ETA cannot be provided atm. Thanks in advance! Robert

**Comment by andyzhangx** [comment]
> ballpark

@Robert-Stam  azure disk team are still investigating on this since there is a blocking issue, current VM is using VHD, and it does not support dynamic resize.

**Comment by xamox** [comment]
Here is the forum issue for Azure.  I would recommend going there and voting it up:
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/39681535-online-resize-of-the-pv-pvc-for-the-kubernetes

**Comment by xamox** [comment]
Any movement on this?

**Comment by andyzhangx** [comment]
> Any movement on this?

@xamox Azure disk team are working on this, **rough** estimation is end of this year

**Comment by xamox** [comment]
Okay, thanks @andyzhangx

**Comment by ljeromets** [comment]
+1, we are also waiting for it.

**Comment by iMoses** [comment]
+1

**Comment by dhruvilshah3** [comment]
Any update on this?

**Comment by Morriz** [comment]
+1

**Comment by andyzhangx** [comment]
since Azure storage team are still working on resizing attached disk feature, here is the workaround to resize attached disk, it requires remove pod, make disk in `unattached` state first, and then resize disk: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/known-issues/sizegrow.md

**Comment by adamrushuk** [comment]
If anyone has to resize disks in a StatefulSet, my recent notes may also be useful: https://adamrushuk.github.io/increasing-the-volumeclaimtemplates-disk-size-in-a-statefulset-on-aks/

**Comment by dhruvilshah3** [comment]
@andyzhangx @adamrushuk thanks for the workaround - we're already using that in production but there are several related problems we run into given the lack of online resizing. Is there an ETA on when we can expect this issue to be completed?

**Comment by dancronintix** [comment]
Any update on this ?

**Comment by broomfn** [comment]
+1 I can't believe this isn't already implemented.  I commonly resize Linux PVs/LVs all online, it's generally expected in this day and age.

**Comment by lukasmrtvy** [comment]
> on 7 Jun 2020
> @xamox Azure disk team are working on this, **rough** estimation is end of this year

Can You give us updated ETA? Thanks

**Comment by yuzsun** [comment]
@andyzhangx hello andy, may I know if there is any update on this feature? do we have any ETA?

**Comment by gfrankel97** [comment]
Waiting on this feature as well

**Comment by Robert-Stam** [comment]
Good to see it's fixed!
Any estimation when it will be available in AKS?

**Comment by andyzhangx** [comment]
> @andyzhangx Andy, good to see it's fixed/supported now! Any estimation when it will be available in AKS?

@Robert-Stam this feature is just in private preview only available on US East 2 EUAP region, sign up the feature here: https://aka.ms/disksliveresizepreview

I have verified with latest mater branch version resizing attached disk works though it still needs restart pod to get new disk size.

**Comment by andyzhangx** [comment]
this feature is only supported in v1.9.0: https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.9.0
current CSI driver version on aks 1.21 is 1.8.0, will roll out to v1.9.0 version on AKS in Jan.

**Comment by Robert-Stam** [comment]
@andyzhangx Thanks for the update, we are excited to test early next year!

**Comment by tmihalac** [comment]
Is this fix also coming to ARO in Jan ? 
In which version ?

**Comment by andyzhangx** [comment]
> Is this fix also coming to ARO in Jan ? In which version ?

@tmihalac probably not, it requires minimum Azure Disk CSI driver version v1.9.0

**Comment by andyzhangx** [comment]
v1.10.0 is already rolled out on AKS in eastus2euap region now, which already supports AzureDiskLiveReisze feature, I just tried, it works:
 - `kubectl edit pvc pvc-name`, change `spec.resources.requests.storage` in PVC config to a larger size
 - and after a while, pvc resize would succeed, e.g.
<details> <summary> describe pvc </summary>

```
#kubectl describe pvc persistent-storage-statefulset-azuredisk-0
Name:          persistent-storage-statefulset-azuredisk-0
Namespace:     default
StorageClass:  managed-csi
Status:        Bound
Volume:        pvc-a8564491-915f-4613-8efb-d02cce0103aa
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-class: managed-csi
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/selected-node: aks-agentpool-14838774-vmss000002
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       statefulset-azuredisk-0
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 20 Jan 2022 09:13:00 +0000           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                    Age                  From                                 Message
  ----     ------                    ----                 ----                                 -------
  Warning  ExternalExpanding         2m19s                volume_expand                        Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Warning  VolumeResizeFailed        18s (x2 over 79s)    external-resizer disk.csi.azure.com  resize volume "pvc-a8564491-915f-4613-8efb-d02cce0103aa" by resizer "disk.csi.azure.com" failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   Resizing                  16s (x3 over 2m19s)  external-resizer disk.csi.azure.com  External resizer is resizing volume pvc-a8564491-915f-4613-8efb-d02cce0103aa
  Normal   FileSystemResizeRequired  16s                  external-resizer disk.csi.azure.com  Require file system resize of volume on node
```

</details> 

 - delete original pod, the pod would get new size after remount immediately

**Comment by bandesz** [comment]
I've tested this too, but after deleting the pod the new pod gets stuck in containercreating: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1151

**Comment by andyzhangx** [comment]
this feature is still in private preview, and needs to sign up first: https://aka.ms/disksliveresizepreview

**Comment by bandesz** [comment]
@andyzhangx what would signing up improve on my issue? To clarify I wasn't testing online resizing, just resizing an attached disk, which doesn't work for me using v1.10.0, as the recreated pod couldn't reattach the volume.

**Comment by bandesz** [comment]
@andyzhangx I had to check and the used subscriptions are signed up for this preview.

**Comment by andyzhangx** [comment]
> @andyzhangx what would signing up improve on my issue? To clarify I wasn't testing online resizing, just resizing an attached disk, which doesn't work for me using v1.10.0, as the recreated pod couldn't reattach the volume.

@bandesz your subs could only support online resize when it's whitelisted by signing up.

**Comment by andyzhangx** [comment]
sorry, I forgot to mention use this command to register LiveResize preview feature:
```console
az feature show --namespace Microsoft.Compute --name LiveResize
```

**Comment by kuhlman-labs** [comment]
@andyzhangx any information I can share with partners on a potential GA date?

**Comment by andyzhangx** [comment]
online resize is already supported on v1.11.0, more details: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/resize

**Comment by vgazzola** [comment]
Hey, for the regions not currently in the preview mentioned in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks#expand-an-azure-managed-disk it wouldn't work now, right? 
if correct, do you have an ETA for them? Specifically SwitzerlandNorth

**Comment by andyzhangx** [comment]
This feature is already enabled on all Azure public regions, follow guide here to register feature first: https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#resize-a-persistent-volume-without-downtime

**Comment by stoetti** [comment]
@andyzhangx 
Any ETA when this feature will be available without registration?

**Comment by S0LERA** [comment]
Any updates of this on OCP?

**Comment by andyzhangx** [comment]
> Any updates of this on OCP?

@S0LERA it should be supported since the underlying azure vm supports data disk online resize now.
