### ISSUE TITLE
PV did not be created using CSI driver using MSI

### ISSUE THREAD

**Issue by duanwei33** [kubernetes-sigs/azuredisk-csi-driver#274]
**What happened**:
Hi, I'm new for CSI driver, not sure it is an issue or I missed something. Thanks in advance for any help.  
I have k8s cluster on azure and try azure-disk CSI driver on it. After deploying drive successfully (csi-azuredisk-controller and csi-azuredisk-node are running), I created sc and pvc, but volume provided failed with following message: "_failed to provision volume with StorageClass "disk.csi.azure.com": rpc error: code = DeadlineExceeded desc = context deadline exceeded_".
When checking the container azuredisk log, we see message below, seems no response received and no pv created. 
_0205 09:51:21.286809       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0205 09:51:21.286836       1 utils.go:113] GRPC request: name:"pvc-2c475062-0e87-42e8-8c57-8b0102effb46" capacity_range:<required_bytes:1073741824 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"kind" value:"managed" > parameters:<key:"storageaccounttype" value:"Premium_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > >  
I0205 09:45:14.873673       1 azure_managedDiskController.go:83] azureDisk - creating new managed Name:pvc-413713e4-f91f-4616-bbbb-b4e5af7b39e6 StorageAccountType:Standard_LRS Size:2_

**What you expected to happen**:
I hope pvc created successfully and bond to pv.

**How to reproduce it**:
I followed the guide below:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.6.0
- Kubernetes version (use `kubectl version`): v17.1
- OS (e.g. from /etc/os-release): RHEL CoreOS 44.81
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

azuredisk-log
I0206 03:35:06.915435       1 main.go:85] set up prometheus server on [::]:10252
I0206 03:35:06.915698       1 azuredisk.go:98] 
DRIVER INFORMATION:
-------------------
Build Date: "2020-01-20T06:19:27Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v0.6.0
Git Commit: e1c2613898996dbaf8223c866c791a14335598c2
Go Version: go1.13.4
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone

Streaming logs below:
I0206 03:35:06.915724       1 azure.go:31] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/azure.json
I0206 03:35:06.916338       1 azure_auth.go:152] Using AzurePublicCloud environment
I0206 03:35:06.916359       1 azure_auth.go:83] azure: using managed identity extension to retrieve access token
I0206 03:35:06.916367       1 azure_auth.go:94] azure: using System Assigned MSI to retrieve access token
I0206 03:35:06.916403       1 azure.go:409] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
I0206 03:35:06.916464       1 azure_client.go:1541] Azure DisksClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916482       1 azure_client.go:1544] Azure DisksClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916508       1 azure_client.go:1199] Azure RoutesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916517       1 azure_client.go:1202] Azure RoutesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916534       1 azure_client.go:710] Azure SubnetsClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916542       1 azure_client.go:713] Azure SubnetsClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916554       1 azure_client.go:316] Azure InterfacesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916561       1 azure_client.go:319] Azure InterfacesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916573       1 azure_client.go:1309] Azure RouteTablesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916581       1 azure_client.go:1312] Azure RouteTablesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916597       1 azure_client.go:408] Azure LoadBalancersClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916605       1 azure_client.go:411] Azure LoadBalancersClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916629       1 azure_client.go:835] Azure SecurityGroupsClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916637       1 azure_client.go:838] Azure SecurityGroupsClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916652       1 azure_client.go:1413] Azure StorageAccountClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916659       1 azure_client.go:1416] Azure StorageAccountClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916670       1 azure_client.go:188] Azure VirtualMachinesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916677       1 azure_client.go:191] Azure VirtualMachinesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916694       1 azure_client.go:566] Azure PublicIPAddressesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916702       1 azure_client.go:569] Azure PublicIPAddressesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916723       1 azure_client.go:1648] Azure VirtualMachineSizesClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916732       1 azure_client.go:1651] Azure VirtualMachineSizesClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916748       1 azure_client.go:992] Azure VirtualMachineScaleSetsClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916756       1 azure_client.go:995] Azure VirtualMachineScaleSetsClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916774       1 azure_client.go:1096] Azure VirtualMachineScaleSetVMsClient (read ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.916794       1 azure_client.go:1099] Azure VirtualMachineScaleSetVMsClient (write ops) using rate limit config: QPS=6, bucket=10
I0206 03:35:06.920788       1 mount_linux.go:170] Cannot run systemd-run, assuming non-systemd OS
I0206 03:35:06.920803       1 mount_linux.go:171] systemd-run failed with: exit status 1
I0206 03:35:06.920817       1 mount_linux.go:172] systemd-run output: Failed to create bus connection: No such file or directory
I0206 03:35:06.920831       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0206 03:35:06.920838       1 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0206 03:35:06.920848       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0206 03:35:06.920852       1 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0206 03:35:06.920855       1 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0206 03:35:06.920859       1 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0206 03:35:06.920863       1 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0206 03:35:06.920867       1 driver.go:90] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0206 03:35:06.920871       1 driver.go:90] Enabling node service capability: EXPAND_VOLUME
I0206 03:35:06.921158       1 server.go:103] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0206 03:35:07.074957       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:35:07.074982       1 utils.go:113] GRPC request: 
I0206 03:35:07.074991       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:35:07.077603       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.077619       1 utils.go:113] GRPC request: 
I0206 03:35:07.077627       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.077634       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.079103       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0206 03:35:07.079132       1 utils.go:113] GRPC request: 
I0206 03:35:07.079139       1 identityserver.go:59] Using default capabilities
I0206 03:35:07.079147       1 utils.go:119] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > > capabilities:<service:<type:VOLUME_ACCESSIBILITY_CONSTRAINTS > > 
I0206 03:35:07.081170       1 utils.go:112] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0206 03:35:07.081207       1 utils.go:113] GRPC request: 
I0206 03:35:07.081217       1 controllerserver.go:448] Using default ControllerGetCapabilities
I0206 03:35:07.081224       1 utils.go:119] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:LIST_SNAPSHOTS > > capabilities:<rpc:<type:CLONE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > 
I0206 03:35:07.110249       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.110270       1 utils.go:113] GRPC request: 
I0206 03:35:07.110279       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.110287       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.446741       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.446763       1 utils.go:113] GRPC request: 
I0206 03:35:07.446773       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.446780       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.453588       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:35:07.453606       1 utils.go:113] GRPC request: 
I0206 03:35:07.453613       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:35:07.455667       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.455682       1 utils.go:113] GRPC request: 
I0206 03:35:07.455699       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.455705       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.461344       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0206 03:35:07.461359       1 utils.go:113] GRPC request: 
I0206 03:35:07.461366       1 identityserver.go:59] Using default capabilities
I0206 03:35:07.461378       1 utils.go:119] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > > capabilities:<service:<type:VOLUME_ACCESSIBILITY_CONSTRAINTS > > 
I0206 03:35:07.467184       1 utils.go:112] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0206 03:35:07.467212       1 utils.go:113] GRPC request: 
I0206 03:35:07.467219       1 controllerserver.go:448] Using default ControllerGetCapabilities
I0206 03:35:07.467225       1 utils.go:119] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:LIST_SNAPSHOTS > > capabilities:<rpc:<type:CLONE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > 
I0206 03:35:07.749031       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.749128       1 utils.go:113] GRPC request: 
I0206 03:35:07.749153       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.749161       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.750556       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:35:07.750573       1 utils.go:113] GRPC request: 
I0206 03:35:07.750581       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:35:07.751777       1 utils.go:112] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0206 03:35:07.751794       1 utils.go:113] GRPC request: 
I0206 03:35:07.751807       1 controllerserver.go:448] Using default ControllerGetCapabilities
I0206 03:35:07.751814       1 utils.go:119] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:LIST_SNAPSHOTS > > capabilities:<rpc:<type:CLONE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > 
I0206 03:35:07.965769       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:35:07.965795       1 utils.go:113] GRPC request: 
I0206 03:35:07.965804       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:35:07.967696       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginInfo
I0206 03:35:07.967714       1 utils.go:113] GRPC request: 
I0206 03:35:07.967723       1 identityserver.go:33] Using default GetPluginInfo
I0206 03:35:07.967730       1 utils.go:119] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.6.0" 
I0206 03:35:07.969021       1 utils.go:112] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0206 03:35:07.969035       1 utils.go:113] GRPC request: 
I0206 03:35:07.969042       1 identityserver.go:59] Using default capabilities
I0206 03:35:07.969049       1 utils.go:119] GRPC response: capabilities:<service:<type:CONTROLLER_SERVICE > > capabilities:<service:<type:VOLUME_ACCESSIBILITY_CONSTRAINTS > > 
I0206 03:35:07.970991       1 utils.go:112] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0206 03:35:07.971007       1 utils.go:113] GRPC request: 
I0206 03:35:07.971015       1 controllerserver.go:448] Using default ControllerGetCapabilities
I0206 03:35:07.971020       1 utils.go:119] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:PUBLISH_UNPUBLISH_VOLUME > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:LIST_SNAPSHOTS > > capabilities:<rpc:<type:CLONE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > 
I0206 03:35:27.322003       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:35:27.322040       1 utils.go:113] GRPC request: name:"pvc-4b012c84-48c0-4e93-8aef-42253a8a9a2e" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > > 
I0206 03:35:27.324514       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:35:27.324543       1 utils.go:113] GRPC request: name:"pvc-063808ec-6b18-4463-851a-c0b6e30c86ce" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > > 
I0206 03:35:40.147055       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:35:40.147160       1 utils.go:113] GRPC request: 
I0206 03:35:40.147174       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:36:10.146524       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:36:10.146547       1 utils.go:113] GRPC request: 
I0206 03:36:10.146555       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:36:10.933179       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:36:10.933244       1 utils.go:113] GRPC request: name:"pvc-41c234f5-bd53-4ef3-b3fa-6ee2fc33933c" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > > 
I0206 03:36:40.146388       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:36:40.146424       1 utils.go:113] GRPC request: 
I0206 03:36:40.146433       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:37:10.147169       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:37:10.147327       1 utils.go:113] GRPC request: 
I0206 03:37:10.147342       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:37:27.261984       1 controllerserver.go:177] begin to create azure disk(pvc-063808ec-6b18-4463-851a-c0b6e30c86ce) account type(Standard_LRS) rg(qe-wduan-0205-8b6vp-rg) location() size(2) selectedAvailabilityZone(centralus-1)
I0206 03:37:27.263039       1 azure_managedDiskController.go:83] azureDisk - creating new managed Name:pvc-063808ec-6b18-4463-851a-c0b6e30c86ce StorageAccountType:Standard_LRS Size:2
I0206 03:37:27.262812       1 controllerserver.go:177] begin to create azure disk(pvc-4b012c84-48c0-4e93-8aef-42253a8a9a2e) account type(Standard_LRS) rg(qe-wduan-0205-8b6vp-rg) location() size(2) selectedAvailabilityZone(centralus-2)
I0206 03:37:27.263218       1 azure_managedDiskController.go:83] azureDisk - creating new managed Name:pvc-4b012c84-48c0-4e93-8aef-42253a8a9a2e StorageAccountType:Standard_LRS Size:2
I0206 03:37:28.319725       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:37:28.319848       1 utils.go:113] GRPC request: name:"pvc-4b012c84-48c0-4e93-8aef-42253a8a9a2e" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > > 
I0206 03:37:28.320038       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:37:28.320060       1 utils.go:113] GRPC request: name:"pvc-063808ec-6b18-4463-851a-c0b6e30c86ce" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > > 
I0206 03:37:40.146626       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:37:40.146717       1 utils.go:113] GRPC request: 
I0206 03:37:40.146734       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:38:10.146871       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:38:10.147024       1 utils.go:113] GRPC request: 
I0206 03:38:10.147047       1 utils.go:119] GRPC response: ready:<value:true > 
I0206 03:38:10.925957       1 controllerserver.go:177] begin to create azure disk(pvc-41c234f5-bd53-4ef3-b3fa-6ee2fc33933c) account type(Standard_LRS) rg(qe-wduan-0205-8b6vp-rg) location() size(2) selectedAvailabilityZone(centralus-3)
I0206 03:38:10.926119       1 azure_managedDiskController.go:83] azureDisk - creating new managed Name:pvc-41c234f5-bd53-4ef3-b3fa-6ee2fc33933c StorageAccountType:Standard_LRS Size:2
I0206 03:38:11.955541       1 utils.go:112] GRPC call: /csi.v1.Controller/CreateVolume
I0206 03:38:11.955573       1 utils.go:113] GRPC request: name:"pvc-41c234f5-bd53-4ef3-b3fa-6ee2fc33933c" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > parameters:<key:"cachingMode" value:"ReadOnly" > parameters:<key:"kind" value:"managed" > parameters:<key:"skuname" value:"Standard_LRS" > accessibility_requirements:<requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > requisite:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-3" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-1" > > preferred:<segments:<key:"topology.disk.csi.azure.com/zone" value:"centralus-2" > > > 
I0206 03:38:40.148339       1 utils.go:112] GRPC call: /csi.v1.Identity/Probe
I0206 03:38:40.148365       1 utils.go:113] GRPC request: 
I0206 03:38:40.148374       1 utils.go:119] GRPC response: ready:<value:true >

**Comment by andyzhangx** [comment]
this issue is fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/271, could you workaround by: 
```
kubectl edit deployment csi-azuredisk-controller -n kube-system
# add "hostNetwork: true"
kubectl edit daemonset csi-azuredisk-node -n kube-system
# change port num from 9602 to 9603
```

When that fix is merged, it should work well on MSI enabled cluster, thanks.

**Comment by andyzhangx** [comment]
More simpler workaround:
```
kubectl apply -f https://raw.githubusercontent.com/andyzhangx/azuredisk-csi-driver/msi-support/deploy/csi-azuredisk-node.yaml
kubectl apply -f https://raw.githubusercontent.com/andyzhangx/azuredisk-csi-driver/msi-support/deploy/csi-azuredisk-controller.yaml
```

**Comment by duanwei33** [comment]
Thanks a lot, will try and back to you later. @andyzhangx

**Comment by duanwei33** [comment]
It works, we can see the procedure from the log, thanks again.
This issue can be closed.

**Comment by andyzhangx** [comment]
> It works, we can see the procedure from the log, thanks again.
> This issue can be closed.

thanks for confirming, when PR #271 is merged, this issue will be closed automatically.
