### ISSUE TITLE
Cannot create PVC with volumesnapshot

### ISSUE THREAD

**Issue by duanwei33** [kubernetes-sigs/azuredisk-csi-driver#275]
**What happened**:
Step:
1. Install azuredisk-csi-driver successfully (#274)
2. create pvc successfully
3. create volumesnapshot/volumesnapshotcontents successfully.
4. create another pvc with volumesnapshot failed.

From log,  not sure why csi driver cannot get the resource, could you kindly help check if issue from csi driver side?  Thanks in advance.

Resource we have(snapshotcontents/snapshots):
$ kubectl get volumesnapshotcontents.snapshot.storage.k8s.io
NAME                                               AGE
snapcontent-9cfa4c37-8515-4375-8699-5435128827a2   54m
$ kubectl get volumesnapshots.snapshot.storage.k8s.io vs-03
NAME    AGE
vs-03   97m

Error message:
From snapshot container log:
_I0206 09:50:37.732505       1 reflector.go:161] Listing and watching *v1alpha1.VolumeSnapshotContent from github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117
E0206 09:50:37.734013       1 reflector.go:126] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)_
From controller container log:
_I0206 09:08:10.680201       1 controller.go:1199] provision "kube-system/restore-pvc-03" class "disk.csi.azure.com": started
I0206 09:08:10.691920       1 controller.go:398] skip translation of storage class for plugin: disk.csi.azure.com
I0206 09:08:10.692553       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"restore-pvc-03", UID:"dbade117-3a31-4a4c-9c1c-a14d3b2972b0", APIVersion:"v1", ResourceVersion:"672665", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "kube-system/restore-pvc-03"
W0206 09:08:10.697522       1 controller.go:887] Retrying syncing claim "dbade117-3a31-4a4c-9c1c-a14d3b2972b0", failure 0
E0206 09:08:10.697555       1 controller.go:910] error syncing claim "dbade117-3a31-4a4c-9c1c-a14d3b2972b0": failed to provision volume with StorageClass "disk.csi.azure.com": error getting handle for DataSource Type VolumeSnapshot by Name vs-03: error getting snapshot vs-03 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io vs-03)
I0206 09:08:10.697583       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"restore-pvc-03", UID:"dbade117-3a31-4a4c-9c1c-a14d3b2972b0", APIVersion:"v1", ResourceVersion:"672665", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "disk.csi.azure.com": error getting handle for DataSource Type VolumeSnapshot by Name vs-03: error getting snapshot vs-03 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io vs-03)_

**What you expected to happen**:
create  pvc with volumesnapshot successfully.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.6.0
- Kubernetes version (use `kubectl version`): 1.17.1
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: MSI
- Others:

**Comment by andyzhangx** [comment]
there is on going PR(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/260) to move snapshot alpha api to beta, that would fix this issue.

**Comment by duanwei33** [comment]
Yes, I noticed v1.17 using beta, so I used the updated yaml file.
Or you mean need update csi-driver as well for new api version?

**Comment by andyzhangx** [comment]
yes, that's all in PR#260, actually it's working now, I am fixing the snapshot e2e tests in that PR.

**Comment by duanwei33** [comment]
Got it.
I appreciate your kind and quick support.

**Comment by andyzhangx** [comment]
@duanwei33 snapshot of latest version should work, I have migrated to v1beta1 version now. Pls try again by redploying latest master version: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md

**Comment by duanwei33** [comment]
Hi @andyzhangx 

First, I use rbac-csi-snapshot-controller.yaml instead of rbac-csi-azuredisk-controller.yaml in following guide:
skip below yaml configurations if snapshot feature(only available from v1.17.0) will not be used
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/crd-csi-snapshot.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/rbac-csi-azuredisk-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deplo

I still have problem to create pvc with snapshot successfully, snapshot is not in ready status. Also, I find some message from csi-driver, did you meet it from your side? Thanks a lot.
in volumesnapshot status:
_Spec:
  Source:
    Persistent Volume Claim Name:  mypvc02
  Volume Snapshot Class Name:      csi-snapclass
Status:
  Bound Volume Snapshot Content Name:  snapcontent-568d9961-a657-47c1-8a32-d79e773c04b4
  Ready To Use:                        false_


in csi-azuredisk-controller/csi-snapshotter：
_I0210 05:24:57.013162       1 snapshot_controller_base.go:144] enqueued "snapcontent-568d9961-a657-47c1-8a32-d79e773c04b4" for sync
I0210 05:24:57.013185       1 snapshot_controller_base.go:144] enqueued "snapcontent-d0519c1a-da24-435d-b9cd-e06c8ec5bc01" for sync
E0210 05:24:57.014354       1 reflector.go:320] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: unknown (get volumesnapshotcontents.snapshot.storage.k8s.io)
I0210 05:24:57.418516       1 leaderelection.go:283] successfully renewed lease kube-system/external-snapshotter-leader-disk-csi-azure-com
I0210 05:24:57.788469       1 reflector.go:188] Listing and watching *v1beta1.VolumeSnapshotClass from github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117
E0210 05:24:57.790646       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotClass: volumesnapshotclasses.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:csi-azuredisk-controller-sa" cannot list resource "volumesnapshotclasses" in API group "snapshot.storage.k8s.io" at the cluster scope
I0210 05:24:58.014525       1 reflector.go:188] Listing and watching *v1beta1.VolumeSnapshotContent from github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117_

in csi-snapshot-controller/csi-snapshot-controller
_I0210 05:21:36.226489       1 snapshot_controller.go:882] bindandUpdateVolumeSnapshot [kube-system/mysnapshot02]: trying to update snapshot status
I0210 05:21:36.226506       1 snapshot_controller.go:942] updateSnapshotStatus[kube-system/mysnapshot02]
I0210 05:21:36.226514       1 snapshot_controller.go:959] updateSnapshotStatus: updating VolumeSnapshot [&{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:mysnapshot02 GenerateName: Namespace:kube-system SelfLink:/apis/snapshot.storage.k8s.io/v1beta1/namespaces/kube-system/volumesnapshots/mysnapshot02 UID:568d9961-a657-47c1-8a32-d79e773c04b4 ResourceVersion:86996 Generation:1 CreationTimestamp:2020-02-10 04:53:14 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection snapshot.storage.kubernetes.io/volumesnapshot-bound-protection] ClusterName: ManagedFields:[]} Spec:{Source:{PersistentVolumeClaimName:0xc000211360 VolumeSnapshotContentName:<nil>} VolumeSnapshotClassName:0xc000211370} Status:0xc000241c80}] based on VolumeSnapshotContentStatus [<nil>]
I0210 05:21:36.230442       1 util.go:147] storeObjectUpdate updating snapshot "kube-system/mysnapshot02" with version 86996
I0210 05:21:36.230464       1 snapshot_controller.go:903] bindandUpdateVolumeSnapshot for snapshot completed [&v1beta1.VolumeSnapshot{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"mysnapshot02", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/snapshot.storage.k8s.io/v1beta1/namespaces/kube-system/volumesnapshots/mysnapshot02", UID:"568d9961-a657-47c1-8a32-d79e773c04b4", ResourceVersion:"86996", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63716907194, loc:(*time.Location)(0x1ff2780)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string{"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection", "snapshot.storage.kubernetes.io/volumesnapshot-bound-protection"}, ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1beta1.VolumeSnapshotSpec{Source:v1beta1.VolumeSnapshotSource{PersistentVolumeClaimName:(*string)(0xc000211730), VolumeSnapshotContentName:(*string)(nil)}, VolumeSnapshotClassName:(*string)(0xc000211740)}, Status:(*v1beta1.VolumeSnapshotStatus)(0xc0002f21e0)}]
I0210 05:21:36.230525       1 snapshot_controller.go:397] bindandUpdateVolumeSnapshot &{{ } {mysnapshot02  kube-system /apis/snapshot.storage.k8s.io/v1beta1/namespaces/kube-system/volumesnapshots/mysnapshot02 568d9961-a657-47c1-8a32-d79e773c04b4 86996 1 2020-02-10 04:53:14 +0000 UTC <nil> <nil> map[] map[] [] [snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection snapshot.storage.kubernetes.io/volumesnapshot-bound-protection]  []} {{0xc000211730 <nil>} 0xc000211740} 0xc0002f21e0}_

**Comment by duanwei33** [comment]
I found there is one error message when deploying:

$ oc apply -f rbac-csi-azuredisk-controller.yaml
serviceaccount/csi-azuredisk-controller-sa unchanged
clusterrole.rbac.authorization.k8s.io/azuredisk-external-provisioner-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-provisioner-binding unchanged
clusterrole.rbac.authorization.k8s.io/azuredisk-external-attacher-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-attacher-binding unchanged
clusterrole.rbac.authorization.k8s.io/azuredisk-cluster-driver-registrar-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-driver-registrar-binding unchanged
error: error parsing rbac-csi-azuredisk-controller.yaml: error converting YAML to JSON: yaml: line 33: did not find expected key


 32   - apiGroups: ["coordination.k8s.io"]
 33     resources: ["leases"]
 34     verbs: ["get", "list", "watch", "create", "update", "patch"]

**Comment by andyzhangx** [comment]
> I found there is one error message when deploying:
> 
> $ oc apply -f rbac-csi-azuredisk-controller.yaml
> serviceaccount/csi-azuredisk-controller-sa unchanged
> clusterrole.rbac.authorization.k8s.io/azuredisk-external-provisioner-role unchanged
> clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-provisioner-binding unchanged
> clusterrole.rbac.authorization.k8s.io/azuredisk-external-attacher-role unchanged
> clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-attacher-binding unchanged
> clusterrole.rbac.authorization.k8s.io/azuredisk-cluster-driver-registrar-role unchanged
> clusterrolebinding.rbac.authorization.k8s.io/azuredisk-csi-driver-registrar-binding unchanged
> error: error parsing rbac-csi-azuredisk-controller.yaml: error converting YAML to JSON: yaml: line 33: did not find expected key
> 
> 32 - apiGroups: ["coordination.k8s.io"]
> 33 resources: ["leases"]
> 34 verbs: ["get", "list", "watch", "create", "update", "patch"]

pls try again installing the csi driver: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md
it's related to broken format of `rbac-csi-azuredisk-controller.yaml`:
```
Failed to list *v1beta1.VolumeSnapshotClass: volumesnapshotclasses.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:csi-azuredisk-controller-sa" cannot list resource "volumesnapshotclasses" in API group "snapshot.storage.k8s.io" at the cluster scope
```

**Comment by duanwei33** [comment]
HI @andyzhangx 
It works now, thanks a lot for your support.
