### ISSUE TITLE
fix race condition when delete azure disk right after that attach azure disk

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#297]
**What happened**:

port PR: https://github.com/kubernetes/kubernetes/pull/84917

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ialidzhikov** [comment]
@andyzhangx , this one should be fixed with #234, right?

**Comment by andyzhangx** [comment]
correct, already fixed in version `v0.7.0`
