### ISSUE TITLE
v0.6.0 file not found

### ISSUE THREAD

**Issue by ibalajiarun** [kubernetes-sigs/azuredisk-csi-driver#302]
**What happened**:
I ran:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/v0.6.0/crd-csi-driver-registry.yaml
```

I got:
```error: unable to read URL "https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/v0.6.0/crd-csi-driver-registry.yaml", server reported 404 Not Found, status code=404```

**What you expected to happen**:

Successful application

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.6.0
- Kubernetes version (use `kubectl version`): 1.17
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): Linux winter 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by ZeroMagic** [comment]
Since we have changed CSIDriver CRD from alpha to beta, it does not need to create crd-csi-driver-registry.yaml. I will update the document.
