### ISSUE TITLE
add shared disk e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#331]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

[Shared disk feature](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-shared-enable) is still in private preview, should add e2e test  when it's in public preview.

**Describe alternatives you've considered**

**Additional context**

**Comment by palma21** [comment]
FYI:
https://discourse.ubuntu.com/t/ubuntu-high-availability-corosync-pacemaker-shared-disk-environments/14874
