### ISSUE TITLE
SKU - Zone-redundant storage (ZRS)

### ISSUE THREAD

**Issue by rgarcia89** [kubernetes-sigs/azuredisk-csi-driver#332]
**Is your feature request related to a problem? Please describe.**

RIght now it is not possible to set a SKU of type Zone-redundant storage (ZRS). This however, is possible when deploying your Azure Cluster via AKS. In order to survive the outage of a zone it would be nice if this option could be made possible.

**Describe the solution you'd like in detail**

Make it possible to create ZRS pvc with the azuredisk-csi-driver. 
https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy

**Describe alternatives you've considered**

I don't see any alternative for this right now

**Additional context**

**Comment by andyzhangx** [comment]
hi @rgarcia89 azure disk only supports `Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS`, while  you could create a zone supported AKS cluster, and azure disk csi driver is zone aware, follow guide here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology

**Comment by rgarcia89** [comment]
hi @andyzhangx thanks for your fast response. 
I must have been confused by the following [book](https://books.google.de/books?id=DeTWDwAAQBAJ&pg=PA262&lpg=PA262&dq=azure+disk+ZRS+kubernetes.io&source=bl&ots=ACSH3Vfr9u&sig=ACfU3U3K6BngXP747IksMRWWBMqhatGhQQ&hl=de&sa=X&ved=2ahUKEwikkavOzrfoAhVCxaYKHX8eCCYQ6AEwA3oECAgQAQ#v=onepage&q=azure%20disk%20ZRS%20kubernetes.io&f=false)

Our nodes are already zone tagged
```
5-21-275-821-1-232fa6c7   Ready    <none>   6d12h   v1.17.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=5-21-275-821-1-232fa6c7,kubernetes.io/os=linux,topology.disk.csi.azure.com/zone=westeurope-1
5-21-275-822-1-232fa763   Ready    <none>   6d12h   v1.17.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=5-21-275-822-1-232fa763,kubernetes.io/os=linux,topology.disk.csi.azure.com/zone=westeurope-2
5-21-275-823-1-232fa7e5   Ready    <none>   6d12h   v1.17.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=5-21-275-823-1-232fa7e5,kubernetes.io/os=linux,topology.disk.csi.azure.com/zone=westeurope-3
```

So if I understood it correctly there is no possibility to create zone unaware PVCs for a self deployed k8s cluster at azure that resides on the same region but different availability zones?

**Comment by andyzhangx** [comment]
Correct, now you could only create zone aware PVC, and that PVC could only be in that zone, e.g. azure disk in zone#1 could not be moved to zone#2.

**Comment by rgarcia89** [comment]
Thats a pity... So there is no way to use ZRS for such a cluster?

**Comment by andyzhangx** [comment]
I rechecked the azure disk doc, currently only disk snapshot supports ZRS, while azure disk only supports these 4 types: `Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS`

https://azure.microsoft.com/en-us/pricing/details/managed-disks/

**Comment by SatyKrish** [comment]
@andyzhangx Azure Managed Disks now supports ZRS. Does Azure Disk CSI driver support creating zone redundant PVs?
https://docs.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks

**Comment by andyzhangx** [comment]
> @andyzhangx Azure Managed Disks now supports ZRS. Does Azure Disk CSI driver support creating zone redundant PVs? https://docs.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks

yes, follow guide here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology#zrs-disk-support
