### ISSUE TITLE
support read cloud config from secret

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-sigs/azuredisk-csi-driver#333]
Hi * ,

I installing   plain k8s cluster and want to connect the k8s ckuster to azure account , 
there is any way to do it when the cloud config is not plain text.

BR Eliyahu

**Comment by andyzhangx** [comment]
use this template: https://github.com/andyzhangx/demo/blob/master/aks-engine/deployment/etc/kubernetes/azure.json ?

**Comment by eliyahu77** [comment]
I install the

**Comment by eliyahu77** [comment]
Yes part of it , i install also with kubespary that genrate thrnclod config    this file will be on all the nodes after install  there is any way to create this file as part of csi yaml like create it as secret in k8s?

**Comment by andyzhangx** [comment]
that's a good point, where do you want to store all contents in azure.json, by k8s configmap? We will see how to make install easier

**Comment by eliyahu77** [comment]
HI 
https://stackoverflow.com/questions/56060284/create-kubernetes-secret-from-json-file
maybe the follwoing link can hel create the file as secret , and because the csi is inside k8s cluster it will bale to access this secret

**Comment by andyzhangx** [comment]
> HI
> https://stackoverflow.com/questions/56060284/create-kubernetes-secret-from-json-file
> maybe the follwoing link can hel create the file as secret , and because the csi is inside k8s cluster it will bale to access this secret

thanks for the info, we are already working on this, below PR is the first step:
https://github.com/kubernetes/kubernetes/pull/89645#issuecomment-605954148

**Comment by andyzhangx** [comment]
it's non blocking now, https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/347 has already exposed the KubeClient

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#setting-azure-cloud-provider-from-kubernetes-secrets

**Comment by andyzhangx** [comment]
@eliyahu77 pls follow this guide to read cloud config from secret: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/read-from-secret.md
Currently only master branch supports this feature.
