### ISSUE TITLE
Replace cluster driver registrar with CSIDriver CRD

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/azuredisk-csi-driver#335]
**Is your feature request related to a problem?/Why is this needed**
See the cluster driver registrar [repo](https://github.com/kubernetes-csi/cluster-driver-registrar#note), it notes that the sidecar container has been officially deprecated since 1.16, and suggested that turn to use [CSI Driver object](https://kubernetes-csi.github.io/docs/csi-driver-object.html).

**Describe the solution you'd like in detail**
Turn to use [CSI Driver object](https://kubernetes-csi.github.io/docs/csi-driver-object.html).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by andyzhangx** [comment]
thanks for raising this.
I think we are already using CSI driver object: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-azuredisk-driver.yaml

**Comment by Colstuwjx** [comment]
Okay, I think we don't need to run the sidecar container inside controller anymore, the [controller yaml](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-azuredisk-controller.yaml#L75) may needs update.

**Comment by andyzhangx** [comment]
@ZeroMagic could you take a look? I think at least azure file, blobfuse csi driver need replace with CSI Driver object too.
/assign @ZeroMagic

**Comment by ZeroMagic** [comment]
>@ZeroMagic could you take a look? I think at least azure file, blobfuse csi driver need replace with CSI Driver object too.

ok. The storage.k8s.io/CSIDriver has moved to GA in k8s v1.18 recently. We can directly use the GA version.

**Comment by andyzhangx** [comment]
> > @ZeroMagic could you take a look? I think at least azure file, blobfuse csi driver need replace with CSI Driver object too.
> 
> ok. The storage.k8s.io/CSIDriver has moved to GA in k8s v1.18 recently. We can update to GA version.

@ZeroMagic we still need to make sure whether it's supported by 1.14.

**Comment by ZeroMagic** [comment]
The GA version only can be used in k8s v1.18+. Still use the beta version currently. Here we just remove the cluster driver registrar. Is it ok? @andyzhangx

**Comment by andyzhangx** [comment]
> The GA version only can be available in k8s v1.18+. Still use the beta version currently. Here we just remove the cluster driver registrar. Is it ok? @andyzhangx

yep, we could have a try to remove cluster driver registrar, our e2e test could make sure it works or not
