### ISSUE TITLE
leader-election-type has been removed in csi attacher v2.x

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/azuredisk-csi-driver#339]
**Is your feature request related to a problem?/Why is this needed**
I found that our attacher deploy yaml still includes [-leader-election-type](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/csi-azuredisk-controller.yaml#L59), it may works right now, since we're using v1.2.0, but It has been removed since v2.0, see [ref](https://github.com/kubernetes-csi/external-attacher/pull/173).

**Describe the solution you'd like in detail**
While we're prepared to upgrade the attacher version to v2.0, don't forget to remove this line. Otherwise, the csi attacher container would panic.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by andyzhangx** [comment]
thanks for reminder, you are working on kubernetes-csi-tencentcloud, right?

**Comment by Colstuwjx** [comment]
Yes, I'm not from tencentcloud, my corp is using tencentcloud infra, so I forked the repo.
