### ISSUE TITLE
list 404 urls

### ISSUE THREAD

**Issue by CriaHu** [kubernetes-sigs/azuredisk-csi-driver#350]
.github/PULL_REQUEST_TEMPLATE.md
1.[404] https://git.k8s.io/community/contributors/devel/release.md
2.[404] https://git.k8s.io/community/contributors/devel/testing.md
 CONTRIBUTING.md
3.[404] https://git.k8s.io/community/contributors/guide/contributor-cheatsheet.md
 deploy/example/windows/README.md
4.[404] https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/win-script/deploy/install-driver.sh
 docs/install-csi-driver-master.md
5.[404] https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/win-script/deploy/install-driver.sh
 docs/install-csi-driver-v0.6.0.md
6.[404] https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/win-script/deploy/install-driver.sh

**Comment by andyzhangx** [comment]
thanks for reporting this! How did you find it? is there a script, I would like to make it into our CI test, thanks.
