### ISSUE TITLE
fix windows Add-Content command transient error

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#381]
**What happened**:

may add encoding parameter in the `Add-Content` test:
```
	case "echo 'hello world' >> /mnt/test-1/data && while true; do sleep 1; done":
		return "Add-Content C:\\mnt\\test-1\\data.txt 'hello world'; while (1) { sleep 1 }"
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/380/pull-azuredisk-csi-driver-e2e-windows/1254589218768818176/build-log.txt

```
• Failure [330.245 seconds]
Dynamic Provisioning
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:37
  [single-az]
  /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:40
    should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [It]
    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:263

    Unexpected error:
        <*errors.errorString | 0xc000d40640>: {
            s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello world\r\n\"",
        }
        Failed to find "hello world
        hello world
        ", last result: "�������������hello world
        "
    occurred

    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/testsuites.go:467
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
still failing now:
```
• Failure [330.881 seconds]
Dynamic Provisioning
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:37
  [single-az]
  /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:40
    should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [It]
    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:263

    Unexpected error:
        <*errors.errorString | 0xc0007effb0>: {
            s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00h\x00e\x00l\x00l\x00o\x00 \x00w\x00o\x00r\x00l\x00d\x00\r\n\x00\r\n\x00\r\n\"",
        }
        Failed to find "hello world
        hello world
        ", last result: "����������������������������h�e�l�l�o� �w�o�r�l�d�
        �
        �
        "
    occurred

    /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/testsuites.go:467
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/410/pull-azuredisk-csi-driver-e2e-windows/1265435775105765376/build-log.txt

**Comment by andyzhangx** [comment]
PR(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/466) disabled this e2e test(` should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [It]`)

**Comment by andyzhangx** [comment]
so it could be related to this issue: https://stackoverflow.com/questions/56944301/why-does-powershell-redirection-change-the-formatting-of-the-text-content

**Comment by jingxu97** [comment]
I discussed similar issue in in-tree gce pd driver https://github.com/kubernetes/kubernetes/issues/83590
I suspect volume data cache issue, so had a fix in in-tree driver https://github.com/kubernetes/kubernetes/pull/83591
it seems working..

**Comment by andyzhangx** [comment]
> I discussed similar issue in in-tree gce pd driver [kubernetes/kubernetes#83590](https://github.com/kubernetes/kubernetes/issues/83590)
> I suspect volume data cache issue, so had a fix in in-tree driver [kubernetes/kubernetes#83591](https://github.com/kubernetes/kubernetes/pull/83591)
> it seems working..

@jingxu97 thanks a lot, I will fix the in-tree also.

**Comment by andyzhangx** [comment]
in-tree azure disk fix: https://github.com/kubernetes/kubernetes/pull/95456
