### ISSUE TITLE
Azuredisk Static Provisioning fails

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes-sigs/azuredisk-csi-driver#403]
**What happened**:

I have successfully installed the CSI driver on AKS. Then I started to perform the role assigment below but it was not enough:
```sh
az role assignment create --role "Managed Identity Operator" --assignee $aks_client_id --scope /subscriptions/$subId/resourcegroups/$managed_rg
az role assignment create --role "Virtual Machine Contributor" --assignee $aks_client_id --scope /subscriptions/$subId/resourcegroups/$managed_rg
```

So I then I did add the role assignment below
```sh
az role assignment create --role "Contributor" --assignee $aks_client_id --scope /subscriptions/$subId/resourcegroups/$rg_name
```
I did create a disk in my own RG but then hit a role assingment issue at runtime :
az disk create --name $disk_name --sku Premium_LRS --size-gb 5 --zone 1 --location $location -g $rg_name

So I then create the disk in AKS MC RG :
az disk create --name $disk_name --sku Premium_LRS --size-gb 5 --zone 1 --location $location -g **$managed_rg** 

I created the PV & PVC, when deploying finally the test pod I hit this issue:

 Normal   Scheduled               <unknown>            default-scheduler                             Successfully assigned default/nginx-azuredisk to aks-strcsiaksnp-14664217-vmss000000
  Warning  FailedAttachVolume      22m                  attachdetach-controller                       AttachVolume.Attach failed for volume "pv-azuredisk" : rpc error: code = Unknown desc = Attach volume "/subscriptions/xxxx/resourcegroups/MC_rg-strcsi-francecentral_aks-strcsi-101_francecentral/providers/microsoft.compute/disks/aks-dsk" to instance "aks-strcsiaksnp-14664217-vmss000000" failed with Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Code="BadRequest" Message=**"Disk 'aks-dsk' created in availability zone '1'** cannot be attached to VM '/subscriptions/xxxxxx/resourceGroups/MC_rg-strcsi-francecentral_aks-strcsi-101_francecentral/providers/Microsoft.Compute/virtualMachineScaleSets/aks-strcsiaksnp-14664217-vmss/virtualMachines/aks-strcsiaksnp-14664217-vmss_0' **which belongs to an availability set**.  Target: '/subscriptions/xxxxx/resourceGroups/MC_rg-strcsi-francecentral_aks-strcsi-101_francecentral/providers/Microsoft.Compute/disks/aks-dsk'."
  Normal   SuccessfulAttachVolume  22m                  attachdetach-controller                       AttachVolume.Attach succeeded for volume "pv-azuredisk"
  Warning  FailedMount             2m38s (x5 over 20m)  kubelet, aks-strcsiaksnp-14664217-vmss000000  Unable to attach or mount volumes: unmounted volumes=[azuredisk01], unattached volumes=[default-token-wx4g7 azuredisk01]: timed out waiting for the condition
  Warning  FailedMount             2m38s (x9 over 20m)  kubelet, aks-strcsiaksnp-14664217-vmss000000  MountVolume.MountDevice failed for volume "pv-azuredisk" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             22s (x5 over 16m)    kubelet, aks-strcsiaksnp-14664217-vmss000000  Unable to attach or mount volumes: unmounted volumes=[azuredisk01], unattached volumes=[azuredisk01 default-token-wx4g7]: timed out waiting for the condition

I do not understand this error as AKS has been created with VirtualMachineScaleSets.

**What you expected to happen**:

Volume should be mounted and test Pod status should be Running

**How to reproduce it**:

See snippet on my [git repo](https://github.com/ezYakaEagle442/aks-csi/blob/master/setup-store-CSI-driver-azure-disk.md)
```sh

disk_name="aks-dsk"
az disk create --name $disk_name --sku Premium_LRS --size-gb 5 --zone 1 --location $location -g $managed_rg 
az disk list -g $managed_rg
disk_id=$(az disk show --name $disk_name -g $managed_rg --query id)

export SUBSCRIPTION_ID=$subId
export RESOURCE_GROUP=$managed_rg
export TENANT_ID=$tenantId
export DISK_ID=$disk_name

envsubst < ./cnf/pv-static-azuredisk-csi.yaml > deploy/pv-static-azuredisk-csi.yaml
cat deploy/pv-static-azuredisk-csi.yaml

k create -f deploy/pv-static-azuredisk-csi.yaml
k create -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/example/pvc-azuredisk-csi-static.yaml

# create a pod with azuredisk CSI PVC
k create -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/example/nginx-pod-azuredisk.yaml

# enter the pod container to do validation: watch the status of pod until its Status changed from Pending to Running and then enter the pod container
k get po -w

k exec -it nginx-azuredisk -- bash

# run the command below inside the container
df -k # /mnt/azuredisk directory should mounted as disk filesystem
cat  /mnt/azuredisk/outfile
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: Master
- Kubernetes version (use `kubectl version`): AKS 16.7
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
pls use `volumeBindingMode: WaitForFirstConsumer` in zone support, details:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology#use-following-storage-class-with-topology-support

**Comment by ezYakaEagle442** [comment]
The issue does not happen when I create the dis kwithout the zone parameter : 
az disk create --name $disk_name --location $location -g $managed_rg --sku Premium_LRS --size-gb 5

**Comment by andyzhangx** [comment]
I see, your vmss cluster is not zoned, so you should not create a disk with zone
