### ISSUE TITLE
fix test error in github action 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#406]
**What happened**:
original azure action yaml does not work
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1cf5d698b4ff19f8d7783979dd5b6ba5743dd8fe/.github/workflows/go.yml#L1-L33

https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/405/checks?check_run_id=709211370

not sure whether it's related to go 1.13 not available on github action.
```
 Set up Go 1.x12s
go env
Run actions/setup-go@v2
Setup go stable version spec ^1.13
A version satisfying ^1.13 not found locally, attempting to download ...
Downloading from https://storage.googleapis.com/golang/go1.14.3.linux-amd64.tar.gz
Extracting ...
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/a3c232f0-326b-4988-a6d7-219b0cc6c481 -f /home/runner/work/_temp/9f2ad4a4-f429-4de0-b886-db6fe6823a8a
Installed
Added go to the path
go version go1.14.3 linux/amd64

	/opt/hostedtoolcache/go/1.14.3/x64/src/google.golang.org/grpc/status (from $GOROOT)
	/home/runner/go/src/google.golang.org/grpc/status (from $GOPATH)
pkg/azuredisk/azure_common.go:29:2: cannot find package "k8s.io/api/core/v1" in any of:
	/opt/hostedtoolcache/go/1.14.3/x64/src/k8s.io/api/core/v1 (from $GOROOT)
	/home/runner/go/src/k8s.io/api/core/v1 (from $GOPATH)
pkg/azuredisk/controllerserver.go:36:2: cannot find package "k8s.io/apimachinery/pkg/api/resource" in any of:
	/opt/hostedtoolcache/go/1.14.3/x64/src/k8s.io/apimachinery/pkg/api/resource (from $GOROOT)
	/home/runner/go/src/k8s.io/apimachinery/pkg/api/resource (from $GOPATH)
pkg/azuredisk/controllerserver.go:37:2: cannot find package "k8s.io/apimachinery/pkg/types" in any of:
	/opt/hostedtoolcache/go/1.14.3/x64/src/k8s.io/apimachinery/pkg/types
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by anshulahuja98** [comment]
I did some investigation around this
So firstly the method of providing the go version has some issues, the carat (^) is not working as intended

So we should specify it explicitly as '1.13' or '1.12.1'

Also I added a step for doing 
`go get`

During installing dependencies, there is possibly a need to upgrade/update some libraries
```
GOROOT: /opt/hostedtoolcache/go/1.12.1/x64
pkg/azuredisk/azure.go:28:2: cannot find package "k8s.io/klog" in any of:
	/opt/hostedtoolcache/go/1.12.1/x64/src/k8s.io/klog (from $GOROOT)
	/home/runner/go/src/k8s.io/klog (from $GOPATH)
package k8s.io/kubernetes/pkg/util/mount: cannot find package "k8s.io/kubernetes/pkg/util/mount" in any of:
	/opt/hostedtoolcache/go/1.12.1/x64/src/k8s.io/kubernetes/pkg/util/mount (from $GOROOT)
	/home/runner/go/src/k8s.io/kubernetes/pkg/util/mount (from $GOPATH)
##[error]Process completed with exit code 1.
```

Refer this build logs: https://github.com/anshulahuja98/azuredisk-csi-driver/runs/712539763?check_suite_focus=true#step:10:3

This issue is somehow similar to what some other people faced. Adding related issues
https://github.com/kubernetes/client-go/issues/678

You can check the other builds I was trying out here
https://github.com/anshulahuja98/azuredisk-csi-driver/actions

**Comment by andyzhangx** [comment]
thanks for the investigation, in travis CI, go 1.12.1 works:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/fcbd49356397e4515b36d4c15c01e46932e165ab/.travis.yml#L5-L6

Also enable go action is not a must now, we are using travis CI to get code coverage data, that's also ok now.

**Comment by anshulahuja98** [comment]
Can you help me understand where in the travis build are we setting up the dependencies?
It's not there in the YAML explicitly.

**Comment by andyzhangx** [comment]
> Can you help me understand where in the travis build are we setting up the dependencies?
> It's not there in the YAML explicitly.

It should be supported by travis natively, not sure why github action did not work. Here is all we have for the setting: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/.travis.yml

**Comment by anshulahuja98** [comment]
Ohkay!

**Comment by andyzhangx** [comment]
should be fixed
