### ISSUE TITLE
Subscription/RG parameters when taking snapshot

### ISSUE THREAD

**Issue by anshulahuja98** [kubernetes-sigs/azuredisk-csi-driver#417]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently from what I could check, azure disk CSI driver doesn't give an option to take the snapshot in another resource group and/or subscription. Is there a possibility to extend this and provide that capability by adding a parameter in the  VolumeSnapshot spec. And then correspondingly call the required ARM API to provision the Snapshot in a different RG/subscription

`*Edit*`  We might not be able to use an alternate Subscription, but can we at least use a different resource group
**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
Currently we take snapshot in resource group where the original disk is:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/d383bceef29891faf51c38e84c49567bed81732e/pkg/azuredisk/controllerserver.go#L568-L571

I think we can add a new parameter(`resourceGroup`) in snapshot class, if specified, then snapshot would be made on that rg:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/d383bceef29891faf51c38e84c49567bed81732e/pkg/azuredisk/controllerserver.go#L579-L589

Would you work on that? @anshulahuja98  thanks.

Regarding to different subscription requirement, actually the whole azure disk driver does not support different subs, not sure whether there are strong requirement on this scenario, I think we can work on different rg first, thanks.

**Comment by anshulahuja98** [comment]
@andyzhangx  I'll work on this.

**Comment by andyzhangx** [comment]
also I remember that attach disk in subs#1 to VM in subs#2 is not supported, so there is not strong requirement to support cross-subs for snapshot too as I could see.
```
AttachVolume.Attach failed for volume "azure" : Attach volume "andytest" to instance "/subscriptions/b9d2281e-dcd5-4dfd-9a97-xxx/resourceGroups/MC_andy-aks1112_andy-aks1112_westus2/providers/Microsoft.Compute/virtualMachines/aks-nodepool1-20449952-1" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Subscription b9d2281e-dcd5-4dfd-9a97-xxx of the request must match the subscription 4be8920b-2978-43d7-ab14-xxx contained in the managed disk id." Target="dataDisk.managedDisk.id"
```

**Comment by anshulahuja98** [comment]
Makes sense. 
We can take care of this in future when Azure Disk supports it.
