### ISSUE TITLE
[test] skip running test for doc change

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#42]
**Is your feature request related to a problem?/Why is this needed**

Currently all changes including doc change would trigger full test running, while it's not necessary, need to skip test when there is only doc change, e.g. `*.md`

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by lizebang** [comment]
@andyzhangx Can I do it?

**Comment by andyzhangx** [comment]
sure

**Comment by lizebang** [comment]
@andyzhangx I might not be able to finish it now. I have read the documentation for Travis CI and I found that this feature is not supported. Please see [travis-ci/issues/6301](https://github.com/travis-ci/travis-ci/issues/6301) for details. I have already subscribed to it. I will solve this problem after it is solved.

**Comment by andyzhangx** [comment]
that's ok, thanks for the investigation.

**Comment by lizebang** [comment]
@andyzhangx Thanks. And I find [oni/.travis.yml](https://github.com/onivim/oni/blob/master/.travis.yml). This seems like a good temporary solution.
