### ISSUE TITLE
Disk Detach not working properly

### ISSUE THREAD

**Issue by anshulahuja98** [kubernetes-sigs/azuredisk-csi-driver#436]
**What happened**:
Unable to mount more PVs to the cluster
```
{
  "error": {
    "code": "OperationNotAllowed",
    "message": "The maximum number of data disks allowed to be attached to a VM of this size is 4.",
    "target": "dataDisks"
  }
```

Even though it was the only PV that was in the cluster. I had deleted all other PVs and PVCs. Somehow there were perhaps not properly detached. This issue happened to me in another cluster as well. Unable to fix it. Multiple disks are also shown attached when checking from the azure portal when ideally they should have been detached.
**What you expected to happen**:

Disks should have been detached properly since they don't have any PV/PVC or compute associated with them
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy
Used these yamls in the deploy directory:
```
csi-azuredisk-driver.yaml
crd-csi-node-info.yaml
rbac-csi-azuredisk-controller.yaml
rbac-csi-azuredisk-node.yaml
csi-azuredisk-controller.yaml
csi-azuredisk-node.yaml
crd-csi-snapshot.yaml
rbac-csi-snapshot-controller.yaml
csi-snapshot-controller.yaml
```

- Kubernetes version (use `kubectl version`): 1.17.4
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you check how many disks are already attached on that node?

**Comment by anshulahuja98** [comment]
Where can I check that info?
I could overall see that I was not able to delete 5 disks from azure portal as they seemed to be attached to VMs in the cluster. It is a 2 node cluster

From k8s view I only have 1 PV 1 PVC so others should have ideally been detached.

**Comment by anshulahuja98** [comment]
I just checked the VM in the VM scale set and it does show 4 disks attached to it

**Comment by andyzhangx** [comment]
How are the 4 disks attached to your VM? by CSI driver? The Azure disk CSI driver would assume that all data disks should be handled by driver itself.

**Comment by anshulahuja98** [comment]
All disks were CSI provisioned.

**Comment by andyzhangx** [comment]
how could repro this issue? If you delete PVCs which are already mounted, it won't succeed. Could be related this feature not implemented: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/378

**Comment by anshulahuja98** [comment]
It's a bit tricky to reproduce this issue. I just personally faced this 2-3 times.
I deleted the PVC's by removing the finalizers which further delete the PV and ideally the disk.
Being related to #378 I am not sure.

**Comment by andyzhangx** [comment]
so finally the 4 disks are still attached to that node, and no one pod is using those 4 disks, right?

**Comment by anshulahuja98** [comment]
Yes
