### ISSUE TITLE
successful pvc resize does not increase disk size

### ISSUE THREAD

**Issue by Morriz** [kubernetes-sigs/azuredisk-csi-driver#496]
**What happened**:
pvc resize completed successfully after `kubectl edit pvc ...` and then removing pod, but it still shows the same old size it was before in the new pod.

**What you expected to happen**:
resize to reflect the disk size in the pod as described in the pvc resource.

**How to reproduce it**:
start statefulset with pvc claim
update pvc claim size (does nothing, which imo is another bug)
update pvc size directly
remove sts pod
describe pvc: its increased in size

inside the pod the mounted disk is still old size

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: AKS
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Morriz** [comment]
Ah, we didn't notice the disk detaching as it obviously took several minutes(?). We tried finding the correct lun but noticed that it was gone, making us investigate and see it was detached of course.

Thanks for the workaround. Time to start using something like https://github.com/opstree/dynamic-pv-scaler/issues/28

**Comment by andyzhangx** [comment]
> Ah, we didn't notice the disk detaching as it obviously took several minutes(?). We tried finding the correct lun but noticed that it was gone, making us investigate and see it was detached of course.
> 
> Thanks for the workaround. Time to start using something like [opstree/dynamic-pv-scaler#28](https://github.com/opstree/dynamic-pv-scaler/issues/28)

detach disk should take with 1min

**Comment by andyzhangx** [comment]
there are detailed steps about disk resize here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/resize/volume-expansion.md
