### ISSUE TITLE
metrics does not work

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#505]
**What happened**:
follow page under: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/metrics
```
# kubectl get svc csi-azuredisk-controller -n kube-system
NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
csi-azuredisk-controller   ClusterIP   10.0.230.247   <none>        29604/TCP   30s
root@andydev:~/go/src/sigs.k8s.io/azuredisk-csi-driver/deploy/example/metrics# curl http://10.0.230.247:29604/metrics | grep cloudprovider_azure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0^C
root@andydev:~/go/src/sigs.k8s.io/azuredisk-csi-driver/deploy/example/metrics# curl https://10.0.230.247:29604/metrics | grep cloudprovider_azure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0^C
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign @ZeroMagic 
cc @nilo19 

may also add an e2e test to make sure it works in the future.

**Comment by ZeroMagic** [comment]
The feature works. The current doc is not totally correct. Only when meeting the following conditions, the method in the doc can works.
1. The node which executes the `curl` command is in the same subnet with the cluster so that the ClusterIP only can be accessed.
2. The replicas of controller is 1. When it is >1, the service will randomly select one controller to get the metrics. Then if the controller is not the primary one, there will be no related data.

**Comment by ZeroMagic** [comment]
There was a issue #290  to track. 

The suitable method is to use a prometheus server to get the metrics from all controllers and nodes. But it is a little complicate to config the prometheus server.
