### ISSUE TITLE
buildx windows support doenst include os.version

### ISSUE THREAD

**Issue by jchauncey** [kubernetes-sigs/azuredisk-csi-driver#519]
```shell
docker buildx build --no-cache -t $(IMAGE_TAG)-linux-amd64 -f ./pkg/azurediskplugin/Dockerfile --platform="linux/amd64" --push .
docker buildx build --no-cache -t $(IMAGE_TAG)-windows-1809-amd64 -f ./pkg/azurediskplugin/Windows.Dockerfile --platform="windows/amd64" --push .
docker manifest create $(IMAGE_TAG) $(IMAGE_TAG)-linux-amd64 $(IMAGE_TAG)-windows-1809-amd64
docker manifest inspect $(IMAGE_TAG)
```

windows uses a key called os.version in the manifest to know which image to run for a particular manifest. When an image is created with buildx that information is missing and subsequently not added to the manifest when you run the `docker manifest create` command. You have to add this information manually.

Update:
    I see there is the reason why need os.version:

For Windows containers without Hyper-V isolation, the host OS Version and the Container OS Version need to match, which is why we added multiple Windows OS Versions to the building process.

Adds support for Windows OS Versions: 1809, 1903, 1909, 2004.
https://github.com/kubernetes/kubernetes/pull/91452

related issue: https://github.com/docker/cli/issues/2722

**Comment by andyzhangx** [comment]
@jchauncey how can I add `os.version` into `docker buildx build` command, do you have an example? thanks.

**Comment by andyzhangx** [comment]
cc @chewong

**Comment by jchauncey** [comment]
You can see the fix here - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docker/build.sh#L103

**Comment by Sakuralbj** [comment]
I noticed that secrets-store-csi-driver build manifest using these instructions.
```
docker buildx build --no-cache --build-arg LDFLAGS=$(LDFLAGS) -t $(IMAGE_TAG)-linux-amd64 -f docker/Dockerfile --platform="linux/amd64" --push .
docker buildx build --no-cache --build-arg LDFLAGS=$(LDFLAGS) -t $(IMAGE_TAG)-windows-1809-amd64 -f docker/windows.Dockerfile --platform="windows/amd64" --push .
docker manifest create $(IMAGE_TAG) $(IMAGE_TAG)-linux-amd64 $(IMAGE_TAG)-windows-1809-amd64
docker manifest inspect $(IMAGE_TAG)
docker manifest push --purge $(IMAGE_TAG)
```
Is it necessary to integrate [build.sh](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docker/build.sh#L103)  in CI(https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/Makefile#L114)

**Comment by Sakuralbj** [comment]
@jchauncey

**Comment by claudiubelu** [comment]
> 
> 
> I noticed that secrets-store-csi-driver build manifest using these instructions.
> 
> ```
> docker buildx build --no-cache --build-arg LDFLAGS=$(LDFLAGS) -t $(IMAGE_TAG)-linux-amd64 -f docker/Dockerfile --platform="linux/amd64" --push .
> docker buildx build --no-cache --build-arg LDFLAGS=$(LDFLAGS) -t $(IMAGE_TAG)-windows-1809-amd64 -f docker/windows.Dockerfile --platform="windows/amd64" --push .
> docker manifest create $(IMAGE_TAG) $(IMAGE_TAG)-linux-amd64 $(IMAGE_TAG)-windows-1809-amd64
> docker manifest inspect $(IMAGE_TAG)
> docker manifest push --purge $(IMAGE_TAG)
> ```
> 
> Is it necessary to integrate https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docker/build.sh#L103 in CI(https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/Makefile#L114)

I've actually written that ``build.sh`` script. You can see that I've mentioned the ``os.version`` problem in that function's comments, and that I used a workaround in which I was manually setting the ``os.version`` in the manifest image itself.

And no, it isn't necessary to include in your CI since you're only building a manifest list with only 2 images: one for Linux and one for Windows. This is a concern for manifest lists that contain multiple Windows OS versions and are meant to be used by Windows nodes with various OS versions.

**Comment by andyzhangx** [comment]
already fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/585
