### ISSUE TITLE
reenable unit tests on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#525]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Need to enable following unit tests on Windows since NodeXXX funcs would still run on Windows, should fix the test cases:

```
root@andydev:~/go/src/sigs.k8s.io/azuredisk-csi-driver# grep skipIfTestingOnWindows ./* -R
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/nodeserver_test.go:     skipIfTestingOnWindows(t)
./pkg/azuredisk/azuredisk_test.go:      skipIfTestingOnWindows(t)
./pkg/azuredisk/azure_test.go:  skipIfTestingOnWindows(t)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
cc @mayankshah1607

**Comment by mayankshah1607** [comment]
Some tests may fail due to csi-proxy. In that case, we will have to fake mount csi-proxy and run it as a process in Github Actions CI. Similar - https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/426
