### ISSUE TITLE
Mounted volume size issue when cloning a larger size pvc

### ISSUE THREAD

**Issue by duanwei33** [kubernetes-sigs/azuredisk-csi-driver#528]
**What happened**:
When cloned a target PVC with a larger size(16G) than the original PVC(8G), the mounted volume size for the container is accurately 8G.

**What you expected to happen**:
When cloned a target PVC with a larger size(16G) than the original PVC(8G), the mounted volume size for the container should equal to 16G

**How to reproduce it**:
Create original pvc(8G)
clone target pvc(16G)
Create pod and consume target pvc

**Anything else we need to know?**:
Some check on the worker:

$ df -h | grep pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8
/dev/sdd                              7.9G  4.5M  7.9G   1% /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8/globalmount

$ lsblk | grep pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8
sdd                            8:48   0    16G  0 disk /var/lib/kubelet/pods/5a8ef385-efe0-4f0d-91b2-0d9bbcd39bbc/volumes/kubernetes.io~csi/pvc-58344a0e-3a4b-4732-8f67-d41d8affa7c8/mount

**Environment**:
- CSI Driver version: azuredisk-csi:v0.7.0
- Kubernetes version (use `kubectl version`):  latest happen on 1.19, but seen in 1.18 as well
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@VybavaRamadoss do you know whether `DiskSizeGB` will be ommitted when `SourceResourceID` is not empty in disk creation?
```
	diskProperties := compute.DiskProperties{
		DiskSizeGB:   &diskSizeGB,
		CreationData: &compute.CreationData{
			CreateOption:     compute.Copy,
			SourceResourceID: &sourceResourceID,
		},
	}
```

We use this API to clone a disk: https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate#creationdata,

related code:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/dd1d74696c8f9d754399fa0e81b0cfa8249a1d2a/vendor/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go#L111-L118

**Comment by sunpa93** [comment]
I will start working on this issue.

**Comment by LostinCloud** [comment]
I had similar issue with PVC size which is cloned from orginal pvc which has less size.

I have performed a work around mount volume and executed  resize2fs /dev/sdc1 command on filesystem in AKS nodes. It worked for me.
