### ISSUE TITLE
Volumesnapshot readytouse is false when taking snapshot in different resource group

### ISSUE THREAD

**Issue by sandesha-rao-by** [kubernetes-sigs/azuredisk-csi-driver#530]
**What happened**:
When taking incremental volume snapshot for azure managed disk in a different resource group than the disk , snapshot is created but volume snapshot readytouse status is false.

**What you expected to happen**:
When taking incremental volume snapshot for azure managed disk in a different resource group than the disk , snapshot is created with volume snapshot readytouse status set true.

**How to reproduce it**:
Create a POD with PVC/PV attached to managed azure disk in ResourceGroup1
Create volumesnapshot class with parameters incremental: "true" and resourcegroup: ResourceGroup2
Create a volumesnapshot pointing to the above volumesnapshotclass and PVC.
Observe that for the azure disk in ResourceGroup1, incremental snapshot snapshot-xyz is created in ResourceGroup2 , but volumesnapshot set as readytouse false.

**Anything else we need to know?**:
As per the PR , https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/e71d9ae759ec6883fdceb4d9458578a85382eb7c , I assume that taking snaspshot in different resource group than the resource group of the manged disk is supported . Please see the error available while describing  volumesnapshotcontent : 

  Warning  SnapshotContentCheckandUpdateFailed  50s   csi-snapshotter disk.csi.azure.com  Failed to check and update snapshot content: rpc error: code = Internal desc = get snapshot snapshot-xyz from rg(ResourceGroup1) error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/snapshots/snapshot-xyz' under resource group 'ResourceGroup1' was not found.

Please check .Its not clear from the below error description the reason behind csi snapshotter checking for snapshot in the resource group where disk is located . There could be a possibility that I would have overlooked some required configurations .Thanks.

**Environment**:
- CSI Driver version: azuredisk-csi:v0.8.0
- Kubernetes version (use `kubectl version`): v1.17.7
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks for reporting, there is a PR to fix this issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/532

**Comment by andyzhangx** [comment]
I have verified that https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/532 fixed this issue

**Comment by sandesha-rao-by** [comment]
@andyzhangx : The fix from the master works for me . Appreciate the quick fix 👍 Is this fix expected to be rolled out with next release ?

**Comment by andyzhangx** [comment]
> @andyzhangx : The fix from the master works for me . Appreciate the quick fix 👍 Is this fix expected to be rolled out with next release ?

@sandesha-rao-by yes, let me know if that's urgent or not.

**Comment by sandesha-rao-by** [comment]
As this is critical for us , it will be really great , if this fix can be rolled out with next release . Thanks .

**Comment by andyzhangx** [comment]
> As this is critical for us , it will be really great , if this fix can be rolled out with next release . Thanks .

@sandesha-rao-by is it possible to share how you use this snapshot feature? by a tool? how do you restore? Thanks.

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v0.9.0

**Comment by sandesha-rao-by** [comment]
Awesome :tada: Thanks.
