### ISSUE TITLE
Use a standalone user agent

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes-sigs/azuredisk-csi-driver#536]
**Is your feature request related to a problem?/Why is this needed**

Currently, we use the user agent in cloud provider to send an ARM request. Should decouple it and write a new armclient to use in this repository directly.

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
you mean copy the armclient code to this repo? is there any way to reuse the code, only replace the agent info?

**Comment by ZeroMagic** [comment]
It will be more convenient to debug the failure in the kusto. Then it will be clearer to distinguish the requests between CSI Drivers and Cloud Provider, especially in CRP table.

> you mean copy the armclient code to this repo?

Almost.

> is there any way to reuse the code, only replace the agent info?

Need to investigate.

**Comment by andyzhangx** [comment]
could be related to go mod setting:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/17906d16a160c476bfddbe569489964fc7cd2915/go.mod#L32

current value:
```
Go/go1.14.2 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v0.0.0-master+$Format:%h$
```

**Comment by ZeroMagic** [comment]
We can set the user agent when creating the client. 
Ref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/cmd/main.go#L74-L77
