### ISSUE TITLE
Volume Snapshot: azure csi driver conflicting with csi external snapshotter 

### ISSUE THREAD

**Issue by Sathishkunisai** [kubernetes-sigs/azuredisk-csi-driver#540]
Azure CSI snapshotter controller is overlapping with external snapshotter of Ceph (rook), and not successful in creating snapshots of volumes.
 
Azure CSI Driver instructions:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/install-csi-driver-master.md
 
CSI external snapshotter instructions:
 
https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage 

Considering my storage platform is on Ceph(rook), only external snapshotter CSI driver is working. After removing azure CSI driver, I could take snapshots.

 
https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage 
 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:  Azure Kubernetes 
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): 1.17.9
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
if there is really conflict, remove one snapshot controller should be ok, run:
```
kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/csi-snapshot-controller.yaml
```

@Sathishkunisai do you have the install link of external snapshotter of Ceph? Thanks. In long term, need to figure out a way how  do we prevent such conflict, at least doc somewhere, thanks.

**Comment by Sathishkunisai** [comment]
https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage
@andyzhangx  link is above.thanks

**Comment by andyzhangx** [comment]
> https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage
> @andyzhangx link is above.thanks

We use same snapshot controller, so only use one snapshot controller is ok, for this Azure disk CSI driver, snapshot controller is optional.
