### ISSUE TITLE
fix windows test failure

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#544]
**What happened**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/543/pull-azuredisk-csi-driver-e2e-migration-windows/1306577171103354880/build-log.txt

```
STEP: checking pod exec after pod restart again
Sep 17 13:49:01.253: INFO: Running '/usr/local/bin/kubectl --server=https://kubetest-86f93ec4-f8e5-11ea-bb39-5a82d0e4ca6e.eastus2.cloudapp.azure.com --kubeconfig=/root/tmp371921023/kubeconfig/kubeconfig.eastus2.json exec azuredisk-volume-tester-x4h6r-0 --namespace=azuredisk-8981 -- cmd /c type C:\mnt\test-1\data.txt'
Sep 17 13:49:02.262: INFO: stderr: ""
Sep 17 13:49:02.262: INFO: stdout: "hello world\r\nhello world\r\n"
Sep 17 13:49:02.262: INFO: deleting StatefulSet "azuredisk-8981"/"azuredisk-volume-tester-x4h6r"
Sep 17 13:49:02.535: INFO: Pod azuredisk-volume-tester-x4h6r-0 has the following logs: 
C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory

C:\>timeout 3600 
timeout: can't execute '3600': No such file or directory
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mayankshah1607** [comment]
Related - https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/426

**Comment by andyzhangx** [comment]
> Related - [kubernetes-sigs/azurefile-csi-driver#426](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/426)

this is e2e test failure, it's not related to unit test falure

**Comment by mayankshah1607** [comment]
My bad, just saw

**Comment by andyzhangx** [comment]
should already be fixed
