### ISSUE TITLE
driver daemonset pod run failure on Windows containerd

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#547]
**What happened**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/546/pull-azuredisk-csi-driver-e2e-migration-windows/1308389672262569984/build-log.txt
```
print out all nodes status ...
NAME                    STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
2877k8s00000000         Ready    agent    21m   v1.18.8   10.240.0.34    <none>        Windows Server 2019 Datacenter   10.0.17763.1339    containerd://1.4.0
2877k8s00000001         Ready    agent    22m   v1.18.8   10.240.0.65    <none>        Windows Server 2019 Datacenter   10.0.17763.1339    containerd://1.4.0
k8s-master-28775873-0   Ready    master   25m   v1.18.8   10.255.255.5   <none>        Ubuntu 18.04.5 LTS               5.3.0-1035-azure   containerd://1.3.2+azure
======================================================================================
print out all kube-system namespace pods status ...
NAME                                            READY   STATUS             RESTARTS   AGE   IP             NODE                    NOMINATED NODE   READINESS GATES
azure-cni-networkmonitor-6vfsl                  1/1     Running            0          25m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
azure-ip-masq-agent-8kw7j                       1/1     Running            0          25m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
blobfuse-flexvol-installer-mdqrt                1/1     Running            0          25m   10.240.0.4     k8s-master-28775873-0   <none>           <none>
coredns-56db558fb9-j7vfn                        1/1     Running            0          25m   10.240.0.9     k8s-master-28775873-0   <none>           <none>
coredns-autoscaler-5c7db64899-zpf7n             1/1     Running            0          25m   10.240.0.10    k8s-master-28775873-0   <none>           <none>
csi-azuredisk-controller-7d9b85db5b-vqsgv       5/5     Running            0          17m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
csi-azuredisk-node-win-jv4pk                    2/3     ImagePullBackOff   0          17m   10.240.0.77    2877k8s00000001         <none>           <none>
csi-azuredisk-node-win-kxnss                    2/3     ImagePullBackOff   0          17m   10.240.0.36    2877k8s00000000         <none>           <none>
csi-secrets-store-cg95x                         3/3     Running            0          25m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
csi-secrets-store-provider-azure-4j9qf          1/1     Running            0          25m   10.240.0.13    k8s-master-28775873-0   <none>           <none>
kube-addon-manager-k8s-master-28775873-0        1/1     Running            0          25m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
kube-apiserver-k8s-master-28775873-0            1/1     Running            0          24m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
kube-controller-manager-k8s-master-28775873-0   1/1     Running            0          24m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
kube-proxy-h2n67                                1/1     Running            0          25m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
kube-scheduler-k8s-master-28775873-0            1/1     Running            0          24m   10.255.255.5   k8s-master-28775873-0   <none>           <none>
metrics-server-6756f7f765-b8s8h                 1/1     Running            0          25m   10.240.0.11    k8s-master-28775873-0   <none>           <none>
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could be related to this issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/382

**Comment by abhisheksinghbaghel** [comment]
@andyzhangx Where can I find the test failure to investigate?
My understanding is that this PR unblocks one of the potential several issues with containerd. So can we let this PR go and investigate the test failures separately?
Unless you think that this PR is causing more failures?

**Comment by andyzhangx** [comment]
> @andyzhangx Where can I find the test failure to investigate?
> My understanding is that this PR unblocks one of the potential several issues with containerd. So can we let this PR go and investigate the test failures separately?
> Unless you think that this PR is causing more failures?

just run `/test pull-azuredisk-csi-driver-e2e-windows-containerd` on the PR and you will get test failure. Since disk driver on containerd does not work now, we can wait. This PR fixed the latest tag issue on containerd while would make the Makefile more complex(it's already complex enough), that would make it hard to maintain, since `os.version` is added in buildx, it's better that use buildx directly in the near future.

**Comment by abhisheksinghbaghel** [comment]
> > @andyzhangx Where can I find the test failure to investigate?
> > My understanding is that this PR unblocks one of the potential several issues with containerd. So can we let this PR go and investigate the test failures separately?
> > Unless you think that this PR is causing more failures?
> 
> just run `/test pull-azuredisk-csi-driver-e2e-windows-containerd` on the PR and you will get test failure. Since disk driver on containerd does not work now, we can wait. This PR fixed the latest tag issue on containerd while would make the Makefile more complex(it's already complex enough), that would make it hard to maintain, since `os.version` is added in buildx, it's better that use buildx directly in the near future.

I am not sure if I agree with that assertion, only thing that PR does is parameterizes push-manifest, so that we can call it with any release tag and yet get all the images annotated with `os.version`, whereas the existing version is hardcoded to add the `os.version` to specific release version and not to the `:latest` images.

**Comment by andyzhangx** [comment]
related to this blocking upstream issue: https://github.com/kubernetes/kubernetes/issues/99342
