### ISSUE TITLE
support LogicalSectorSize for UltraSSD

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#559]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

LogicalSectorSize should be with 2020-06-30/compute, when it's ready, should be supported by this driver.

We do have a feature in GA behind an AFEC flag where we expose a new disk property to customers where we let them specify whether the disk is 512 sector size enabled.
 
This is from Az cli for example:
--logical-sector-size          : Logical sector size in bytes for Ultra disks. Supported values are 512 ad 4096. 4096 is the default.

it's here in [2020-06-30/compute](https://github.com/Azure/azure-sdk-for-go/blob/928b9cbac68670876b583465f789bd3ba655777c/services/compute/mgmt/2020-06-30/compute/models.go#L1056-L1057)
```
	// LogicalSectorSize - Logical sector size in bytes for Ultra disks. Supported values are 512 ad 4096. 4096 is the default.
	LogicalSectorSize *int32 `json:"logicalSectorSize,omitempty"`
```

**Describe alternatives you've considered**

**Additional context**

**Comment by gopalvibm** [comment]
is this being worked on? There is no way for us to try this out in the current storage class definition. What other options are there? can we modify a disk after it gets created by using the regular storage class method?

**Comment by andyzhangx** [comment]
> is this being worked on? There is no way for us to try this out in the current storage class definition. What other options are there? can we modify a disk after it gets created by using the regular storage class

we are waiting on 2020-06-30/compute go sdk ready, and then work on this.
To workaround, only way is create a disk with this setting and then use static provisioning: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md#azuredisk-static-provisioninguse-an-existing-azure-disk

**Comment by andyzhangx** [comment]
created a PR to upgrade to 2020-06-30/compute go sdk first:
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/444

**Comment by andyzhangx** [comment]
@nearora-msft I have already upgraded go sdk to 2020-06-30 in this repo, so you could work on this now.
To create an AKS cluster with Ultra Disk support, follow this guide: https://docs.microsoft.com/en-us/azure/aks/use-ultra-disks
