### ISSUE TITLE
Error starting node and controller for CSI

### ISSUE THREAD

**Issue by carlosrbcunha** [kubernetes-sigs/azuredisk-csi-driver#560]
**What happened**:
CSI Node and Controller Plugin failed to start
**What you expected to happen**:

**How to reproduce it**:

Start node or controller job

**Anything else we need to know?**:

`I0930 09:29:17.208388       1 main.go:86] set up prometheus server on [::]:29604
I0930 09:29:17.209793       1 azuredisk.go:114] 
DRIVER INFORMATION:
-------------------
Build Date: "2020-09-30T06:42:33Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v0.10.0
Git Commit: 18ae1342cf55149e27e596d00a6a9d16c5480538
Go Version: go1.14.4
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone

Streaming logs below:
W0930 09:29:17.211710       1 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
I0930 09:29:17.211720       1 azure.go:56] could not read cloud config from secret
I0930 09:29:17.211725       1 azure.go:59] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/azure.json
I0930 09:29:17.211744       1 azure.go:77] read cloud config from file: /etc/kubernetes/azure.json successfully
I0930 09:29:17.219304       1 azure_auth.go:232] Using AzurePublicCloud environment
I0930 09:29:17.219418       1 azure_auth.go:117] azure: using client_id+client_secret to retrieve access token
I0930 09:29:17.238558       1 azure_interfaceclient.go:62] Azure InterfacesClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.238581       1 azure_interfaceclient.go:65] Azure InterfacesClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241726       1 azure_vmsizeclient.go:62] Azure VirtualMachineSizesClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241741       1 azure_vmsizeclient.go:65] Azure VirtualMachineSizesClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241903       1 azure_snapshotclient.go:63] Azure SnapshotClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241921       1 azure_snapshotclient.go:66] Azure SnapshotClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241939       1 azure_storageaccountclient.go:63] Azure StorageAccountClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241944       1 azure_storageaccountclient.go:66] Azure StorageAccountClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241953       1 azure_diskclient.go:63] Azure DisksClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241960       1 azure_diskclient.go:66] Azure DisksClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241972       1 azure_vmclient.go:63] Azure VirtualMachine client (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241976       1 azure_vmclient.go:66] Azure VirtualMachine client (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241992       1 azure_vmssclient.go:63] Azure VirtualMachineScaleSetClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.241996       1 azure_vmssclient.go:66] Azure VirtualMachineScaleSetClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242004       1 azure_vmssvmclient.go:64] Azure vmssVM client (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242008       1 azure_vmssvmclient.go:67] Azure vmssVM client (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242016       1 azure_routeclient.go:61] Azure RoutesClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242019       1 azure_routeclient.go:64] Azure RoutesClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242026       1 azure_subnetclient.go:62] Azure SubnetsClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242029       1 azure_subnetclient.go:65] Azure SubnetsClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242037       1 azure_routetableclient.go:61] Azure RouteTablesClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242045       1 azure_routetableclient.go:64] Azure RouteTablesClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242054       1 azure_loadbalancerclient.go:63] Azure LoadBalancersClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242061       1 azure_loadbalancerclient.go:66] Azure LoadBalancersClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242069       1 azure_securitygroupclient.go:63] Azure SecurityGroupsClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242075       1 azure_securitygroupclient.go:66] Azure SecurityGroupsClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242102       1 azure_publicipclient.go:63] Azure PublicIPAddressesClient (read ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.242108       1 azure_publicipclient.go:66] Azure PublicIPAddressesClient (write ops) using rate limit config: QPS=1, bucket=5
I0930 09:29:17.268040       1 mount_linux.go:163] Detected OS without systemd
I0930 09:29:17.268780       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
I0930 09:29:17.268806       1 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0930 09:29:17.268811       1 driver.go:80] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0930 09:29:17.268815       1 driver.go:80] Enabling controller service capability: LIST_SNAPSHOTS
I0930 09:29:17.268819       1 driver.go:80] Enabling controller service capability: CLONE_VOLUME
I0930 09:29:17.268823       1 driver.go:80] Enabling controller service capability: EXPAND_VOLUME
I0930 09:29:17.268828       1 driver.go:99] Enabling volume access mode: SINGLE_NODE_WRITER
I0930 09:29:17.268832       1 driver.go:90] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0930 09:29:17.268860       1 driver.go:90] Enabling node service capability: EXPAND_VOLUME
I0930 09:29:17.268865       1 driver.go:90] Enabling node service capability: GET_VOLUME_STATS
F0930 09:29:17.268914       1 server.go:82] Failed to remove /csi/csi.sock, error: remove /csi/csi.sock: permission denied
goroutine 32 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc000374360, 0x7b, 0x110)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x262bc80, 0xc000000003, 0x0, 0x0, 0xc00035fdc0, 0x25896bd, 0x9, 0x52, 0x0)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x19d
k8s.io/klog/v2.(*loggingT).printf(0x262bc80, 0x3, 0x0, 0x0, 0x1821351, 0x1e, 0xc000088f60, 0x2, 0x2)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17b
k8s.io/klog/v2.Fatalf(...)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.(*nonBlockingGRPCServer).serve(0xc000173880, 0x7ffd9b1add7f, 0x13, 0x1a66a20, 0xc000130e10, 0x1a88100, 0xc000130e10, 0x1a7d6c0, 0xc000130e10, 0xc000173800)
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common/server.go:82 +0x686
created by sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.(*nonBlockingGRPCServer).Start
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common/server.go:56 +0xcd

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000173888)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000173880)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.(*nonBlockingGRPCServer).Wait(0xc000173880)
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common/server.go:60 +0x2d
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).Run(0xc000130e10, 0x7ffd9b1add7f, 0x13, 0x0, 0x0, 0x18bdf00)
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk.go:152 +0x4dd
main.handle()
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:72 +0xe5
main.main()
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:63 +0xae

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x262bba0)
	/root/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/root/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 7 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x262bc80)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	/root/go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:416 +0xd6

goroutine 30 [IO wait]:
internal/poll.runtime_pollWait(0x7fe05723bf18, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000115998, 0x72, 0x0, 0x0, 0x18026cc)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000115980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc000115980, 0xc00008cd48, 0xc00005c700, 0x7fe07dec8108)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001732c0, 0xc00008cd88, 0x40ca58, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0001732c0, 0x16f79a0, 0xc00028f3b0, 0x15db680, 0x260ae20)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc0000fc1c0, 0x1a666a0, 0xc0001732c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2901 +0x25d
net/http.Serve(...)
	/usr/local/go/src/net/http/server.go:2468
main.serveMetrics(0x1a666a0, 0xc0001732c0, 0xc000101258, 0x45d090)
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:98 +0xc5
main.serve.func1(0x1a666a0, 0xc0001732c0, 0x18bdf48, 0xc00013b770, 0xa)
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:89 +0x80
created by main.serve
	/root/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:87 +0x12f

goroutine 11 [select]:
k8s.io/apimachinery/pkg/util/wait.contextForChannel.func1(0xc00007a660, 0xc0001cb8e0, 0x1a69de0, 0xc000270ac0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:279 +0xb7
created by k8s.io/apimachinery/pkg/util/wait.contextForChannel
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:278 +0x8c

goroutine 31 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0002d82a0, 0xc00008dfb8, 0xc00007a6c0, 0x0, 0x0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:526 +0x10f
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x6fc23ac00, 0xc0000547b8, 0xc00007a660, 0x0, 0x0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:479 +0xc2
k8s.io/apimachinery/pkg/util/wait.PollInfinite(0x6fc23ac00, 0xc0000547b8, 0x0, 0x0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:451 +0x87
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfinite(0x6fc23ac00, 0xc0000547b8, 0x0, 0x0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:468 +0x75
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run(0xc0003c08a0)
	/root/go/pkg/mod/k8s.io/legacy-cloud-providers@v0.0.0-20200908054054-791ca33c5f97/azure/azure_routes.go:95 +0x52
created by k8s.io/legacy-cloud-providers/azure.(*Cloud).InitializeCloudFromConfig
	/root/go/pkg/mod/k8s.io/legacy-cloud-providers@v0.0.0-20200908054054-791ca33c5f97/azure/azure.go:528 +0xa63

goroutine 12 [select]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc00007a780, 0x6fc23ac00, 0x0, 0xc00007a720)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:575 +0x16a
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2-beta.0/pkg/util/wait/wait.go:558 +0x8c`

**Environment**:
- CSI Driver version: v0.10.0
- Nomad version : 12.4
- OS (e.g. from /etc/os-release): Ubuntu 18,04,5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1026-azure #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
it works on Ubuntu, how can I repro your issue? have you added following config in your blob container in the deployment?
```
          securityContext:
            runAsUser: 0
```

**Comment by andyzhangx** [comment]
it failed here:
`server.go:82] Failed to remove /csi/csi.sock, error: remove /csi/csi.sock: permission denied`

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/18ae1342cf55149e27e596d00a6a9d16c5480538/pkg/csi-common/server.go#L81-L82

**Comment by carlosrbcunha** [comment]
I am running this on Nomad . Here are my nomad jobs for node and controller.

**Controller**
```
job "plugin-azure-disk-controller" {
  datacenters = ["dc1"]
  type = "service"

  vault {
    policies = ["nomad-jobs"]
  }

  group "controller" {
    count = 2

    constraint { # Don't deploy more than one instance on the same host
      distinct_hosts = true
    }

    # disable deployments
    update {
      max_parallel = 0
    }
    task "controller" {
      driver = "docker"

      template {
        change_mode = "noop"
        destination = "local/azure.json"
        data = <<EOH
{
"cloud":"AzurePublicCloud",
"tenantId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_TENANT_ID}}{{end}}",
"subscriptionId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_SUBSCRIPTION_ID}}{{end}}",
"aadClientId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_CLIENT_ID}}{{end}}",
"aadClientSecret": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_CLIENT_SECRET}}{{end}}",
"resourceGroup": "test-resource-group",
"location": "westeurope"
}
EOH
      }

      env {
        AZURE_CREDENTIAL_FILE = "/etc/kubernetes/azure.json"
      }

      config {
        image = "mcr.microsoft.com/k8s/csi/azuredisk-csi:v0.10.0"

        volumes = [
          "local/azure.json:/etc/kubernetes/azure.json"
        ]

        args = [
          "--nodeid=${attr.unique.hostname}-vm",
          "--endpoint=unix://csi/csi.sock",
          "--logtostderr",
          "--v=5",
        ]
      }

      csi_plugin {
        id        = "az-disk0"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        memory = 256
      }

      # ensuring the plugin has time to shut down gracefully
      kill_timeout = "2m"
    }
  }
}
```

**Node**
```
job "plugin-azure-disk-nodes" {
  datacenters = ["dc1"]

  vault {
    policies = ["nomad-jobs"]
  }

  # you can run node plugins as service jobs as well, but this ensures
  # that all nodes in the DC have a copy.
  type = "system"

  group "nodes" {
    task "node" {
      driver = "docker"

      template {
        change_mode = "noop"
        destination = "local/azure.json"
        data = <<EOH
{
"cloud":"AzurePublicCloud",
"tenantId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_TENANT_ID}}{{end}}",
"subscriptionId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_SUBSCRIPTION_ID}}{{end}}",
"aadClientId": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_CLIENT_ID}}{{end}}",
"aadClientSecret": "{{with secret "kv/azure/credentials"}}{{.Data.ARM_CLIENT_SECRET}}{{end}}",
"resourceGroup": "test-resource-group",
"location": "westeurope"
}
EOH
      }

      env {
        AZURE_CREDENTIAL_FILE = "/etc/kubernetes/azure.json"
      }

      config {
        image = "mcr.microsoft.com/k8s/csi/azuredisk-csi:v0.10.0"

        volumes = [
          "local/azure.json:/etc/kubernetes/azure.json"
        ]

        args = [
          "--nodeid=${attr.unique.hostname}-vm",
          "--endpoint=unix://csi/csi.sock",
          "--logtostderr",
          "--v=5",
        ]

        # node plugins must run as privileged jobs because they
        # mount disks to the host
        privileged = true
      }

      csi_plugin {
        id        = "az-disk0"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        memory = 256
      }

      # ensuring the plugin has time to shut down gracefully
      kill_timeout = "2m"
    }
  }
}
```

As you can see, I have no options on users used or directories, I am only starting the nodes and controllers that will plugin the CSI Driver into Nomad.
With previous versions we did not have this problem.
Is there any parameter we need to add for this to work correctly (O.S. , docker or nomad) ?

**Comment by andyzhangx** [comment]
do you know how to set `securityContext` on the nomad? Should change the deployment similar to PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/439)
```
          securityContext:
            privileged: true
            runAsUser: 0
```

**Comment by andyzhangx** [comment]
I will revert #558, revert PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/562 since #558 actually did not improve the security, that PR is just for bypass security scanning, while would introduce various permission setting issue.
cc @chewong

**Comment by andyzhangx** [comment]
I have reverted the PR, pls use `imagePullPolicy: Always` to get the newly built latest image, thanks.
