### ISSUE TITLE
reduce vendor size

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#58]
**Is your feature request related to a problem?/Why is this needed**

Currently this driver code only uses https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure and some k8s util lib, while the `vendor` directory has whole k8s library, need to update go dep config to reduce vendor size

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by Masquerade0097** [comment]
I would like to work on it.
