### ISSUE TITLE
Raw block + volume expansion does not work

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes-sigs/azuredisk-csi-driver#591]
**What happened**:

I am running kubernetes e2e tests specifically the volume expansion test https://github.com/kubernetes/kubernetes/blob/160c33a6a17b6c49fee365d7cbe2acc7f1fe2f8e/test/e2e/storage/testsuites/volume_expand.go#L169

And the combination of raw block and offline volume expansion does not work. The volume mount fail with following error in the pod events:
```
MapVolume.MarkVolumeAsMounted failed while expanding volume for volume "pvc-b060b08d-71e1-48cf-97f4-590ed86e7363" : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not get size of block volume at path devtmpfs[/sdc]: error when getting size of block volume at path devtmpfs[/sdc]: output: , err: exit status 1
```

**What you expected to happen**:
Expansion succeed.

**How to reproduce it**:
Create a raw block PVC and do volume expansion on it.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.9.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks, do you know is there any special handling to support `Raw block + volume expansion`,  actually filesystem+volume expansion already works now.

**Comment by Jiawei0227** [comment]
I am not really sure... I think there might something need to be done in the NodePublishVolume where you check if File System Expansion is required? Again I dont have much knowledge on this. 
/cc @msau42 to help understand this better.

**Comment by msau42** [comment]
For raw block PV, usually the block device is resized in the controller call, and there's nothing to do in the Node call because there's no filesystem. For example, in PD driver, this is a noop:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/f4608fbaa86182ffde2df3279bf61d10067ab454/pkg/gce-pd-csi-driver/node.go#L467

**Comment by Jiawei0227** [comment]
Keep exploring at this, I found the code in PDCSI is not being executed: 
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/f4608fbaa86182ffde2df3279bf61d10067ab454/pkg/gce-pd-csi-driver/node.go#L467

accesstype was never being passed to the CSI controller.
The reason pdcsi driver works is because https://github.com/kubernetes/kubernetes/blob/e0c587bf4fc1084cf915a6cbfe3db20c68f2597e/staging/src/k8s.io/mount-utils/mount_linux.go#L430

Here the pdcsi return error status 2. But the error is actually nil. While the azuredisk return 
"blkid: error: devtmpfs[/sdc]
devtmpfs[/\sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]: No such file or directory"

**Comment by Jiawei0227** [comment]
So basically it seems somehow the devicePath we get from `findmnt -o source --noheadings --mountpoint <volumepath>` is "devtmpfs[/sdc]
devtmpfs[/\sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]
devtmpfs[/sdc]:" This giant string
