### ISSUE TITLE
Snapshot restore cannot handle less than 1 Gi

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes-sigs/azuredisk-csi-driver#592]
**What happened**:
I am running the k8s e2e snapshottable test againest Azuredisk csi driver. And the snapshot test failed because it failed to restore the snapshot to PVC. And I looked into what happened:

The PVC created by the e2e test is only 1 M, and when create snapshot, it seems azuredisk will automatically round up to 1G. So when trying to restore the PVC, the pvc will not be able to restored correctly.

I am wondering if 1G is the minimum snapshot size azuredisk can do?

**Comment by msau42** [comment]
For the e2e test, you can set min supported size in the TestDriver.

When the PVC from snapshot is created, does it use 1mb or 1gb?

**Comment by Jiawei0227** [comment]
> When the PVC from snapshot is created, does it use 1mb or 1gb?
It is 1mb, and that's the problem because snapshot created by the original "1mi PVC" is 1Gi

**Comment by msau42** [comment]
@andyzhangx what do you think of the driver erroring if someone tries to create a pvc < 1gb. I know other plugins silently round up to 1gb, but I prefer erroring so that users don't be surprised by a higher bill.

**Comment by Jiawei0227** [comment]
Or I think we could change the capacity to 1Gi in the PVC. That's the current behavior of GCE PD CSI

**Comment by andyzhangx** [comment]
Azure disk does not support pvc < 1GB, default to 1GB as minimum is current behavior, BTW, in Azure billing, 1MB has same cost as  32GB ...

**Comment by Jiawei0227** [comment]
Yeah, I understand it does not support pvc<1GB, I think if we should make the PVC capacity to 1Gi instead of return 1Mi?

**Comment by Jiawei0227** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/controller.go#L842

**Comment by Jiawei0227** [comment]
Because I also notice this even when PVC only shows up as 1Mi:

```
$ KUBECONFIG=kubeconfig kubectl exec -it nginx-azuredisk -- df -h /mnt/azuredisk
Filesystem                Size      Used Available Use% Mounted on
/dev/sdc                975.9M      2.5M    957.4M   0% /mnt/azuredisk
```

**Comment by andyzhangx** [comment]
thanks, I created a PR to address this issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/593, PTAL
