### ISSUE TITLE
Snapshot restore PVC cannot mount

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes-sigs/azuredisk-csi-driver#597]
**What happened**:
External Storage [Driver: disk.csi.azure.com] [Testpattern: Pre-provisioned Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller
  should check snapshot fields, check restore correctly works after modifying source data, check deletion

I am running e2e test snapshottable test against the azuredisk driver. When I was running into this test, the pod using the restored PVC fail to start.

The following event occur during mount:
```
Normal   Scheduled               <unknown>            default-scheduler                          Successfully assigned snapshotting-1543 /restored-pvc-tester-9jxsp to nodepool-f985db88-68ff3c05000001                                                                             
Normal   SuccessfulAttachVolume  3m38s                attachdetach-controller                    AttachVolume.Attach succeeded for volume "pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f"                                                                                               
Warning  FailedMount             110s                 kubelet, nodepool-f985db88-68ff3c05000001  Unable to attach or mount volumes: unmounted volumes=[my-volume], unattached volumes=[my-volume default-token-5bmjn]: timed out waiting for the condition                         
Warning  FailedMount             83s (x9 over 3m37s)  kubelet, nodepool-f985db88-68ff3c05000001  MountVolume.MountDevice failed for volume "pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f" : rpc error: code = Internal desc = could not format "/dev/disk/azure/scsi1/lun2"(lun: "2"), and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f/globalmount"
```

The following is the log for azuredisk
```
2020-11-20T18:42:09.570726156Z stderr F I1120 18:42:09.570645       1 utils.go:108] GRPC call: /csi.v1.Controller/ControllerPublishVolume
2020-11-20T18:42:09.573608274Z stderr F I1120 18:42:09.570762       1 utils.go:109] GRPC request: {"node_id":"nodepool-f985db88-68ff3c05000001","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.
k8s.io/pv/name":"pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f","csi.storage.k8s.io/pvc/name":"pvc-4phg8","csi.storage.k8s.io/pvc/namespace":"snapshotting-1543","skuName":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1605893975912-8081-disk.csi.azur
e.com"},"volume_id":"/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f"}
2020-11-20T18:42:09.607054884Z stderr F I1120 18:42:09.599641       1 controllerserver.go:402] GetDiskLun returned: <nil>. Initiating attaching volume "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.C
ompute/disks/pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f" to node "nodepool-f985db88-68ff3c05000001".
2020-11-20T18:42:09.607073084Z stderr F I1120 18:42:09.599676       1 azure_vmss.go:185] Couldn't find VMSS VM with nodeName nodepool-f985db88-68ff3c05000001, refreshing the cache
2020-11-20T18:42:09.662052827Z stderr F I1120 18:42:09.661792       1 controllerserver.go:419] Trying to attach volume "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d-9d0d-4
ec9-b8c3-fce0564d401f" to node "nodepool-f985db88-68ff3c05000001"
2020-11-20T18:42:09.731785063Z stderr F I1120 18:42:09.731666       1 azure_controller_common.go:183] Trying to attach volume "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d
-9d0d-4ec9-b8c3-fce0564d401f" lun 2 to node "nodepool-f985db88-68ff3c05000001".
2020-11-20T18:42:09.731925464Z stderr F I1120 18:42:09.731862       1 azure_controller_vmss.go:101] azureDisk - update(anthos_cluster_f985db88): vm(nodepool-f985db88-68ff3c05000001) - attach disk(pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f, /subscriptions/e317f310-5d
67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f) with DiskEncryptionSetID()
2020-11-20T18:42:15.287784494Z stderr F I1120 18:42:15.287706       1 utils.go:108] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
2020-11-20T18:42:15.288790301Z stderr F I1120 18:42:15.287983       1 utils.go:109] GRPC request: {"node_id":"nodepool-f985db88-68ff3c05000001","volume_id":"/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Micros
oft.Compute/disks/pvc-b302c090-9204-4071-a506-1977f5cbe141"}
2020-11-20T18:42:15.288911101Z stderr F I1120 18:42:15.288861       1 controllerserver.go:470] Trying to detach volume /subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-40
71-a506-1977f5cbe141 from node nodepool-f985db88-68ff3c05000001
2020-11-20T18:42:15.289058102Z stderr F I1120 18:42:15.288995       1 azure_controller_common.go:208] detach /subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-19
77f5cbe141 from node "nodepool-f985db88-68ff3c05000001"
2020-11-20T18:42:24.95906011Z stderr F I1120 18:42:24.958952       1 azure_controller_vmss.go:113] azureDisk - update(anthos_cluster_f985db88): vm(nodepool-f985db88-68ff3c05000001) - attach disk(pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f, /subscriptions/e317f310-5d6
7-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d-9d0d-4ec9-b8c3-fce0564d401f)  returned with <nil>
2020-11-20T18:42:24.959193211Z stderr F I1120 18:42:24.959146       1 controllerserver.go:423] Attach operation successful: volume "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f
46f6d-9d0d-4ec9-b8c3-fce0564d401f" attached to node "nodepool-f985db88-68ff3c05000001".
2020-11-20T18:42:24.959266711Z stderr F I1120 18:42:24.959225       1 controllerserver.go:438] attach volume "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-94f46f6d-9d0d-4ec9-b8c3-f
ce0564d401f" to node "nodepool-f985db88-68ff3c05000001" successfully
2020-11-20T18:42:24.959777715Z stderr F I1120 18:42:24.959319       1 utils.go:114] GRPC response: {"publish_context":{"LUN":"2"}}
2020-11-20T18:42:24.959914715Z stderr F I1120 18:42:24.959879       1 azure_vmss.go:185] Couldn't find VMSS VM with nodeName nodepool-f985db88-68ff3c05000001, refreshing the cache
2020-11-20T18:42:25.020763898Z stderr F I1120 18:42:25.020664       1 azure_controller_vmss.go:145] azureDisk - detach disk: name "pvc-b302c090-9204-4071-a506-1977f5cbe141" uri "/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985
db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-1977f5cbe141"
2020-11-20T18:42:25.020853799Z stderr F I1120 18:42:25.020817       1 azure_controller_vmss.go:171] azureDisk - update(anthos_cluster_f985db88): vm(nodepool-f985db88-68ff3c05000001) - detach disk(pvc-b302c090-9204-4071-a506-1977f5cbe141, /subscriptions/e317f310-5d
67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-1977f5cbe141)
2020-11-20T18:42:40.215779083Z stderr F I1120 18:42:40.215669       1 azure_controller_vmss.go:183] azureDisk - update(anthos_cluster_f985db88): vm(nodepool-f985db88-68ff3c05000001) - detach disk(pvc-b302c090-9204-4071-a506-1977f5cbe141, /subscriptions/e317f310-5d
67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-1977f5cbe141) returned with <nil>
2020-11-20T18:42:40.215917284Z stderr F I1120 18:42:40.215875       1 azure_controller_common.go:242] azureDisk - detach disk(pvc-b302c090-9204-4071-a506-1977f5cbe141, /subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/provi
ders/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-1977f5cbe141) succeeded
2020-11-20T18:42:40.215988784Z stderr F I1120 18:42:40.215952       1 controllerserver.go:479] detach volume /subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-b302c090-9204-4071-a506-19
77f5cbe141 from node nodepool-f985db88-68ff3c05000001 successfully
2020-11-20T18:42:40.216452587Z stderr F I1120 18:42:40.216022       1 utils.go:114] GRPC response: {}
```

**What you expected to happen**:
The preprovisioned snapshot test pass

**How to reproduce it**:
Run snapshottable e2e test

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.9.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @msau42

**Comment by Jiawei0227** [comment]
Hmm, it seems this is flaky. It happens also to:

External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller
  should restore from snapshot with saved data after modifying source data

**Comment by Jiawei0227** [comment]
Okay, this is CSINode azuredisk log:
```
I1120 19:46:32.788248       1 utils.go:108] GRPC call: /csi.v1.Node/NodeStageVolume
I1120 19:46:32.788260       1 utils.go:109] GRPC request: {"publish_context":{"LUN":"2"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-236cb755-0e6a-4883-8003-ff00e5fc6326","csi.storage.k8s.io/pvc/name":"pvc-trz2n","csi.storage.k8s.io/pvc/namespace":"snapshotting-976","skuName":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1605893975912-8081-disk.csi.azure.com"},"volume_id":"/subscriptions/e317f310-5d67-42b3-8d6d-2a8c757f8cb8/resourceGroups/anthos_cluster_f985db88/providers/Microsoft.Compute/disks/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326"}
I1120 19:46:33.560188       1 azure_common_linux.go:175] azureDisk - found /dev/disk/azure/scsi1/lun2 by sde under /dev/disk/azure/scsi1/
I1120 19:46:33.560213       1 nodeserver.go:121] NodeStageVolume: formatting /dev/disk/azure/scsi1/lun2 and mounting at /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount with mount options([])
I1120 19:46:33.560225       1 mount_linux.go:405] Attempting to determine if disk "/dev/disk/azure/scsi1/lun2" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/azure/scsi1/lun2])
I1120 19:46:33.563693       1 mount_linux.go:408] Output: "DEVNAME=/dev/disk/azure/scsi1/lun2\nTYPE=ext4\n", err: <nil>
I1120 19:46:33.563952       1 mount_linux.go:298] Checking for issues with fsck on disk: /dev/disk/azure/scsi1/lun2
I1120 19:46:33.570399       1 mount_linux.go:311] `fsck` error fsck from util-linux 2.33.1
/dev/sde is in use.
e2fsck: Cannot continue, aborting.


I1120 19:46:33.571133       1 mount_linux.go:394] Attempting to mount disk /dev/disk/azure/scsi1/lun2 in ext4 format at /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount
I1120 19:46:33.571810       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t ext4 -o defaults /dev/disk/azure/scsi1/lun2 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount)
E1120 19:46:33.574875       1 mount_linux.go:150] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/azure/scsi1/lun2 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount: /dev/sde already mounted or mount point busy.

E1120 19:46:33.575122       1 utils.go:112] GRPC error: rpc error: code = Internal desc = could not format "/dev/disk/azure/scsi1/lun2"(lun: "2"), and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount"
```

**Comment by Jiawei0227** [comment]
okay so this is super flaky. It is not about retain/delete policy or dynamic/pre-provisioned pvc. The restore test will just fail. I am wondering if there is a race condition here potentially.

**Comment by andyzhangx** [comment]
@Jiawei0227 do you have the test case code? the error said `/dev/sde already mounted or mount point busy.`

**Comment by andyzhangx** [comment]
are you using the same pv name `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-236cb755-0e6a-4883-8003-ff00e5fc6326/globalmount` for snapshot restore? I think for snapshot restore scenario, it should use a different PVC/PV name.

**Comment by Jiawei0227** [comment]
Nope, I am using the upstream OSS snapshottable test. 

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/snapshottable.go#L213

**Comment by Jiawei0227** [comment]
Another data point on this: I add a 10s delay between delete the previous pod and start the next new pod using the snapshot. And this time the test succeed. Not sure if that is something related.

**Comment by Jiawei0227** [comment]
What I have found so far:

It seems that the issue is: when the system trying to do a fsck on the device, it reports that the device is **in use** which fails the NodeStageVolume step. I tried `lsof | grep /dev/sdxx(whatever the device is)`, it returns this:
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
multipath 447 root    7r   BLK   8,48      0t0  466 /dev/sdd
```

I dont really understand why and what multipath does here.

Another thought: since adding a 10s delay between the previous pod tear down and new pod creation, I checked the ControllerPublishVolume log, it seems the two times it all attach the disk to the same lun. But without the 10s delay, the first disk is on lun0, the second disk is on lun1. And then I guess after the second disk attaches the first disk gets detached. So is it possible there is some race here?...

**Comment by andyzhangx** [comment]
the disk detach could be more than > 10s, where did you add the sleep time in the snapshot test? Thanks.

**Comment by Jiawei0227** [comment]
A little more context about the test. Here is what the test does:

1. Create a PVC and start a pod to write some initial data
2. Delete the Pod. 
3. Create a Snapshot of the PVC. (Not waiting for the original disk to be fully detached)
4. Create another pod with the origin disk. Write some other data into the disk
5. Delete the Pod again.
6. Restore the snapshot to a new PVC and create a pod to use it.
7. Check the restored PVC has the original data.

I tried to add the 10s timeout between 5&6, and it seems everything is working fine.

**Comment by andyzhangx** [comment]
could be related to this PR? https://github.com/kubernetes-csi/csi-proxy/pull/84

**Comment by andyzhangx** [comment]
looks like that snapshot disk is broken when snapshot taken on attached and mounted disk on Ubuntu VM:
```
root@nodepool-f985db88-68ff3c05000001:/home/gkeadmin# lsof | grep /dev/sdd
multipath     447                              root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     448 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     449 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     450 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     451 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     452 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
multipath     447     453 multipath            root    7r      BLK               8,48       0t0        466 /dev/sdd
New
11:13
root@nodepool-f985db88-68ff3c05000001:/home/gkeadmin# lsscsi
[0:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sda 
[1:0:1:0]    disk    Msft     Virtual Disk     1.0   /dev/sdb 
[3:0:0:1]    disk    Msft     Virtual Disk     1.0   /dev/sdd 
[5:0:0:0]    cd/dvd  Msft     Virtual CD/ROM   1.0   /dev/sr0 
root@nodepool-f985db88-68ff3c05000001:/home/gkeadmin# fsck /dev/sdd
fsck from util-linux 2.34
e2fsck 1.45.5 (07-Jan-2020)
/dev/sdd is in use.
e2fsck: Cannot continue, aborting.
```

**Comment by Jiawei0227** [comment]
Another experiment we did:

Manually detach and re-attach the disk to the node from Azure console. The disk is still shown as `/dev/xxx is in use`. So it is indeed possible this is a broken snapshot.

**Comment by abhisheksinghbaghel** [comment]
@Jiawei0227 I am trying to set-up a repro for this. Can you share a few more details related to your environment set-up:
1. How are you provisioning your aks\aks-engine cluster? What is the size of cluster you're using?
2. How are you deploying the azure-disk csi driver, az cli + azure, help, script etc?
2. How\where you're running the test from? kubetest etc.?

**Comment by Jiawei0227** [comment]
Hey @abhisheksinghbaghel Thanks for your help on this!

1. I am installing k8s on the azure vm. So it's not an Azure managed kubernetes service. My cluster is very small, it's a 3 control-plane kubernetes cluster with a nodepool of size 2.
2. I am deploying the azure-disk driver follow the csi deployment instruction so it's not really much difference.
3. I am running the kubernetes testsuite snapshottable test which is here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/snapshottable.go#L200

This is part of the kubernetes e2e storage testsuite. You can find more instruction on executing the external testsuite here: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external

Basically you might need to do the following: 
1. Prepare a k8s cluster with Azuredisk csi driver installed
2. git clone kubernetes/kubernetes
3. You may want to check what's the snapshot api version in your k8s cluster since the latest k8s snapshottable test uses v1 snapshot api. If your cluster is running in v1beta1, you can change the api to v1beta1 here: https://github.com/kubernetes/kubernetes/blob/81e82b84531f8e99521a5a58945a3236f71acf78/test/e2e/storage/utils/snapshot.go#L38-L48
4. make WHAT=test/e2e/e2e.test
5. Create a DRIVER_CONFIG_PATH file for azuredisk driver: 
```
StorageClass:
  FromExistingClassName: azure-csi
SnapshotClass:
  FromExistingClassName: azure-csi-snapshotclass
DriverInfo:
  Name: disk.csi.azure.com
  SupportedSizeRange:
    Min: 10Gi
  RequiredAccessModes:
  - ReadWriteOnce
  Capabilities:
    persistence: true
    multipods: true
    exec: true
    block: true
    fsGroup: true
    topology: true
    controllerExpansion: true
    nodeExpansion: false
    volumeLimits: true
    snapshotDataSource: true
```
6. ginkgo -focus='External.Storage.*Dynamic.*delete.policy.*should.check.snapshot.fields.*' \
       -skip='\[Disruptive\]|\[Serial\]' \
       "$E2E_BINARY_PATH" \
       -- \
       -storage.testdriver="$DRIVER_CONFIG_PATH"


Please let me know if you encounter any difficulties.

**Comment by Jiawei0227** [comment]
And I might also give you a heads-up that the test is flaky so you might need to run it several times to get a failure. The failure rate for me is like 40%-60%

**Comment by abhisheksinghbaghel** [comment]
Thanks @Jiawei0227. The step #3 above helped. I ran tests one time, but didn't get a repro.
I am going to let the test run and check for repro in the morning.

Given your description, it feels like that there's a race condition which is causing the conflict during fsck run.
A repro would be more telling, but if you get a chance, try mounting the disk created from the snapshot to a different path (step #6). That would confirm if the snapshot itself has a problem.

**Comment by Jiawei0227** [comment]
@abhisheksinghbaghel Thanks! Please let me know if you could repro.

We have tried detach and re-attach the disk manually from Azure console, it still says the disk is in use.

**Comment by abhisheksinghbaghel** [comment]
@Jiawei0227 I gave it a day to repro this, but no luck. I'll continue to try for another day. I have a similar set-up except for the fact that I am using aks.

So for next steps:
1. Are you using a special kubernetes distribution?
2. Next time you get a repro, can you share full logs for the csi-azuredisk-controller, csi-azuredisk-node, csi-snapshot-controller and test (with timestamps and the original and snapshot restored disk having issues).
3. If you have a disk which is stuck in this state and wont mount again, we should be able to check that from back-end and see what's going on. So just share the details when you have a repro next time along with the logs.

**Comment by Jiawei0227** [comment]
1. I am using k8s v1.18.6 so I dont think there is anything special...
2. I will try again maybe early Jan
3. I am using the latest version azuredisk-csi-driver build from my local

I will try again with aks and see if that makes a difference. It is very easy to repro in my previous environment but let me switch to a new one. Thanks!

**Comment by andyzhangx** [comment]
@abhisheksinghbaghel any update?
maybe @sunpa93 could help since he is already working on snapshot restore test, thanks.

**Comment by abhisheksinghbaghel** [comment]
@Jiawei0227 Any luck with the repro?

**Comment by Jiawei0227** [comment]
I haven't got a chance to work on this. I will probably try that again sometime later this month using the latest azurefile csi driver.

**Comment by Jiawei0227** [comment]
I had this repro using Azuredisk csi driver v1.1.0 using the v1.19 e2e test binary again. Seems the issue still exist.

**Comment by Jiawei0227** [comment]
One thing that can help to run the e2e test is to use k8s release v1.19, and when run it, using flag: `-focus='External.Storage.*Testpattern.*Dynamic.Snapshot.*delete policy.*snapshottable.Feature:VolumeSnapshotDataSource.*volume.snapshot.controller.*'` to focus on this one test so that it is easier to repro.

**Comment by Jiawei0227** [comment]
Hmm. I tried with AKS and I cannot reproduce this.... Seems like this is with my cluster environment then...

**Comment by Jiawei0227** [comment]
lol wait, I only upgrade the node driver version not the controller version... let me upgrade the controller side and try again

**Comment by Jiawei0227** [comment]
I upgrade the csi driver to v1.1.0 and still no luck... I guess there must be something wrong here. It seems we are using ubuntu 20.04. I notice AKS is using ubuntu 18.04, could that be a difference?

**Comment by Jiawei0227** [comment]
/remove-lifecycle rotten

I can still reproduce. Sync with @abhisheksinghbaghel offline and we will have a debug session

**Comment by Jiawei0227** [comment]
We had a debug session and some more interesting information. It seems somehow the bug is related to multipath. We try to attach the restored PVC on another new node and it succeed without any issue, which proves that the Snapshot itself is correct.

Somehow, when we attach the disk to the node, there will be a multipath service running whereas in the new node there is not. 

Another interesting experiment we did is we attached both new and old PVC to the old node and multipath is treating these two devices as the same and treat them as two different path.
```
ubuntu@vmss-np-a3d27726-anthos-ae2ff2ea000000:/dev$ sudo multipath -ll
mpatha (3600224801400649cefe46cf53e8f174b) dm-0 Msft,Virtual Disk
size=5.0G features='0' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=1 status=active
| `- 1:0:0:1 sdd 8:48 active ready running
`-+- policy='service-time 0' prio=1 status=enabled
  `- 1:0:0:0 sdc 8:32 active ready running
```
However on the new node there is no multipath running when disk attached.

Will do some more investigation on it.

**Comment by andyzhangx** [comment]
@Jiawei0227   thanks for sharing, so disable `multipath` would simply fix the issue?

**Comment by abhisheksinghbaghel** [comment]
@Jiawei0227 As discussed earlier today, I tried to repro this on a single node, i.e. without the e2e test and looks like the issue does appear to be OS/multipath specific.
I don't see multipath enabled on ubuntu 18.04 and reading online confirms that its enabled by default on 20.04 and that's probably the reason it repros at your end and not time.

To find right resolution for this can you send me the contents of /etc/multipath.conf.

It appears that the simplest resolution would be to set something like this in the config and see if issue goes away:

`
blacklist {
	devnode "^sd[a-z]"                       ### blacklist all scsi Devices
}
`

Also, from where exactly you're picking up this OS image, is it from the azure catalog or something custom from your end?
