### ISSUE TITLE
Deletion failed when a disk was already deleted

### ISSUE THREAD

**Issue by zuzzas** [kubernetes-sigs/azuredisk-csi-driver#614]
**What happened**:

Deletion failed when a disk was already deleted.

```
E1214 14:40:25.873355       1 controller.go:1016] error syncing volume "pvc-99685d1e-00ca-4853-92be-87b07b5c37ff": rpc error: code = Unknown desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/disks/pvc-99685d1e-00ca-4853-92be-87b07b5c37ff' under resource group 'klimentyev-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
```

**What you expected to happen**:

I expected CSI `DeleteVolume` request to succeed since there is no disk to delete.

**How to reproduce it**:

Detach and delete a Volume manually (through the console). azuredisk-csi controller won't be able to delete it then.

**Anything else we need to know?**:

I've tried to create a PR for this issue, but found it hard to get over the following hurdle.

There is a type erasure in the code path:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/f8a9b018a786664b4e49ca223ae186c132415455/vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go#L79-L80

We can compare errors via string comparison, but that's just horrible.

**Comment by edreed** [comment]
@zuzzas The error returned by [DeleteManagedDisk](https://pkg.go.dev/k8s.io/legacy-cloud-providers/azure#ManagedDiskController.DeleteManagedDisk) should be a [retry.Error](https://pkg.go.dev/k8s.io/legacy-cloud-providers/azure/retry#Error). Could you use a type assertion to convert to retry.Error and call [IsNotFound](https://pkg.go.dev/k8s.io/legacy-cloud-providers/azure/retry#Error.IsNotFound)?

**Comment by edreed** [comment]
NM. I just realized that DeleteManagedDisk converts the retry.Error to a standard error through the use of the [retry.Error.Error()](https://pkg.go.dev/k8s.io/legacy-cloud-providers/azure/retry#Error.Error) function. *SIGH*

**Comment by zuzzas** [comment]
Aye, I've been bashing at my keyboard for 10 minutes without realizing that. :c

**Comment by edreed** [comment]
@mukhoakash- *Eugh* It seems there is a [`HasStatusForbiddenOrIgnoredError()`] function in `cloud-provider-azure` specifically for checking the error when deleting a resource to ignore "Not Found" errors. It does a string search for the specific `HTTPStatusCode`. Sadly, it also ignores "Forbidden" errors.

**Comment by andyzhangx** [comment]
already fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/623 in v1.3.0 release
