### ISSUE TITLE
check whether this driver could run on a RBAC enabled k8s cluster

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by ashishranjan738** [comment]
i would to work on this issue @andyzhangx

**Comment by andyzhangx** [comment]
I have validated it works well on a RBAC enabled cluster
