### ISSUE TITLE
CSI Driver support for Azure Stack HCI/AKS VHD

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes-sigs/azuredisk-csi-driver#638]
Does the Azure Disk CSI Driver support the VHD used by AKS running on-prem on top of Azure Stack HCI ?

**Comment by andyzhangx** [comment]
when do you mean `VHD used by AKS`? As I know, AKS would only provide Ubuntu 16.04 and 18.04 nodes with Ubuntu 16.04 and 18.04 VHD.

And Azure Disk CSI Driver supports Azure Stack now, @songjiaxun is working on this.

**Comment by ezYakaEagle442** [comment]
To clarify, I do not refer to Azure stack Hub, the scenario I think about is :

1. Azure Stack HCI is deployed, the [docs states](https://docs.microsoft.com/en-us/azure-stack/hci/overview) _If you plan to use Software Defined Networking (SDN), you'll need a virtual hard disk (VHD) for the Azure Stack HCI operating system to create Network Controller VMs_
2. AKS is deployed on top of it 
3. In the above AKS cluster , how to configure a PV that would be bound to a Disk managed by HCI ( so not Azure Disk) ?

1. AKS on HCI [doc mentions](https://docs.microsoft.com/en-us/azure-stack/aks-hci/overview#use-aks-to-automate-management-of-containerized-applications) : _functionality provided : Manage storage and networking on your Kubernetes cluster _
2.  on [K8S docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#parameters) the Storage class is not mentionned in this scenario
3. I have found [issue#18](https://github.com/Azure/aks-hci/issues/18) about storage enhancement

Do we have a CSI Driver supported to use in this scenario ?

**Comment by ezYakaEagle442** [comment]
I have also seen [https://github.com/Azure/aks-hci/issues/54](https://github.com/Azure/aks-hci/issues/54

**Comment by andyzhangx** [comment]
not sure what this CSI driver supports HCI or not, I think you could try on a k8s cluster first : https://github.com/kubernetes-sigs/azuredisk-csi-driver#install-driver-on-a-kubernetes-cluster

**Comment by ezYakaEagle442** [comment]
I have found this [MS blog](https://techcommunity.microsoft.com/t5/azure-stack-blog/azure-kubernetes-service-on-azure-stack-hci-deliver-storage/ba-p/1703996) explaining tha tthe Storage Class to use with the HCI Software Defined Storage "Storage spaces Direct" is : msvhd

**Comment by andyzhangx** [comment]
that's another CSI driver
