### ISSUE TITLE
Dynamic Azure Disk PVC Extension causes pod to fail post resize

### ISSUE THREAD

**Issue by deepak16795** [kubernetes-sigs/azuredisk-csi-driver#714]
We are using a custom kubernetes cluster and we are using CSI driver for Dynamic Azure Disk provisioning. Normal Provisioning works without issues but trying to mount the PVC again post extension of the PVC gives the error. Please find the below steps taken and error reported.

**Steps for Creating CSI Driver in Kubernetes.**
1)kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/azure.json" -n kube-system
2) Using CSI version (0.9.0)
3)curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/v0.9.0/deploy/install-driver.sh | bash -s v0.9.0 --
4)Content of Azure.json

 cat /etc/kubernetes/cloud.conf
{
    "cloud":"AzurePublicCloud",
    "tenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "subscriptionId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aadClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aadClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "resourceGroup": "xxxxxxxxxxxxx",
    "location": "",
    "subnetName": "",
    "securityGroupName": "",
    "vnetName": "",
    "vnetResourceGroup": "",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffExponent": 1.5,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderBackoffJitter": 1,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 3,
    "cloudProviderRateLimitBucket": 10,
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": true
}

Error Logs:
**Normal Provision Working without Error**
root@master-testing:csi-azure-disk# kdesc sc managed-csi
Name:            managed-csi
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"managed-csi"},"parameters":{"skuname":"StandardSSD_LRS"},"provisioner":"disk.csi.azure.com","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}

Provisioner:           disk.csi.azure.com
Parameters:            skuname=StandardSSD_LRS
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

root@master-testing:dynamic-azuredisk# kg pvc
NAME                                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistent-storage-statefulset-azuredisk-0   Bound    pvc-187d49ee-1eca-4712-80d7-11e71802d883   5Gi        RWO            managed-csi    17s
root@master-testing:dynamic-azuredisk# kg pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                STORAGECLASS   REASON   AGE
pvc-187d49ee-1eca-4712-80d7-11e71802d883   5Gi        RWO            Delete           Bound    default/persistent-storage-statefulset-azuredisk-0   managed-csi             14s

root@master-testing:dynamic-azuredisk# kexec -it statefulset-azuredisk-0 -- df -h /mnt/azuredisk
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc        4.9G   20M  4.9G   1% /mnt/azuredisk

**Starting the Process to Resize it**
root@master-testing:dynamic-azuredisk# kubectl get statefulsets
NAME                    READY   AGE
statefulset-azuredisk   1/1     2m21s
root@master-testing:dynamic-azuredisk# kubectl scale statefulsets statefulset-azuredisk --replicas=0
statefulset.apps/statefulset-azuredisk scaled
root@master-testing:dynamic-azuredisk# kubectl get statefulsets
NAME                    READY   AGE
statefulset-azuredisk   0/0     3m39s

root@master-testing:dynamic-azuredisk# kubectl patch pvc  persistent-storage-statefulset-azuredisk-0 --type merge --patch '{"spec": {"resources": {"requests": {"storage": "8Gi"}}}}'
persistentvolumeclaim/persistent-storage-statefulset-azuredisk-0 patched
root@master-testing:dynamic-azuredisk# kg pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                STORAGECLASS   REASON   AGE
pvc-187d49ee-1eca-4712-80d7-11e71802d883   8Gi        RWO            Delete           Bound    default/persistent-storage-statefulset-azuredisk-0   managed-csi             5m24s

root@master-testing:dynamic-azuredisk# kdesc pvc persistent-storage-statefulset-azuredisk-0
Name:          persistent-storage-statefulset-azuredisk-0
Namespace:     default
StorageClass:  managed-csi
Status:        Bound
Volume:        pvc-187d49ee-1eca-4712-80d7-11e71802d883
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-class: managed-csi
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       <none>
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 04 Feb 2021 13:38:22 +0000           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                    Age    From                                                                    Message
  ----     ------                    ----   ----                                                                    -------
  Normal   ExternalProvisioning      6m10s  persistentvolume-controller                                             waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
  Normal   Provisioning              6m10s  disk.csi.azure.com_master-testing_cd332bc2-c8d2-45e7-8431-17a613df23c0  External provisioner is provisioning volume for claim "default/persistent-storage-statefulset-azuredisk-0"
  Normal   ProvisioningSucceeded     6m1s   disk.csi.azure.com_master-testing_cd332bc2-c8d2-45e7-8431-17a613df23c0  Successfully provisioned volume pvc-187d49ee-1eca-4712-80d7-11e71802d883
  Normal   Resizing                  53s    external-resizer disk.csi.azure.com                                     External resizer is resizing volume pvc-187d49ee-1eca-4712-80d7-11e71802d883
  Warning  ExternalExpanding         53s    volume_expand                                                           Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   FileSystemResizeRequired  51s    external-resizer disk.csi.azure.com                                     Require file system resize of volume on node

root@master-testing:dynamic-azuredisk# kubectl scale statefulsets statefulset-azuredisk --replicas=1
statefulset.apps/statefulset-azuredisk scaled

root@master-testing:dynamic-azuredisk# kgp
NAME                      READY   STATUS              RESTARTS   AGE
statefulset-azuredisk-0   0/1     ContainerCreating   0          78s

root@master-testing:dynamic-azuredisk# kdesc pod statefulset-azuredisk-0 | tail -10
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               89s               default-scheduler        Successfully assigned default/statefulset-azuredisk-0 to master-testing
  Normal   SuccessfulAttachVolume  78s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-187d49ee-1eca-4712-80d7-11e71802d883"
  Warning  FailedMount             8s (x8 over 72s)  kubelet                  MountVolume.MountDevice failed while expanding volume for volume "pvc-187d49ee-1eca-4712-80d7-11e71802d883" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not get size of block volume at path /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-187d49ee-1eca-4712-80d7-11e71802d883/globalmount: error when getting size of block volume at path /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-187d49ee-1eca-4712-80d7-11e71802d883/globalmount: output: , err: exit status 1

**Environment**
root@master-testing:csi-azure-disk# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

**Comment by andyzhangx** [comment]
I think this bug was introduced by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/607, volume expansion is broken in v0.10.0

```console
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2e033853-f502-4a1c-94f5-05ee91946117/globalmount type ext4 (rw,relatime)

# blockdev --getsize64 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2e033853-f502-4a1c-94f5-05ee91946117/globalmount
blockdev: ioctl error on BLKGETSIZE64: Inappropriate ioctl for device
# blockdev --getsize64 /dev/sdc
21474836480
```

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/715 would fix this issue, thanks.

**Comment by gsxmax** [comment]
Hi @andyzhangx , after using the master branch, it seems the PVC launch failed. Below is the error:
 
` Warning  ProvisioningFailed    3s (x3 over 4s)  disk.csi.azure.com_master-testing_7eacf2e5-4695-4802-8153-6e4ddc792d5b  failed to provision volume with StorageClass "managed-csi": rpc error: code = Unknown desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/bd9593b1-8217-4859-b4cb-940a1e410122/resourceGroups/infra-auto/providers/Microsoft.Compute/disks/pvc-9e175fb2-8a5c-4ace-a666-153a3be7ae09?api-version=2020-06-30: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.core.windows.net%2F`

Could you please let us know how to mitigate this issue?

**Comment by andyzhangx** [comment]
> 169.254.169.254

@gsxmax sth wrong with the identity on the node where your driver controller is running on, could you delete the controller pod, and let it recreate again? If that does not work, pls provide controller logs by: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case1-disk-createdeleteattachdetachsnapshotrestore-failed

**Comment by andyzhangx** [comment]
BTW, from the error msg, it looks like there is sth wrong on that node(where your driver controller is running on) has issue using instance metadata, try below command on that node:
```console
curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-04-30" | jq
```

**Comment by deepak16795** [comment]
Hello @andyzhangx ,
I can see error logs only in the controller and please find the below error logs.

Controller Error:
I0207 13:51:06.914409       1 utils.go:94] GRPC call: /csi.v1.Controller/ListVolumes
I0207 13:51:06.914476       1 utils.go:95] GRPC request: {}
I0207 13:51:06.991098       1 azure_diskclient.go:339] Received error in disk.list.request: resourceID: /subscriptions/bd9593b1-8217-4859-b4cb-940a1e410122/resourceGroups/infra-auto/providers/Microsoft.Compute/disks, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/bd9593b1-8217-4859-b4cb-940a1e410122/resourceGroups/infra-auto/providers/Microsoft.Compute/disks?api-version=2020-06-30: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.core.windows.net%2F
E0207 13:51:06.991128       1 utils.go:99] GRPC error: rpc error: code = Internal desc = ListVolumes on rg(infra-auto) failed with error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/bd9593b1-8217-4859-b4cb-940a1e410122/resourceGroups/infra-auto/providers/Microsoft.Compute/disks?api-version=2020-06-30: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.core.windows.net%2F

**Output of curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-04-30" | jq**

root@master-testing:dynamic-azuredisk# curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2019-04-30" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1894  100  1894    0     0   369k      0 --:--:-- --:--:-- --:--:--  369k
{
  "compute": {
    "azEnvironment": "AzurePublicCloud",
    "customData": "",
    "location": "SouthIndia",
    "name": "master-testing",
    "offer": "UbuntuServer",
    "osType": "Linux",
    "placementGroupId": "",
    "plan": {
      "name": "",
      "product": "",
      "publisher": ""
    },
    "platformFaultDomain": "0",
    "platformUpdateDomain": "0",
    "provider": "Microsoft.Compute",
    "publicKeys": [
      {
        "keyData": "---- BEGIN SSH2 PUBLIC KEY ----\nComment: \"4096-bit RSA, converted by deepakd@JCR487-IND-LT from OpenSS\"\nAAAA\n---- END SSH2 PUBLIC KEY ----",
        "path": "/home/azureuser/.ssh/authorized_keys"
      }
    ],
    "publisher": "Canonical",
    "resourceGroupName": "infra-auto",
    "resourceId": "/subscriptions/##########################/resourceGroups/infra-auto/providers/Microsoft.Compute/virtualMachines/master-testing",
    "sku": "18.04-LTS",
    "subscriptionId": "##########################",
    "tags": "",
    "version": "18.04.202101290",
    "vmId": "a7c9f829-0614-4cb1-b81a-c03e5c7c2",
    "vmScaleSetName": "",
    "vmSize": "Standard_B2s",
    "zone": ""
  },
  "network": {
    "interface": [
      {
        "ipv4": {
          "ipAddress": [
            {
              "privateIpAddress": "10.1.0.4",
              "publicIpAddress": "##################"
            }
          ],
          "subnet": [
            {
              "address": "10.1.0.0",
              "prefix": "19"
            }
          ]
        },
        "ipv6": {
          "ipAddress": []
        },
        "macAddress": "000D3AC9B28B"
      }
    ]
  }
}

**Comment by andyzhangx** [comment]
What's your controller deployment? The controller should not use InstanceMetadata, have you set nodeID for the controller deployment? How did you deploy this driver?

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/09466126dce7111dcac8968a9a6abc229a93ae0b/pkg/azuredisk/azuredisk.go#L127-L132

**Comment by deepak16795** [comment]
@andyzhangx 
I Created an configmap with the cloud.conf file and then initialized the controller using kubectl.

1)kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" -n kube-system
2)curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/install-driver.sh | bash -s master --

**Comment by andyzhangx** [comment]
> @andyzhangx
> I Created an configmap with the cloud.conf file and then initialized the controller using kubectl.
> 
> 1)kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" -n kube-system
> 2)curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/install-driver.sh | bash -s master --

@deepak16795 could you provide the first 100 lines of controller logs?

**Comment by deepak16795** [comment]
@andyzhangx The issue was with the SP associated with the Resource Group have fixed it out and and now resizing also works fine. Thanks for your support and time on this.

**Comment by andyzhangx** [comment]
> @andyzhangx The issue was with the SP associated with the Resource Group have fixed it out and and now resizing also works fine. Thanks for your support and time on this.

@deepak16795 great, so the SP does not have enough permission on the Resource Group?

**Comment by deepak16795** [comment]
Yes @andyzhangx that was the issue.

**Comment by yzarca** [comment]
@deepak16795 could you share (of course no personal information) how did you set your cloud.conf file ?
Did you set up this into on premise k8s cluster ?

Thanks.

**Comment by yzarca** [comment]
> @deepak16795 could you share (of course no personal information) how did you set your cloud.conf file ?
> Did you set up this into on premise k8s cluster ?
> 
> Thanks.

I found out you already did, sorry i didnt check well.
So i guess the matter is hout to get in the right way the parameters:
```
"aadClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"aadClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
```
Is there any procedure to help ?

Thanks,
Yzarca

**Comment by deepak16795** [comment]
@yzarca We are using Azure Devops Pipeline for populating the client id and secret where we create the Service Principal as part of it and update it in the azure.json

**Comment by andyzhangx** [comment]
> > @deepak16795 could you share (of course no personal information) how did you set your cloud.conf file ?
> > Did you set up this into on premise k8s cluster ?
> > Thanks.
> 
> I found out you already did, sorry i didnt check well.
> So i guess the matter is hout to get in the right way the parameters:
> 
> ```
> "aadClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
> "aadClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
> ```
> 
> Is there any procedure to help ?
> 
> Thanks,
> Yzarca

@yzarca you could check this: https://github.com/kubernetes-sigs/azuredisk-csi-driver#prerequisite
