### ISSUE TITLE
Cannot mount disk due to findDiskByLun(0) failed within timeout

### ISSUE THREAD

**Issue by sharkymcdongles** [kubernetes-sigs/azuredisk-csi-driver#73]
**What happened**:
I tested with the nginx test per documentation, and it worked fine. I then try to use the plugin to deploy a postgres when I get this error.

> Events:
>   Type     Reason                  Age                 From                     Message
>   ----     ------                  ----                ----                     -------
>   Warning  FailedScheduling        16m (x4 over 17m)   default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 16 times)
>   Normal   Scheduled               16m                 default-scheduler        Successfully assigned mip-ppr/mls-db-mip-ppr-beiersdorf-0 to minion-9
>   Warning  FailedAttachVolume      16m                 attachdetach-controller  AttachVolume.Attach failed for volume "pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74" : attachment timeout for volume /subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-3c28483b-5c4d-11e9-a5cc-000d3a29856b
>   Warning  FailedAttachVolume      14m (x8 over 16m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
>   Normal   SuccessfulAttachVolume  12m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74"
>   Warning  FailedMount             76s (x7 over 14m)   kubelet, minion-9        Unable to mount volumes for pod "mls-db-mip-ppr-beiersdorf-0_mip-ppr(3836943f-5c4d-11e9-9ea8-000d3a269e74)": timeout expired waiting for volumes to attach or mount for pod "mip-ppr"/"mls-db-mip-ppr-beiersdorf-0". list of unmounted volumes=[data]. list of unattached volumes=[data wal-g-archive custom-config mls-db-mip-ppr-beiersdorf-token-v2gkn]
>   Warning  FailedMount             75s (x12 over 10m)  kubelet, minion-9        MountVolume.MountDevice failed for volume "pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74" : rpc error: code = Unknown desc = azureDisk - findDiskByLun(0) failed within timeout

and

> I0411 11:42:05.314128       1 utils.go:106] GRPC call: /csi.v1.Node/NodeStageVolume
> I0411 11:42:05.314164       1 utils.go:107] GRPC request: volume_id:"/subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-3c28483b-5c4d-11e9-a5cc-000d3a29856b" publish_context:<key:"devicePath" value:"0" > staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74/globalmount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:"cachingMode" value:"ReadOnly" > volume_context:<key:"kind" value:"managed" > volume_context:<key:"skuname" value:"Premium_LRS" > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1554206899327-8081-disk.csi.azure.com" > 
> I0411 11:42:05.314265       1 nodeserver.go:49] NodeStageVolume: called with args {VolumeId:/subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-3c28483b-5c4d-11e9-a5cc-000d3a29856b PublishContext:map[devicePath:0] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-383468b8-5c4d-11e9-9ea8-000d3a269e74/globalmount VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Secrets:map[] VolumeContext:map[cachingMode:ReadOnly kind:managed skuname:Premium_LRS storage.kubernetes.io/csiProvisionerIdentity:1554206899327-8081-disk.csi.azure.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
> I0411 11:42:11.530559       1 azure_common_linux.go:104] /dev/disk/azure is not populated, now try to parse 0:0:0:0 directly
> I0411 11:42:11.530612       1 azure_common_linux.go:104] /dev/disk/azure is not populated, now try to parse 1:0:1:0 directly
> I0411 11:42:11.530621       1 azure_common_linux.go:104] /dev/disk/azure is not populated, now try to parse 3:0:0:0 directly
> I0411 11:42:11.530630       1 azure_common_linux.go:104] /dev/disk/azure is not populated, now try to parse 5:0:0:0 directly
> I0411 11:42:11.530764       1 azure_common_linux.go:147] model doesn't match VHD, got Virtual CD/ROM
> E0411 11:42:11.530803       1 utils.go:110] GRPC error: azureDisk - findDiskByLun(0) failed within timeout
> I0411 11:42:19.861801       1 utils.go:106] GRPC call: /csi.v1.Identity/GetPluginInfo
> I0411 11:42:19.861835       1 utils.go:107] GRPC request: 
> I0411 11:42:19.861882       1 identityserver.go:33] Using default GetPluginInfo
> I0411 11:42:19.861889       1 utils.go:112] GRPC response: name:"disk.csi.azure.com" vendor_version:"v0.2.0-alpha" 
> I0411 11:42:19.863325       1 utils.go:106] GRPC call: /csi.v1.Identity/Probe

**What you expected to happen**:
Disks attach and mount and actually work.

**How to reproduce it**:
Install CSI driver v0.2.0-alpha on k8s 1.14.

Try deploying a postgres from kubedb. This works fine with our ceph storageclass.

> allowVolumeExpansion: true
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   creationTimestamp: "2019-04-09T12:43:11Z"
>   name: fast
>   resourceVersion: "7993586"
>   selfLink: /apis/storage.k8s.io/v1/storageclasses/fast
>   uid: 09093d0d-5ac5-11e9-9ea8-000d3a269e74
> parameters:
>   cachingMode: ReadOnly
>   kind: managed
>   skuname: Premium_LRS
> provisioner: disk.csi.azure.com
> reclaimPolicy: Delete
> volumeBindingMode: Immediate

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v0.2.0-alpha
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): "Ubuntu 18.04.2 LTS"
- Kernel (e.g. `uname -a`): 4.18.0-1014-azure

**Comment by andyzhangx** [comment]
@sharkymcdongles thanks for the feedback, I think the problem here is why in your Ubuntu 18.04 agent node, `/dev/disk/azure` dir is not populated, below are mine, `lun0` is the data disk:
```
# tree /dev/disk/azure/
/dev/disk/azure/
├── resource -> ../../sdb
├── resource-part1 -> ../../sdb1
├── root -> ../../sda
├── root-part1 -> ../../sda1
├── root-part14 -> ../../sda14
├── root-part15 -> ../../sda15
└── scsi1
    └── lun0 -> ../../../sdc
```

could you paste the UDEV rule on your agent VM:
`# sudo cat /etc/udev/rules.d/66-azure-storage.rules`

**Comment by sharkymcdongles** [comment]
It does not exist. Should the deployment have handled this?

> cat /etc/udev/rules.d/66-azure-storage.rules
> cat: /etc/udev/rules.d/66-azure-storage.rules: No such file or directory

**Comment by andyzhangx** [comment]
@sharkymcdongles how do you set up that Ubuntu 18.04 VM? if it's by Azure platform, waagent will be installed and that UDEV rule will be installed too.

**Comment by sharkymcdongles** [comment]
This was provisioned via an arm template via kubespray. I rolled out the udev per this to all cluster nodes, and it works now for the most part. Thank you so much! Unfortunately one of the disks it tried to create now gets this:

> I0411 16:52:01.294428       1 utils.go:107] GRPC request: volume_id:"/subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-e752dd64-5c76-11e9-a5cc-000d3a29856b" publish_context:<key:"devicePath" value:"0" > staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:"cachingMode" value:"ReadOnly" > volume_context:<key:"kind" value:"managed" > volume_context:<key:"skuname" value:"Premium_LRS" > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1554206899327-8081-disk.csi.azure.com" >
> I0411 16:52:01.294536       1 nodeserver.go:49] NodeStageVolume: called with args {VolumeId:/subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-e752dd64-5c76-11e9-a5cc-000d3a29856b PublishContext:map[devicePath:0] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Secrets:map[] VolumeContext:map[cachingMode:ReadOnly kind:managed skuname:Premium_LRS storage.kubernetes.io/csiProvisionerIdentity:1554206899327-8081-disk.csi.azure.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
> E0411 16:52:01.294633       1 utils.go:110] GRPC error: rpc error: code = InvalidArgument desc = target "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount" is not a valid mount point

> Events:
>   Type     Reason                  Age                   From                     Message
>   ----     ------                  ----                  ----                     -------
>   Warning  FailedScheduling        31m (x4 over 31m)     default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 15 times)
>   Normal   Scheduled               31m                   default-scheduler        Successfully assigned mip-ppr/mls-db-mip-ppr-beiersdorf-1 to minion-9
>   Warning  FailedAttachVolume      30m                   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74" : attachment timeout for volume /subscriptions/a75d78e8-7db2-4364-8dff-76eb48522d3c/resourceGroups/PreProd-EU-MIP-RG/providers/Microsoft.Compute/disks/pvc-disk-dynamic-e752dd64-5c76-11e9-a5cc-000d3a29856b
>   Warning  FailedAttachVolume      29m (x7 over 30m)     attachdetach-controller  AttachVolume.Attach failed for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
>   Normal   SuccessfulAttachVolume  28m                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74"
>   Warning  FailedMount             26m                   kubelet, minion-9        MountVolume.MountDevice failed for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
>   Warning  FailedMount             26m                   kubelet, minion-9        MountVolume.MountDevice failed for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74" : rpc error: code = Internal desc = could not format '\x00' and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount"
>   Warning  FailedMount             6m20s (x11 over 29m)  kubelet, minion-9        Unable to mount volumes for pod "mls-db-mip-ppr-beiersdorf-1_mip-ppr(de532c67-5c76-11e9-9ea8-000d3a269e74)": timeout expired waiting for volumes to attach or mount for pod "mip-ppr"/"mls-db-mip-ppr-beiersdorf-1". list of unmounted volumes=[data]. list of unattached volumes=[data wal-g-archive custom-config mls-db-mip-ppr-beiersdorf-token-59rgc]
>   Warning  FailedMount             2m2s (x18 over 26m)   kubelet, minion-9        MountVolume.MountDevice failed for volume "pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74" : rpc error: code = InvalidArgument desc = target "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount" is not a valid mount point
> 

Any guidance here is greatly appreciated.

**Comment by andyzhangx** [comment]
@sharkymcdongles the error said "could not format '\x00' and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount", have you formated that disk by other file system format before?

**Comment by sharkymcdongles** [comment]
No. This is a newly created dynamically provisioned disk. I will see if I can remove it and allow it to provision a new one.

**Comment by sharkymcdongles** [comment]
I deleted and allowed the pvc to be recreated fresh and the result is the same.

> Events:
>   Type     Reason       Age                    From                Message
>   ----     ------       ----                   ----                -------
>   Warning  FailedMount  10m (x129 over 4h18m)  kubelet, minion-13  MountVolume.MountDevice failed for volume "pvc-d59af162-5e02-11e9-9ea8-000d3a269e74" : rpc error: code = InvalidArgument desc = target "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-d59af162-5e02-11e9-9ea8-000d3a269e74/globalmount" is not a valid mount point
>   Warning  FailedMount  54s (x116 over 4h21m)  kubelet, minion-13  Unable to mount volumes for pod "mls-db-mip-ppr-beiersdorf-1_mip-ppr(d59d347f-5e02-11e9-9ea8-000d3a269e74)": timeout expired waiting for volumes to attach or mount for pod "mip-ppr"/"mls-db-mip-ppr-beiersdorf-1". list of unmounted volumes=[data]. list of unattached volumes=[data wal-g-archive custom-config mls-db-mip-ppr-beiersdorf-token-59rgc]
>

**Comment by andyzhangx** [comment]
@sharkymcdongles thanks for reporting. I have fixed this issue by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/75
pls follow below way to retry, thanks:
 - delete the original pod
 - redeploy azure disk csi driver:
```
kubectl delete ds csi-azuredisk -n kube-system
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/azuredisk-csi-driver.yaml
```
