### ISSUE TITLE
ListVolumes starting token(0) is greater than total number of disks

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#769]
**What happened**:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/768/pull-azuredisk-csi-driver-e2e-single-az/1372389810689282048/build-log.txt

utils.go:100] GRPC error: rpc error: code = FailedPrecondition desc = ListVolumes starting token(0) is greater than total number of disks

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

@sunpa93 is this a bug?

**Comment by sunpa93** [comment]
I will look into it :)
