### ISSUE TITLE
Emit cloudprovider metrics for azuredisk

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/azuredisk-csi-driver#772]
We should emit cloudprovider metrics for azuredisk operations which are similar to what is reported by in-tree driver.

(Or if we are not going to emit these metrics anymore, we should deprecate them in k/k repo with a good reason)

**Comment by andyzhangx** [comment]
it's already implemented in current csi driver: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/metrics
