### ISSUE TITLE
azure cloud provider throttled for operation DiskCreateOrUpdate with reason 'client throttled'

### ISSUE THREAD

**Issue by axelgMS** [kubernetes-sigs/azuredisk-csi-driver#773]
**What happened**:

CRI 233254165 - Not able to provision a disk, as the error below is thrown:

_**Warning  ProvisioningFailed    23m                   disk.csi.azure.com_csi-azuredisk-controller-XYZ  failed to provision volume with StorageClass 'managed-csi': rpc error: code = Unknown desc = Retriable: true, RetryAfter: 297s, HTTPStatusCode: 0, RawError: azure cloud provider throttled for operation DiskCreateOrUpdate with reason 'client throttled'**_

From CCP logs

**_2021-03-22 04:54:11.0000000        csi-provisioner                                                  E0322 04:54:11.477187       1 controller.go:939] error syncing claim "XYZ": failed to provision volume with StorageClass "managed-csi": rpc error: code = Unknown desc = Retriable: false, RetryAfter: 302s, HTTPStatusCode: 429, RawError: Retriable: false, RetryAfter: 302s, HTTPStatusCode: 429, RawError: {"error":{"code":"SubscriptionRequestsThrottled","message":"Number of write requests for subscription 'XYZ' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '303' seconds."}}_**

**What you expected to happen**:

Looks like CSI driver snapshot is making a lot of PUT operations to DiskRP - causing throttling.

**How to reproduce it**:  see CRI 233254165

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
fixed by delete snapshot objects
