### ISSUE TITLE
use empty PUT operation if disk is in data disk list while vm is in failed state

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#780]
**What happened**:
There is case that vm is in failed state, disk is already in data disk list while it's actually not attached, should use empty PUT operation to make it work

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
update:
In current design, we don't check vm status when attach/detach status, to fix this issue, if one disk is already attached to one node, need one extra API to check whether current vm is in failed status, that would cause extra API call, not sure it's worthwhile to do that.

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/cdcb750196a0fb1f4b896c69c72bb8e26a8f20d1/pkg/azuredisk/controllerserver.go#L411-L412

**Comment by MSSedusch** [comment]
if the disk attach fails but the disk is persisted in the goal state of the VM on Azure side, the K8s cluster will currently not recover unless there is another disk operation that would send a PATCH request to Azure for that VM.
Would it be an option to remember that the last attach operation was not successful and ignore that the disk is already attached to the node and send a PATCH request anyway?
