### ISSUE TITLE
 [single-az] should create an inline volume by in-tree driver [kubernetes.io/azure-disk]

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/azuredisk-csi-driver#793]
**What happened**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101129/pull-kubernetes-e2e-aks-engine-azure-disk-windows-dockershim/1382451192465985536

 AzureDisk CSI Driver End-to-End Tests: Pre-Provisioned
failed for 

```
Panic: runtime error: invalid memory address or nil pointer dereference

Full stack:
sigs.k8s.io/azuredisk-csi-driver/test/e2e.glob..func2.3.7()
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:269 +0x1f4
sigs.k8s.io/azuredisk-csi-driver/test/e2e.TestE2E(0xc0000abc80)
	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/suite_test.go:201 +0x1b6
testing.tRunner(0xc0000abc80, 0x1f6b4b8)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
```

**What you expected to happen**:
seems to be related to #789
/cc @andyzhangx 
**How to reproduce it**:
ci failure.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks, it's just fixed, pls rerun test.
