### ISSUE TITLE
Conflicting requests result in slow volume attachment

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-sigs/azuredisk-csi-driver#811]
**What happened**:
When running the [OSS E2E volume stress test](https://github.com/kubernetes/kubernetes/blob/v1.21.0/test/e2e/storage/testsuites/volume_stress.go#L106) with the Azuredisk CSI driver, I encounter very slow volume attachment latencies. For most pods, attachment takes anywhere from 25 seconds to nearly 2 minutes.

For context, this test was ran with 1, 10, and 50 pod workloads, 10 restarts, on a 10 node cluster of [Standard_DS2_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) (2 vCPU and 7 GB of memory). The CSI external-attacher is running with the default 10 worker threads.

When looking at the CSI driver logs, I find this error occurs frequently:
```
I0428 01:35:14.012144       1 azure_armclient.go:308] Received error in sendAsync.send: resourceID: <REDACTED>, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "Conflict",
    "message": "The request failed due to conflict with a concurrent request. To resolve it, please refer to https://aka.ms/activitylog to get more details on the conflicting requests."
  }
}
```

I tried looking in the activity log however no additional details were provided on these failing requests.

The result of this issue is very slow pod start times. From my understanding this is because the CSI external-attacher has to  re-initiate attachment repeatedly until the request goes through.

**What you expected to happen**:

Ideally attachment succeeds without conflicting request errors. I'm unsure what can be done about this on the CSI driver side.

**How to reproduce it**:

```bash
# make the E2E test binary in k8s
make WHAT=test/e2e/e2e.test

# create a testdriver.yaml for the azuredisk CSI driver
cat <<EOF | tee testdriver.yaml
StorageClass:
  FromExistingClassName: <INSERT EXISTING AZUREDISK STORAGECLASS NAME HERE>
SnapshotClass:
  FromExistingClassName: <INSERT EXISTING AZUREDISK VOLUMESNAPSHOTCLASS NAME HERE (actually not required for this)>
DriverInfo:
  Name: disk.csi.azure.com
  RequiredAccessModes:
  - ReadWriteOnce
  Capabilities:
    persistence: true
    multipods: true
    exec: true
    block: true
    fsGroup: true
    topology: true
    controllerExpansion: true
    nodeExpansion: true
    volumeLimits: false
    snapshotDataSource: true
  SupportedSizeRange:
    Min: 1Gi
  StressTestOptions:
    NumPods: 10
    NumRestarts: 10
EOF

# run E2E test with testdriver
e2e.test \
  -ginkgo.focus="External.Storage.*default fs.*volume-stress" \
  --storage.testdriver=testdriver.yaml
```

**Environment**:
- CSI Driver version: v1.1.0
- Kubernetes version (use `kubectl version`): v1.19.9
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 5.4.0-1046-azure
- Install tools:
- Others:

**Comment by chrishenzie** [comment]
Some general questions:
- What volume attachment / pod startup times do others observe?
- Do others encounter this issue?

**Comment by andyzhangx** [comment]
the error is returned by azure ARM service, did it recover finally?

**Comment by chrishenzie** [comment]
Yes it recovers, but it takes a long time to do so. Running the above test with 50 pods (each with their own PVC), restarting 10 times, on a 10 node worker pool the average time for a pod to start was over 6 minutes, and the longest observed pod start time was 14.5 minutes.
