### ISSUE TITLE
MULTI_NODE_MULTI_WRITER not supported for managed-csi on Azure

### ISSUE THREAD

**Issue by mariojacobo** [kubernetes-sigs/azuredisk-csi-driver#827]
**What happened**:

Azure shared disks do not seem to work with AKS on Azure

**What you expected to happen**:

**How to reproduce it**:

storage class, PV and PVC verbatim: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/sharedisk

**Anything else we need to know?**:

Error logs: 

  Normal   WaitForFirstConsumer  31s               persistentvolume-controller                                                                        waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  8s (x3 over 31s)  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
  Normal   Provisioning          2s (x6 over 31s)  disk.csi.azure.com_csi-azuredisk-controller-746bc85c95-cwn9h_59cbd662-be9d-4897-99b9-66900ce360e9  External provisioner is provisioning volume for claim "default/pvc-azuredisk"
  Warning  **ProvisioningFailed    2s (x6 over 31s)  disk.csi.azure.com_csi-azuredisk-controller-746bc85c95-cwn9h_59cbd662-be9d-4897-99b9-66900ce360e9  failed to provision volume with StorageClass "managed-csi-premium": rpc error: code = **InvalidArgument desc = Volume capability(MULTI_NODE_MULTI_WRITER) not supported****

**Environment**:
- CSI Driver version: 
- Kubernetes version (use `kubectl version`): 1.18.14
- OS (e.g. from /etc/os-release): ubutnu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
what's your storage class config and what's the `maxShares` value?

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/bb4c26e6602f170c42a1738cc48e5008b578331c/pkg/azuredisk/controllerserver.go#L190-L198

**Comment by mariojacobo** [comment]
@andyzhangx 

$ kubectl get sc managed-csi -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2021-05-05T12:47:24Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: managed-csi
  resourceVersion: "14764"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/managed-csi
  uid: b0ac2259-9fd7-4d0a-b9d3-d91c064e8edd
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

maxShares: 2

**Comment by mariojacobo** [comment]
@andyzhangx yes, you are completely right. I know what I was doing wrong. I created the AKS cluster with the CSI drivers installed already, meaning the storage classes are created already. Now, I created a separate storage class with maxShares and everything is working. thank you for the quick fix on this, you rock !
