### ISSUE TITLE
aks-engine-windows-containerd-azure-disk-master test failing

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/azuredisk-csi-driver#829]
**What happened**:

The job https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-azure-disk-master is failing during before testsuite.

```
    Last State:  Terminated
      Reason:    StartError
      Message:   failed to create containerd task: hcsshim::CreateComputeSystem cd468bdc693dbe6d59bc68b3f49e0b235310723b9cfd54f1ff607c775aecd36f: The directory name is invalid.
(extra info: {"Owner":"containerd-shim-runhcs-v1.exe","SchemaVersion":{"Major":2,"Minor":1},"Container":{"GuestOs":{"HostName":"csi-azuredisk-node-win-c7jpb"},"Storage":{"Layers":[{"Id":"f2f3e63e-ba3b-5e5d-a46d-4c1b86766dc6","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\8"},{"Id":"dc6e4d16-f2d3-50b0-84ad-b520078bac65","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\7"},{"Id":"bbb3b587-52e4-534d-b0e8-708d7ad7f642","Path":"C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\6"}],"Path":"\\\\?\\Volume{30f74a5c-3f86-47d2-a2eb-aaa41dca9ae3}\\"},"MappedDirectories":[{"HostPath":"C:\\var\\lib\\kubelet\\plugins\\disk.csi.azure.com","ContainerPath":"C:\\csi"},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\cbd5a7a9-d06b-4611-bd99-8d1d04af2145\\containers\\liveness-probe\\1185c5ed","ContainerPath":"c:\\dev\\termination-log"},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\cbd5a7a9-d06b-4611-bd99-8d1d04af2145\\volumes\\kubernetes.io~projected\\kube-api-access-hrgm9","ContainerPath":"c:\\var\\run\\secrets\\kubernetes.io\\serviceaccount","ReadOnly":true},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\cbd5a7a9-d06b-4611-bd99-8d1d04af2145\\etc-hosts","ContainerPath":"C:\\Windows\\System32\\drivers\\etc\\hosts"}],"Memory":{"SizeInMB":200},"Processor":{"Maximum":500},"Networking":{"Namespace":"fd62c3c1-bded-458f-b036-67496ad30907"}},"ShouldTerminateOnLastHandleClosed":true}): unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 00:00:00 +0000
      Finished:     Wed, 05 May 2021 00:58:50 +0000
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:     10m
      memory:  20Mi
    Environment:
      CSI_ENDPOINT:  unix://C:\\csi\\csi.sock
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): main branch
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jsturtevant** [comment]
looks like azurefile is the same issue: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-azure-file-windows-containerd/1389733312267816960

**Comment by andyzhangx** [comment]
it's not essential test yet, and I am tuning the containerd windows test with the containerd fix, it's only one or two test case failures now.

**Comment by andyzhangx** [comment]
following two test cases could not pass, there could be issue in data store

https://prow.k8s.io/log?container=test&id=1390283936113889280&job=pull-azuredisk-csi-driver-e2e-windows-containerd

```
[91m[1mSummarizing 2 Failures:[0m

[91m[1m[Fail] [0m[90mDynamic Provisioning [0m[0m[single-az] [0m[91m[1m[It] should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [0m
[37m/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:602[0m

[91m[1m[Fail] [0m[90mDynamic Provisioning [0m[0m[single-az] [0m[91m[1m[It] should create a statefulset object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [0m
[37m/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/kubernetes/test/e2e/framework/util.go:602[0m

[1m[91mRan 18 of 45 Specs in 3783.726 seconds[0m
[1m[91mFAIL![0m -- [32m[1m16 Passed[0m | [91m[1m2 Failed[0m | [33m[1m0 Pending[0m | [36m[1m27 Skipped[0m
--- FAIL: TestE2E (3783.73s)
```

**Comment by andyzhangx** [comment]
containerd windows e2e tests pass with both in-tree and csi drivers now!

**Comment by andyzhangx** [comment]
for in-tree, run 
```
/test pull-kubernetes-e2e-aks-engine-azure-disk-windows-containerd
/test pull-kubernetes-e2e-aks-engine-azure-file-windows-containerd
```

**Comment by andyzhangx** [comment]
containerd windows tests pass for in-tree azure disk & file drivers now:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure-file-windows-containerd
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure-disk-windows-containerd

Will run a few days, enable it by default if it's stable enough

**Comment by devigned** [comment]
@andyzhangx, looks lilke those jobs are still failing (5/18).

**Comment by andyzhangx** [comment]
> @andyzhangx, looks lilke those jobs are still failing (5/18).

@devigned azure file containerd windows test failure is due to cluster set up failure, and for azure disk, I have just increased sleeping time for containerd test, let's see whether it could work.

**Comment by CecileRobertMichon** [comment]
@andyzhangx it's hard to collect good signal since the job is only running every 48 hours but in the last 3 runs (since your comment above), 2 passed and 1 failed with:
```
AzureDisk CSI Driver End-to-End Tests: Dynamic Provisioning [single-az] should detach disk after pod deleted [disk.csi.azure.com] [Windows]&nbsp;expand_less | 6m43s
-- | --
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:676 Expected     &lt;compute.DiskState&gt;: Unattached to equal     &lt;compute.DiskState&gt;: Attached /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go:97
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-azure-disk-windows-containerd/1395532500918341632

**Comment by andyzhangx** [comment]
> @andyzhangx it's hard to collect good signal since the job is only running every 48 hours but in the last 3 runs (since your comment above), 2 passed and 1 failed with:
> 
> ```
> AzureDisk CSI Driver End-to-End Tests: Dynamic Provisioning [single-az] should detach disk after pod deleted [disk.csi.azure.com] [Windows]&nbsp;expand_less | 6m43s
> -- | --
> /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:676 Expected     &lt;compute.DiskState&gt;: Unattached to equal     &lt;compute.DiskState&gt;: Attached /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go:97
> ```
> 
> https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-azure-disk-windows-containerd/1395532500918341632

@CecileRobertMichon I will add waitForSuccess loop for this test failure since sometimes disk detach costs a lot more time.

**Comment by andyzhangx** [comment]
@CecileRobertMichon should be fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/863
