### ISSUE TITLE
Hostname != Virtual Machine Name will not create the node container

### ISSUE THREAD

**Issue by Flowman** [kubernetes-sigs/azuredisk-csi-driver#869]
**What happened**:

If hostname is not the same as virtual machine name it cannot find the virtual machine in azure when creating the node container.

**What you expected to happen**:

Be able to use different hostname than the virtual machine name.

**How to reproduce it**:

Use a different hostname than the virtual machine name.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: Latest
- Kubernetes: version v1.20.7+k3s1
- OS: 20.04.2 LTS (Focal Fossa)
- Kernel: 5.4.0-1047-azure #49-Ubuntu SMP Thu Apr 22 14:30:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andyzhangx** [comment]
can you provide the driver error logs?

**Comment by Flowman** [comment]
The machine name is: prefix-hostname
Hostname is just: hostname

It takes the hostname and fills in the xxx so it will never find the VM.

I0528 06:54:10.071680       1 azure_vmclient.go:132] Received error in vm.get.request: resourceID: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachines/xxx, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/virtualMachines/xxx' under resource group 'xxx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
I0528 06:54:10.071745       1 azure_wrap.go:194] Virtual machine "xxx" not found
E0528 06:54:10.071758       1 azure_standard.go:563] as.GetInstanceTypeByNodeName(xxx) failed: as.getVirtualMachine(rancher) err=instance not found

**Comment by andyzhangx** [comment]
so the hostname is your k8s agent node name when you run `kubectl get node`?

**Comment by Flowman** [comment]
for an example the VM called 'company-master-001'

NAME                       STATUS   ROLES                       AGE     VERSION
master                      Ready    control-plane,etcd,master   3h35m   v1.20.7+k3s1

The node name is not the same as the VM name.

**Comment by andyzhangx** [comment]
node name should be same as VM name, azure disk driver only knows `node name`, it's not aware of VM name.

**Comment by Flowman** [comment]
Easy good to know not to use the guest host name on the VM.
