### ISSUE TITLE
version 1.3.0 is failing with error "Resource name may not be empty"

### ISSUE THREAD

**Issue by gauravAggrahari** [kubernetes-sigs/azuredisk-csi-driver#889]
Hi,
I am trying to run the azuredisk-csi-driver version 1.3.0 which is resulting in an error when trying to read from secret. 
The error it is running into is "Resource name may not be empty".
The same setup is working fine for 1.2.0.

Thank you.

**Comment by andyzhangx** [comment]
that's a regression fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/886, pls stay with 1.2.0 or wait for 1.4.0 release, thanks.

**Comment by gauravAggrahari** [comment]
Thank @andyzhangx for quick response.

**Comment by andyzhangx** [comment]
fixed with v1.4.0 release
