### ISSUE TITLE
Snapshot CRD conflicts with preinstalled CRD in AKS 1.21 clusters

### ISSUE THREAD

**Issue by scoof** [kubernetes-sigs/azuredisk-csi-driver#926]
**What happened**: When deploying chart with snapshots enabled to a 1.21 AKS cluster, helm complains that the VolumeSnapshots CRD already exists and can't be imported.

**What you expected to happen**: To be able to install chart alongside the default deployment in AKS 1.21

**How to reproduce it**: Deploy AKS 1.21. Install chart with snapshot.enabled: true

**Anything else we need to know?**: CRDs should probably not be included in templates, but rather in a separate chart or in a crds folder: https://helm.sh/docs/topics/charts/#the-chart-file-structure (but removing the crd from templates is likely a breaking change for existing installations, so maybe have an option to disable it)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21

**Comment by rhummelmose** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
there should be only one snapshot controller in one cluster, and snapshot controller is already installed by default on aks 1.21, so helm install with `snapshot.enabled: true` is not supported

**Comment by scoof** [comment]
Makes sense, thanks.
(Having the CRD as part of templates is going to give people a hard time when migrating to 1.21, since Helm will try to delete the CRD as part of the uninstall)
