### ISSUE TITLE
Support for AAD pod-managed identities

### ISSUE THREAD

**Issue by scoof** [kubernetes-sigs/azuredisk-csi-driver#936]
**Is your feature request related to a problem?/Why is this needed**
I thought I had support for pod-managed identities by providing a way to label the pods, but as I dug deeper, I realized it wasn't enough.

**Describe the solution you'd like in detail**
There are currently two things that needs to be changed to fully support pod-managed identities:
* hostNetwork: false
* Injecting azure.json with the correct identity or without identity at all.

I have this working by mounting a manually configured ConfigMap in the pod, and using the azure-cred-file configmap to point to this CM.

Disabling hostNetwork is easy enough, but injecting azure.json with at least tenant, subscription and resource-group is a bit harder, since we need to pick up those from somewhere. I don't know if the only option is to provide them as values to the helm chart and render the azure.json file manually.

This should also remove the requirement to mount any hostPath volumes in the pod.

**Describe alternatives you've considered**
The alternative is to keep using the node managed identity, and that would be a less secure option, since that would delegate too many rights to the CSI driver.

**Comment by andyzhangx** [comment]
for the `hostNetwork: false` setting, I could customize this setting in helm install, by default, `hostNetwork` is true since [optimize disk performance feature](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/enhancements/feat-add-ability-to-tune-azuredisk-performance-parameters.md) depends on this setting.

**Comment by andyzhangx** [comment]
PR(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/939) would add customized `hostNetwork` setting in helm install.

**Comment by scoof** [comment]
> for the `hostNetwork: false` setting, I could customize this setting in helm install, by default, `hostNetwork` is true since [optimize disk performance feature](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/enhancements/feat-add-ability-to-tune-azuredisk-performance-parameters.md) depends on this setting.

As far as I can see (device_perf_linux.go) this feature depends on querying the Azure API for data about disks, and tweaking stuff in /sys? The first should use AAD Pod ID, so would work fine with `hostNetwork: false`, while the latter just uses a hostPath? Am I missing anything?

**Comment by scoof** [comment]
The /csi/csi.sock unix socket mount in the node pod does seem to have issues with `hostNetwork: false` though

**Comment by scoof** [comment]
> The /csi/csi.sock unix socket mount in the node pod does seem to have issues with `hostNetwork: false` though.
> 
> I am mostly focusing on the controller pod at the moment, since that has the largest attack surface.

I don't think it's the socket mount that is creating problems, but rather that azuredisk is not reaching the listening phase. It stops at: `skus.go:121] NewNodeInfo: Starting to populate node and disk sku information.` - so the problem is probably that it tries to get a token from IMDS, but is not authorized for that user. I'll try mounting an azure.json with an identity it can assume.

**Comment by andyzhangx** [comment]
> > The /csi/csi.sock unix socket mount in the node pod does seem to have issues with `hostNetwork: false` though.
> > I am mostly focusing on the controller pod at the moment, since that has the largest attack surface.
> 
> I don't think it's the socket mount that is creating problems, but rather that azuredisk is not reaching the listening phase. It stops at: `skus.go:121] NewNodeInfo: Starting to populate node and disk sku information.` - so the problem is probably that it tries to get a token from IMDS, but is not authorized for that user. I'll try mounting an azure.json with an identity it can assume.

@scoof device_perf is not an essential feature(disabled by default now), I think that's ok, you could go with `hostNetwork: false`

**Comment by scoof** [comment]
I have the node pods working with `hostNetwork: false` now - they just required a proper azure.json to be able to inspect the azure config

**Comment by scoof** [comment]
device_perf fails because the devices in `/sys/block` are symlinks to `/sys/devices`, and that is mounted ro. It works if I add a `hostPath` volume for `/sys/devices`, but I don't know if that is too broad (at least it is less broad than the full sysfs that `hostNetwork: true` provides)

**Comment by andyzhangx** [comment]
> device_perf fails because the devices in `/sys/block` are symlinks to `/sys/devices`, and that is mounted ro. It works if I add a `hostPath` volume for `/sys/devices`, but I don't know if that is too broad (at least it is less broad than the full sysfs that `hostNetwork: true` provides)

@scoof device_perf depends on IMDS, so it won't work if hostNetwork is disabled, that' expected:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c8f75374ec5c60cc25e44530116f4fc4e324359c/pkg/optimization/skus.go#L120-L131

About how to set cloud config, you could follow: https://github.com/kubernetes-sigs/azuredisk-csi-driver#prerequisite

**Comment by scoof** [comment]
> > device_perf fails because the devices in `/sys/block` are symlinks to `/sys/devices`, and that is mounted ro. It works if I add a `hostPath` volume for `/sys/devices`, but I don't know if that is too broad (at least it is less broad than the full sysfs that `hostNetwork: true` provides)
> 
> @scoof device_perf depends on IMDS, so it won't work if hostNetwork is disabled, that' expected:

But the whole point of this exercise is to use the Pod Identity IMDS instead of the node IMDS, since that will allow us to constrain the identities the pod is able to assume.

**Comment by andyzhangx** [comment]
> > > device_perf fails because the devices in `/sys/block` are symlinks to `/sys/devices`, and that is mounted ro. It works if I add a `hostPath` volume for `/sys/devices`, but I don't know if that is too broad (at least it is less broad than the full sysfs that `hostNetwork: true` provides)
> > 
> > 
> > @scoof device_perf depends on IMDS, so it won't work if hostNetwork is disabled, that' expected:
> 
> But the whole point of this exercise is to use the Pod Identity IMDS instead of the node IMDS, since that will allow us to constrain the identities the pod is able to assume.

@scoof just disable hostNetwork since device_perf optimization feature is not a required feature for now. Maybe we could leverage Pod Identity IMDS to get node info in the future. 
cc @bcho

**Comment by scoof** [comment]
> @scoof just disable hostNetwork since device_perf optimization feature is not a required feature for now. Maybe we could leverage Pod Identity IMDS to get node info in the future.

I think we're talking past each other. Device_perf works fine with Pod Identity, when configured in the same manner as the controller, and when adding a hostpath volumemount to /sys/devices.
By labelling the pod with aadpodidentity, we can allow the pod to assume a particular identity (which is more constrained than the kubelet identity), and then it's able to get node info just fine, since Pod Identity exposes a limited IMDS endpoint.

**Comment by scoof** [comment]
> About how to set cloud config, you could follow: https://github.com/kubernetes-sigs/azuredisk-csi-driver#prerequisite

My problem is that there's no way to inject an azure.json that is specific to this particular deployment - the Secret method relies on a hard coded name, which will clash with any other pods using the same method with the same name.
I think viable solutions are either
* to allow the user to specify another secret name (this would require code changes and not just chart changes I think)
* to allow the user to specify a custom azure.json content, which would then be deployed as a configmap or secret, and mounted into the pods

I think the latter is the better option, and I can provide a PR for that if you wish

**Comment by andyzhangx** [comment]
@scoof secret name is defined here:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/c8f75374ec5c60cc25e44530116f4fc4e324359c/pkg/azuredisk/azure.go#L56-L57

do you think we should specify `controller.cloudConfigSecretName`,  `controller.cloudConfigSecretNamespace`, `node.cloudConfigSecretName`,  `node.cloudConfigSecretNamespace` in helm chart?

**Comment by scoof** [comment]
@andyzhangx since we already have a way of pointing to an alternative azure.json, I think it would make more sense to just have the helm chart add a secret, mount that secret and point to it using AZURE_CREDENTIAL_FILE, that would allow the user to just specify the contents

**Comment by andyzhangx** [comment]
> @andyzhangx since we already have a way of pointing to an alternative azure.json, I think it would make more sense to just have the helm chart add a secret, mount that secret and point to it using AZURE_CREDENTIAL_FILE, that would allow the user to just specify the contents

@scoof that's two options: 1)  let driver read from different secrets 2) project different secrets to driver cloud config path.
anyway we need to specify `controller.cloudConfigSecretName, controller.cloudConfigSecretNamespace, node.cloudConfigSecretName, node.cloudConfigSecretNamespace` in helm chart since node and controller may need different cloud configs.

**Comment by scoof** [comment]
> @scoof that's two options: 1) let driver read from different secrets 2) project different secrets to driver cloud config path.
> anyway we need to specify `controller.cloudConfigSecretName, controller.cloudConfigSecretNamespace, node.cloudConfigSecretName, node.cloudConfigSecretNamespace` in helm chart since node and controller may need different cloud configs.

I have no preference of one over the other.
