### ISSUE TITLE
Permissions issue for Azure CSI Disk Driver Based Disks.

### ISSUE THREAD

**Issue by abhioncbr** [kubernetes-sigs/azuredisk-csi-driver#949]
**What happened**:
It is related to running MongoDB in the AKS cluster. 
- We decided to use the Azure CSI driver-based dynamic PV to persist the MongoDB stateful sets. We are getting the permissions issues for the attached disk for the MongoDB pods, hence failing the workload.
-  However, with StorageClass based on `kubernetes.io/azure-disk`, the workload runs absolutely fine without any permissions issues. 
- Events of the namespace
```bash 
0s Warning Unhealthy pod/MongoDB-ops-manager-db-0 Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied For same MongoDB manifest 
```
- with Azure CSI Disk driver based disks, file permissions are as follows
```bash
ls -ltr /var/log/mongodb-mms-automation/ -rw-rw-r-- 1 2000 root 846753 Jul 23 12:52 readiness.log
```
- with `kubernetes.io/azure-disk` StorageClass based disks, file permissions are as follows
```bash
ls -ltr /var/log/mongodb-mms-automation/ -rw-rw-r-- 1 2000 2000 846753 Jul 23 12:52 readiness.log
```
**What you expected to happen**:
File permissions for the applied same manifest should be the same on disk like of the `kubernetes.io/azure-disk` based disk. 

**How to reproduce it**:
Apply [MongoDB OpsManager manifest](https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/samples/ops-manager/ops-manager.yaml) based on Azure CSI driver-based disk

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.2.0
- Kubernetes version (use `kubectl version`): AKS 1.21.1
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.4.0-1047-azure, 18.04.1-Ubuntu, x86_64, GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
should be related to this issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/901#issuecomment-867218476, would you use the workaround `fsType: ext4` in storage class as mentioned in the above issue. CSI driver v1.4.0 is rolling out this week which could solve this issue on aks 1.21, need waiting one more week.

**Comment by abhioncbr** [comment]
Let me give it a try. Thanks
