### ISSUE TITLE
Azure Stack Cloud does not support "NetworkAccessPolicy"

### ISSUE THREAD

**Issue by songjiaxun** [kubernetes-sigs/azuredisk-csi-driver#957]
**What happened**:
After [`NetworkAccessPolicy`](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/147734c75445b522f63f75ebb98d159b79954885/pkg/azuredisk/controllerserver.go#L350) is introduced, Azure Stack Cloud throws error when creating managed disk: 
```
I0802 20:39:08.747781   50487 controllerserver.go:290] begin to create azure disk(citest-1627936742) account type(Standard_LRS) rg(mc_uss_e2eaks-nls_redmond) location() size(2) diskZone() maxShares(0)
I0802 20:39:08.747805   50487 azure_managedDiskController.go:88] azureDisk - creating new managed Name:citest-1627936742 StorageAccountType:Standard_LRS Size:2
I0802 20:39:09.019545   50487 azure_armclient.go:308] Received error in sendAsync.send: resourceID: https://management.redmond.ext-n25r1310.masd.stbtest.microsoft.com/subscriptions/9451ca98-98e8-4ba8-b50b-dc7497a07255/resourceGroups/mc_uss_e2eaks-nls_redmond/providers/Microsoft.Compute/disks/citest-1627936742?api-version=2019-03-01, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "BadRequest",
    "message": "Could not find member 'networkAccessPolicy' on object of type 'DiskProperties'. Path 'properties.networkAccessPolicy', line 1, position 113.",
    "target": "diskDescription.properties.networkAccessPolicy"
  }
}
```

**What you expected to happen**:
On Azure Stack Cloud, bypass setting networkAccessPolicy.

**How to reproduce it**:
Run sanity or integration test.

**Anything else we need to know?**:
Azure Stack Cloud supports the following API version:
```
            "apiVersions": [
                "2019-11-01",
                "2019-07-01",
                "2019-03-01",
                "2018-09-30",
                "2018-06-01",
                "2018-04-01",
                "2017-03-30"
            ],
```

The `NetworkAccessPolicy` is supported since 2020-06-01.

**Environment**:
- CSI Driver version: v1.5.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
can you work out a PR to remove `NetworkAccessPolicy` for azure stack?

**Comment by bottkars** [comment]
was about to open the same. also tried ro install using helm parameter --set feature.enableFSGroupPolicy=false but obviously was ignored

**Comment by songjiaxun** [comment]
I created a PR to fix this issue for Azure Stack Cloud. @bottkars, I created this private image including the fix: `jiaxsong/azuredisk-csi:v1.6.0` for e2e tests, and the tests all passed, just in case you want to try it from your side.

**Comment by andyzhangx** [comment]
this `NetworkAccessPolicy` issue on azure stack should be only on test cases, right? if azure stack does not support `NetworkAccessPolicy`, just don't specify this parameter in storage class.

**Comment by andyzhangx** [comment]
> was about to open the same. also tried ro install using helm parameter --set feature.enableFSGroupPolicy=false but obviously was ignored

@bottkars what is the `--set feature.enableFSGroupPolicy=false` issue? if it's set as `false`, will be set as `fsGroupPolicy: ReadWriteOnceWithFSType` by default on 1.20.0+

**Comment by andyzhangx** [comment]
`v1.5.1` is already published with the azure stack fix.
