### ISSUE TITLE
Document specific Helm Parameters for 1.20 with GA Snapshotter ( Storageclass, Driverparameters )

### ISSUE THREAD

**Issue by bottkars** [kubernetes-sigs/azuredisk-csi-driver#958]
**Is your feature request related to a problem?/Why is this needed**

Document related Driver Parameters for k9s 1.2x

**Describe the solution you'd like in detail**
When Using Helm to install Drivers on a AKS Cluster, Please specify
`--set snapshot.apiVersion=ga`
Also, make  sure to create the Correct Snapshot Storageclass:

`apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass     
metadata:     
  name: csi-azuredisk-vsc    
driver: disk.csi.azure.com    
deletionPolicy: Delete    
parameters:    
  incremental: "true"  # available values: "true", "false" ("true" by default for Azure Public Cloud, and "false" by default for Azure Stack Cloud)  
`

**Additional context**
If not specified Snapshot createion fails on 1.2x Clusters

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/959
